[3 - 4단계 방탈출 예약 대기] 안나(김민겸) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #103
Opened 2024-05-22 08:12 UTC by Mingyum-Kim

안녕하세요 비밥 ~
3, 4단계 미션 구현 후 다시 돌아왔습니다 🤗

이번 미션에서는 러프하게 주어진 요구사항을 바탕으로 고민하여 기능을 설계해보았습니다. 
코드에서 참고가 될 수 있도록 기능과 설계에 대한 세부사항을 아래에 기재해놓겠습니다. 💪

## 기능 및 설계

###  3단계 - 예약 대기 기능

**중복 예약이 불가능하도록 구현하세요.**

- 예약하는 경우 
(1) 날짜, 시간, 테마가 중복되는 경우 예약을 하지 않도록 구현

- 예약 대기 등록하는 경우 
(1) 이미 예약한 사용자가 예약 대기할 수 없도록 구현 
(2) 이미 예약 대기 등록한 사용자가 예약 대기할 수 없도록 구현

### 4단계 - 예약 대기 관리

**예약 취소가 발생 시 예약 승인이 되는 기능을 구현하세요.**

자동으로 승인하도록 구현하였습니다.

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/67851124/56a7aa95-6759-4cad-ac08-6de84b8c1e18)

위와 같이 예약 대기가 있을 때 bibob, brown은 각각 1번째, 2번째 대기자입니다.

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/67851124/5f8213ca-288f-4bff-870d-db800ca5b2fa)

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/67851124/1131f344-6dd0-4e44-9704-5c93c51b4a0d)

기존 예약의 예약 취소가 발생하는 경우 아래와 같이 1번째 예약 대기자인 bibob이 자동으로 예약 상태로 변경됩니다.

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/67851124/50a4c3ad-6b2d-4691-a846-b8ef8cbfa2da)

궁금한 점은 코드에 달아놓겠습니다.
이번 리뷰도 잘 부탁드립니다. 🙋‍♀️🙇‍♀️

2024-05-22 08:14 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
지난 미션에서 남긴 리뷰에 대한 답변입니다.

[답변]

@transactional을 사용하면 실제 프로덕트 코드에서 발생할 수 있는 LazyInitializationException을 테스트 코드에서 검증해주지 못하는 것이 문제라는 것을 알게 되었습니다. 하지만 spring.jpa.open-in-view=true 해당 설정을 통해서 @Transcational을 붙이지 않아도 지연 로딩이 가능했습니다. 따라서 테스트 코드에서 @transactional을 사용하는 것이 괜찮다는 판단을 하였는데, 혹시 다른 의견이 있다면 전달 부탁드립니다.

2024-05-22 23:16 UTC, pci2676 requested changes
조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

2024-05-23 07:53 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
[답변] 

테스트에서 `@Transactional`을 사용한 이유는 직접 트랜잭션을 관리하지 않고도 테스트 메서드마다 영향을 주지 않기 위해 사용하였습니다. 즉, 편리하게 **롤백 테스트**를 하기 위함입니다.

제가 남긴 답변은 비밥이 질문한 **`@Transcational`을 테스트에서 사용하였을 때 부작용**에  대한 글이었습니다. `@Transactional`을 테스트에서 사용하였을 때 `@Transactional`을 사용하지 않은 서비스 레이어에서 발생할 수 있는 오류 중 하나가 `LazyInitializationException`이 있습니다. 이 예외는 트랜잭션이 종료된 경우 지연로딩을 사용할 때 발생합니다.

> spring.jpa.open-in-view=true 이 어떠한 기능을 수행하는지 알고 계실까요?

open-in-view는 OSIV (Open Session In View) 는 트랜잭션이 종료되어도 영속성 컨텍스트를 열어두는 기능입니다.  
서비스 레이어에 `@Transactional`이 없어도 이 설정에 의해 영속성 컨텍스트가 존재하니 굳이 `@Transactional`를 붙이지 않아도 되나보다! 하고 이해했습니다. 

하지만 `OSIV 의 역할 = 트랜잭션을 관리하지 않아도 되게 한다` 라는 식으로 받아들인 건 옳지 않은 접근이었던 것 같아요. 서비스에 `@Transactional`을 붙이는 것은 원자성을 보장하기 위함인데, 영속성 컨텍스트 관점에서만 생각했던 것 같네요.

테스트 코드의 역할은 프로덕션 코드를 검증하는 것인데 테스트 코드에서만 `@Transactional`을 붙임으로서 다른 환경에서 동작하게 되는 것이니까요!
그래서 OSIV를 false로 설정해두고 영속성 컨텍스트를 사용하는 서비스 레이어에서 `@Transactional`를 추가하여 정상적으로 동작하게끔 수정하였습니다 👍

2024-05-23 07:56 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/AdminReservationServiceTest.java
>  @Transactional
[반영 완료] 

위 리뷰 답변 에서 말씀 드린 것처럼 서로 다른 환경의 테스트이므로 트랜잭션 관리의 부재 때문에 프로덕션 레벨에서 생길수 있는 여러 오류를 잡지 못할 수 있겠네요. (데이터 무결성, 명확하지 않은 경계 등 ..) 

서비스 코드에 `@Transactional`을 추가하는 것으로 수정하였습니다.

2024-05-23 08:25 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        validateAlreadyReserved(saveRequest.date(), saveRequest.timeId(), saveRequest.themeId(), member.getId());
[반영 완료] 

감사합니다! 같은 예약의 존재 여부를 검증하고 도메인에서 status에 따라 분기하여 throw하는 것으로 수정하였습니다.

2024-05-23 14:30 UTC, pci2676 commented on src/test/java/roomescape/reservation/service/AdminReservationServiceTest.java
>  @Transactional
아이고 제 질문에 오타가 있네요 ㅠㅠ

원래 질문은

- Service에는 Transaction이 없고 
- ServiceTest에는 Transaction이 없을 때

였습니다 😄

2024-05-23 14:34 UTC, pci2676 commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
>테스트에서 @Transactional을 사용한 이유는 직접 트랜잭션을 관리하지 않고도 테스트 메서드마다 영향을 주지 않기 위해 사용하였습니다. 즉, 편리하게 롤백 테스트를 하기 위함입니다.

위와 같이 답변해주셔서 아래 글을 한번 참고해보시면 좋을것 같습니다.

https://javabom.tistory.com/103

2024-05-24 04:21 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        confirmReservationIfWaitingExists(id);
[반영 완료]

네 맞습니다 😂 트랜잭션 로그를 찍어 확인해보니 서비스에 트랜잭션이 없기 때문에 영속성 컨텍스트가 있어서 변경 감지가 가능하더라도 쿼리가 바로 날라가지는 않네요.
그동안 정상적으로 더티 체킹이 완료된 이유는 해당 메서드에 있는 `deleteById`라는 전혀 다른 부분에서 트랜잭션이 커밋되기 때문이었습니다. 따라서 더티 체킹의 여부가 다른 메서드의 존재 여부에 의존하고 있었었던 것을 새로 알게 되었습니다.

그래서 조언대로 트랜잭션을 서비스 레이어에 추가하여 항상 더티체킹이 정상적으로 수행되도록 하였습니다.  😉

2024-05-24 05:52 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
[반영 완료] 

서비스 테스트에 `@Transactional`을 붙였을 때 서비스 프로덕션 코드와 완전히 같은 환경에서 테스트 할 수 없다는 것이 문제였군요 😃 저는 프로덕션에 `@Transactional`을 붙였으니 JPA 관련한 예외가 터질 일이 어짜피 없고 롤백 테스트가 편리하니 그냥 붙여도 되지 않을까, 하고 생각했는데 테스트 코드의 본질에 대해 집중해보니 그런 사이드 이펙트가 있었군요. 

서비스 테스트에서 @Transactional를 사용하지 않도록 수정하였습니다. 
좋은 인사이트를 제공해주셔서 감사합니다.

2024-05-24 05:52 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/AdminReservationServiceTest.java
>  @Transactional
[답변]

넵 그렇게 이해하였습니다 😁
피드백해주신 대로 수정하였습니다.

2024-05-24 07:49 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +            ) + 1;
[반영 완료] 

네 상수로 분리하였습니다. 😀 그리고 내 예약에서 RANK를 조회하는 로직의 가독성을 위해 코드를 수정하였습니다.

2024-05-24 07:54 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        Reservation reservation = reservationRepository.findById(id).get();
[반영 완료] 

넵 이전 메서드에서 대기가 존재하는 지 이미 검증하였기 때문에 괜찮을 것이라 생각했네요. 😅 그리고 쿼리가 두 번 나가는 것도 불편할 수 있겠어요.
해당 메서드에서 검증 메서드를 호출하고 반환된 예약 객체를 사용하도록 수정하였습니다.

2024-05-24 08:53 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        return responses;
[반영 완료] 

쿼리를 줄이는 가장 간단한 방법 중 하나로 모든 예약 데이터를 조회하고 서비스 레이어에서 스트림으로 예약 대기자 수를 계산하는 것으로 수정하였습니다 😅 앞선 대기자 수를 컬럼에 저장할 수도 있지만, 변경이 잦은 부분이라 덜 효율적일 것 같아서 해당 방법을 선택하였습니다.

2024-05-25 04:47 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
[질문] 

추가로 궁금한 점이 있어 질문 남깁니다. 
스프링에서 제공하는 트랜잭션 전파 중 REQUIRED_NEW와 NEVER를 사용하면 테스트에서 `@Transactional`을 사용해 롤백을 할 수 있음과 동시에 테스트의 트랜잭션이 서비스 클래스에 전파되지 않을수도 있지 않을까요?

물론 서비스 메서드마다 모두 어노테이션을 붙여주어야 한다는 불편함은 존재하지만, 굳이 트랜잭션을 사용해 롤백 테스트를 해야한다면 트랜잭션 전파를 사용해 테스트의 트랜잭션이 서비스까지 영향을 미치지 않도록 하는 방법도 있을 것 같습니다. 

혹시 이 관점에 대해서 비밥은 어떻게 생각하시는 지 궁금합니다.🧐

2024-05-25 05:06 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
+) 자문자답을 덧붙이자면 테스트 메서드의 롤백이 제대로 안될 뿐더러 테스트에서 여러 번 서비스 메서드를 호출하였을 때 커밋되는 시점의 차이로 불안정한 테스트가 되는 것 같네요 😶😶 이 질문은 해결했습니다!

2024-05-25 05:56 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    }
[반영 완료] 

동시성 테스트를 해보니 정확히 같은 시간에 다른 스레드에서 예약 요청을 보내면 동시 예약이 되는 상황이 있었네요 🥲 
가장 간단한 방법 중 하나인 `synchronized` 를 사용해서 동시성 테스트가 성공하도록 우선 만들어보았습니다. 하나의 스레드에서만 메서드를  실행할 수 있어 성능적인 이슈는 있겠지만, 가장 확실한 방법이라고 생각했습니다. 

그 이외로 트랜잭션 격리 수준, 데이터베이스에서 락을 거는 방법 등을 떠올리고 시도해보았는데 동시성 테스트가 실패하여 조금 더 학습 후 적용이 필요해보였습니다. 깊게 학습한 후 다시 올바르게 적용해보는 것을 시도해보겠습니다.

2024-05-26 02:41 UTC, pci2676 approved these changes
피드백 반영도 깔끔하게 해주셨고

이번 단계에서 고려해볼만한 사항은 모두 이야기해본 것 같습니다.

그동안 고생 많으셨습니다. 머지하겠습니다. 🚀

2024-05-26 02:41 UTC, merged