[3 - 4단계 방탈출 예약 대기] 다온(조형익) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #106
Opened 2024-05-22 08:46 UTC by ikjo39

안녕하세요 호돌, 다온입니다. 🙌 
3-4단계 리뷰도 잘 부탁드립니다.

## 정책

- 예약 삭제시 1번째 예약 대기가 자동으로 예약됩니다.
- 예약 대기 조회시 예약 번호는 대기 순위를 보여줍니다.

질문사항은 코멘트로 남겨두겠습니다 😄

2024-05-22 10:16 UTC, ikjo39 reviewed
고민한 부분과 질문을 댓글로 남겨보았습니다. ⭐

2024-05-22 16:17 UTC, kimhodol requested changes
안녕하세요 다온 :)

3, 4단계도 잘 구현해주셨네요.

코멘트 확인 부탁드립니다!

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +    }
의견) hasSameTime이 어떨까요?

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/domain/TimeSlot.java
> +    }
의견) 동일성 검증을 하기 위해서라면 equals를 override해도 될 것 같아요.

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/dto/request/AdminReservationRequest.java
> +        return new Reservation(null, member, date, time, theme, ReservationStatus.BOOKING);
질문) 어드민이 생성하는 Reservation의 상태는 무조건 BOOKING인가요?

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/dto/response/ReservationMineResponse.java
> +                reservationRank.getReservation().getTime().getStartAt(),
의견) 디미터의 법칙을 지켜보면 좋을 것 같아요.

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +        if (!reservation.getStatus().isPending()) {
의견) 여기도 디미터의 법칙을 지켜볼까요?

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +            });
질문) 없는 경우에는 어떻게 처리되는건가요?

2024-05-22 16:17 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
>          }
의견) 서비스가 점점 커지는 것 같은데, 역할을 나눠보는 것은 어떨까요? 우선 Validating 하는 컴포넌트를 만들어보는 것으로 시작해봐도 좋을 것 같아요!

2024-05-22 16:17 UTC, kimhodol commented on src/test/resources/test-data.sql
정답이 없는 문제같긴한데요, 개인 취향(?)을 물어봐주신거라면 엄청나게 많은 더미 데이터를 넣지 않는 이상 테스트에 사용되는 객체들을 넣을 때는 Fixture를 활용하는 편입니다.

2024-05-24 05:56 UTC, ikjo39 reviewed
리뷰해주신 부분 반영해보았습니다 !!

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
[반영완료]
호돌이 말한 메서드명이 좀 더 명확해보여 해당 메서드명으로 수정하였습니다.

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/domain/TimeSlot.java
> +    }
id로서 entity를 구분할 수 있겠네요 ㅎ

[반영완료]
모든 Entity에 대해 id에 대한 equals()와 hashcode()를 오버라이드하였습니다.

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/dto/request/AdminReservationRequest.java
> +        return new Reservation(null, member, date, time, theme, ReservationStatus.BOOKING);
어드민이 예약하는 상황을 신경쓰지 못하였네요 ㅎ

[반영완료]
어드민도 예약할 때 예약 존재 여부에 따라 예약 상태가 구분되게 수정하였습니다!
추가적으로 RequestDTO에서 Reservation 상태를 결정 짓는것은 어색해보여 예약 상태 판별 로직을 Service로 옮겼습니다.

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/dto/response/ReservationMineResponse.java
> +                reservationRank.getReservation().getTime().getStartAt(),
[반영완료]
Reservation 내 getter 메서드를 추가하여 디미터 법칙을 이행하였습니다!

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/service/ReservationService.java
> +        if (!reservation.getStatus().isPending()) {
[반영완료]
Reservation 내 판별 로직을 추가하여 디미터 법칙을 이행하였습니다!

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/service/ReservationService.java
> +            });
없는 경우에 어떠한 로직을 수행하고 싶지 않게 의도하였습니다!

[반영완료]
`ifPresent()`메서드로 수정하여 좀 더 명확한 의미를 보이게 수정하였습니다!

2024-05-24 05:56 UTC, ikjo39 commented on src/main/java/roomescape/service/ReservationService.java
>          }
[반영완료]
validator를 추가하여 역할을 분리하였습니다!
역할 분리하니 Service 레이어의 코드 스멜을 줄일 수 있었습니다.

2024-05-24 05:56 UTC, ikjo39 commented on src/test/resources/test-data.sql
아하 이 또한 트레이드 오프 상황이었군요!
Service 레이어의 통합테스트를 해보니 Fixture를 활용하는 것이 좀 더 테스트를 이해하는데 명확해보여 해당 방식으로 적용해보았습니다!!

2024-05-24 08:22 UTC, kimhodol requested changes
안녕하세요 다온 :)

피드백 잘 반영해주셨네요.

간단한 코멘트 몇 가지 달았습니다!

---

코드를 봤을 때는 TDD를 하고 계신다는 느낌이 잘 안드네요 🥲 비어있는 테스트들 조금 더 채워주시면 좋을 것 같아요!

2024-05-24 08:22 UTC, kimhodol commented on src/main/java/roomescape/domain/Member.java
> +        this.id = id;
질문) id값을 직접 주입할 일이 있나요?

2024-05-24 08:22 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +    public void updateStatusBooked() {
의견) book 정도의 네이밍은 어떨까요?

2024-05-24 08:22 UTC, kimhodol commented on src/main/java/roomescape/domain/ReservationRank.java
> +public class ReservationRank {
의견) record로 사용하는것은 어떨까요?

2024-05-26 06:53 UTC, ikjo39 commented on src/main/java/roomescape/domain/Member.java
> +        this.id = id;
JdbcTemplate에서 JPA로 영속계층이 전환되면서 Entity 생성자내 id가 불필요해진 것을 확인하였습니다!

[반영완료]
다른 Entity들의 생성자의 id도 모두 제거하였습니다.

2024-05-26 06:54 UTC, ikjo39 commented on src/main/java/roomescape/domain/Reservation.java
> +    public void updateStatusBooked() {
[반영완료]
update 를 명시하기 보다 book 으로 간단하게 나타내는게 더 명확해보여 반영하였습니다!

2024-05-26 06:55 UTC, ikjo39 commented on src/main/java/roomescape/domain/ReservationRank.java
> +public class ReservationRank {
[반영완료]
객체 내부에 로직 없이 getter만 수행하므로 record가 적절해보임을 꺠달았습니다!
record로 변환 후 dto로 패키지를 이동하였습니다.

2024-05-26 08:32 UTC, ikjo39 commented
안녕하세요 호돌! 다온입니다.
말씀해주신 리뷰사항 모두 적용해보았습니다.

> 코드를 봤을 때는 TDD를 하고 계신다는 느낌이 잘 안드네요 🥲

마이그레이션한 코드에 E2E 테스트로만 검증이 이루어져있었는데요.
해당 부분에 대한 보완보단 다음 미션 완성이 급급했고, 테스트의 일관성을 위해 E2E로만 검증하며 미션을 수행하여서 발생한 문제 같아요 😅 

> 비어있는 테스트들 조금 더 채워주시면 좋을 것 같아요!

테스트 코드 모두 추가해보았습니다!

2024-05-27 04:56 UTC, kimhodol approved these changes
안녕하세요 다온 :)

이번 단계는 여기서 마무리해도 될 것 같아요.

고생하셨습니다!

2024-05-27 04:56 UTC, kimhodol commented on src/test/java/roomescape/fixture/MemberFixtures.java
> +        return new Member("daon", email, password, memberRole);
의견) 모르는 사람이 봤을 때 다온의 이름이 메소드명에 들어있으면 이해하기 어려울 것 같아요. testUser 정도로 해두는게 낫지 않을까요?

2024-05-27 04:56 UTC, merged