[3 - 4단계 방탈출 예약 대기] 카키(서현준) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #118
Opened 2024-05-22 15:55 UTC by hyeon0208

오랜만에 인사드립니다 파랑! 
예약 정책을 자유롭게 정하는 것이여서 제가 정한 정책을 설명드립니다! 😄

---

> 사용자 (USER)

원래의 구조는 예약자가 예약 취소를 원하더라도 관리자가 취소를 해줘야지만 가능했는데
예약자가 직접 취소를 할 수 있는 편이 좀 더 자연스러운 흐름이라 생각해
회원의 예약 관리 페이지에서 예약 취소가 가능하도록 예약 취소버튼을 추가했습니다

- 예약 당일에는 예약을 취소할 수 없다.
- 예약 당일 전날까지는 예약을 취소할 수 있다. (CANCEL로 상태 변경, 논리적 삭제)
- 예약 대기는 취소는 언제든지 가능하다. 
- 확정된 예약이 취소 될 경우 1번 째 예약 대기자의 예약이 확정된다. (자동 승인)

<br>

> 관리자 (ADMIN)

- 회원의 예약을 상태별로 확인할 수 있다. (status를 파라미터로 넘겨 조회가능하도록, default : 예약 성공 상태)
- 사용자의 예약을 제약없이 삭제할 수 있다. (물리적 삭제)
- 예약 대기 상태의 목록을 조회할 수 있다. (현재 날짜 이후의 예약 대기 목록만 조회)
- 예약 대기를 거절할 수 있다.

---
### 회원 데이터

||일반 회원|어드민|
|---|---|---|
|아이디|kaki@email.com|blue@email.com|
|비밀번호|1234|1234|

---
### 📌 변경 사항
> 조회 쿼리에 `@Transactional(readOnly = true)` 옵션 추가

`readOnly = true`로 설정하면 데이터베이스가 해당 트랜잭션을 읽기 전용으로 인식해 
데이터베이스는 읽기 전용 트랜잭션에 대해 최적화를 수행하는 것으로 알고 있어요

추가적으로 JPA를 사용하는 상황에서는 플러시 모드가 MANUAL로 설정되어 직접 flush()를 호출하지 않는 이상
예상하지 못한 데이터 변경을 방지하고,
영속성 컨텍스트는 변경 감지를 위한 스냅샷을 보관하지 않음으로 메모리를 절약해 성능상 이점을 챙길 수 있다고 생각했어요
또한 읽기 전용임을 명시해 3자가 해당 메서드에서 데이터를 변경하지 않도록 유도할 수 있다는 점을 생각해
해당 옵션을 추가하게 되었습니다!

<br>

> List<>형태로 반환되는 DTO를 객체로 감싸 반환

현재는 응답이 List로 나갈 때 Json 배열로 데이터가 보내지는데
API break change에 대해 듣게 되어
List 응답을 DTO로 감싸 Json 객체로 데이터를 응답해 클라이언트 쪽에서 확장성 용이하도록 수정해보았습니다!

<br>

> DB의 프로시저를 사용하는 것 보다 도메인의 로직으로 해결하도록

크루와 얘기를 하다 DB의 프로시저 사용을 경계해야한다.라는 주제를 알게 되었어요 !
경계해야하는 이유로 현재 저에게 와 닿은 부분은 아래와 같았어요

- 객체지향의 문법을 이용하여 로직을 작성할 경우 읽기 쉬운 코드를 만들어 낼 수 있지만
프로시저의 문법은 구조적인 문법이며 순차적인 문법이기에 로직이 길어진다면 해당 로직을 이해하기 힘들다

- 데이터베이스는 ScaleOut이 매우 힘들다. 만약 내가 만든 프로시저가 많은 성능을 요구한다면 어떻게 ScaleOut을 할 것인가? 보통은 ScaleUp 하는 방법으로 갈 수 밖에 없다. 
기껏해야 나눌 수 있는게 용도별로 DB를 나누는 것이다. 이는 또다른 백업과 관리의 노력이 드는 것과 같다. 
여러대의 WAS를 늘려가는 것과 용도별로 다른 DB를 늘려가는 것은 전혀 차원이 다른 문제이다.

---
### ❓ 궁금한 점

> 테이블

이번 미션에 예약 대기 테이블에 대한 예시 코드가 있었지만
개인적으로는 예약 테이블에 데이터가 추가된 시간 createdAt() 컬럼을 추가해

<br>

> 현재 도메인이 적절한 로직을 갖는지?

2024-05-23 12:22 UTC, summerlunaa requested changes
카키 안녕하세요~

이번에도 잘 구현해주셨네요! 이전 리뷰와 DM으로 말씀드린 부분까지 수정된 것도 확인했습니다. 리뷰 확인해주시고 질문 편하게 주세요~

2024-05-23 12:22 UTC, summerlunaa commented on src/main/java/roomescape/reservation/controller/ReservationApiController.java
> +    public ResponseEntity<MultipleResponses<ReservationResponse>> findAll(@RequestParam(defaultValue = "SUCCESS") String status) {
```suggestion
    public ResponseEntity<MultipleResponses<ReservationResponse>> findAll(@RequestParam(defaultValue = "SUCCESS") Status status) {
```

Enum으로 바로 받을 수도 있어요.

2024-05-23 12:22 UTC, summerlunaa commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    @Transactional(readOnly = true)
Transactional에 readOnly까지 공부하고 적용해보셨군요 👍

2024-05-23 12:22 UTC, summerlunaa commented on src/main/java/roomescape/reservation/domain/Waitings.java
> +public class Waitings {
> 정규화를 적용하기 위해 만든 것도 아닌 Waiting 테이블을 만들더라도 reservation 테이블과 중복된 컬럼을 갖게 될거라 판단되어
오히려 테이블 생성에 대한 리소스를 낭비한다고 생각했어요
그래서 테이블을 추가하기 보다는 컬럼 하나 추가해서 하나의 테이블로 관리하는 편이 더 수월하다 생각이 들었습니다.

추가적인 테이블 생성에 대해서 많이 고민해주셨네요 👍 타당하다 생각합니다. 지금 정도의 요구사항이라면 굳이 waiting 테이블을 분리하지 않아도 충분히 구현 가능해보여요(이미 구현해주셨듯이). 나중에 요구사항이 추가되면서 예약 시 받는 정보와 대기 시 받는 정보들이 크게 달라진다면 테이블 분리도 고민해볼 수 있을 것 같습니다. 테이블을 합치는 것보단 분리하는 게 더 쉬우니까욥ㅎㅎ

2024-05-23 12:52 UTC, hyeon0208 commented on src/main/java/roomescape/common/dto/MultipleResponses.java
> +}
EOF 방지 설정을 적용했을 때 인텔리제이 자체에 적용되어 새 프로젝트 만들 때도 반영될 줄 알았는데
새 프로젝트마다 설정을 해줬어여 했네요 .. !

EOF 방지를 위한 설정을 적용하고 개행이 안된 파일 끝에 개행 추가하였습니다!
<img width="422" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/99153215/80f9d6fb-cb23-4051-a905-3601c771aa79">

2024-05-23 13:36 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/controller/ReservationApiController.java
> +        MultipleResponses<ReservationResponse> reservationResponses = reservationService.findAllByStatus(status);
말씀대로 MultipleResponses는 온전히 컨트롤러들에서만 공통으로 반환하는 DTO라
처음부터 컨트롤러 쪽에서 변환해주는 방법으로 생각 했다면 서비스와 테스트의 코드 변경이 없없을 것 같네요 👍🏻 
무의식적으로 적용하기 보단 이러한 부분도 고민해보고 적용해보는 연습이 필요할 것 같아요 😃
해당 부분 변경했습니다!

2024-05-23 14:12 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/controller/ReservationApiController.java
> +    @PostMapping("/reservations/waiting")
다시 생각해보니 `/reservations/{id}`로 요청을 했을 때 실행되는 `cancelById()` 는 동일한 요청을 여러번 하더라도
결과는 동일해 멱등성을 보장하는데 멱등성을 보장하지 않는다는 특징을 가진 `POST`는 적절하지 않은 것 같아요 !
하지만 리소스를 생성 또는 요청 값으로 대체하는 특징을 가진 `PUT`보단
예약의 일부인 상태만 변경하기 때문에 `PATCH`가 더 적절하지 않을까 생각하고 변경했는데 이점에 대해 어떻게 생각하시는지 궁금합니다! 🙇🏼‍♂️

2024-05-23 14:14 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/BaseDateTime.java
> +public abstract class BaseDateTime {
모든 테이블에 공통적으로 적용될 수 있는 값이라 생각해 `@MappedSuperclass`를 선언한 추상 클래스로 분리했는데
말씀하신대로 변경일 등의 필드가 추가되었을 때도 공통으로 사용할 수 있는 네이밍인 `AuditedEntity`이 적절한 것 같다고
생각들어 변경했습니다 ! 👍🏻

2024-05-23 14:27 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/Status.java
>  public enum Status {
PaymentStatus 같이 Status를 갖는 도메인이 추가된다면 문제가 발생할 수 있을 것 같네요 !
예약 상태임을 명시해주도록 수정해보았습니다 👍🏻
고려할 수 있는 부분을 짚아주셔서 감사합니다 😊

2024-05-23 15:15 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/controller/ReservationApiController.java
> +    public ResponseEntity<MultipleResponses<ReservationResponse>> findAll(@RequestParam(defaultValue = "SUCCESS") String status) {
오 .. Enum 타입으로 매핑도 되군요 👍🏻
해당 부분 반영했습니다 !

2024-05-24 11:35 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/Waitings.java
> +    public int findMemberRank(Reservation reservation, Long memberId) {
너무 많은 것을 애플리케이션에 맡긴 것은 아닐까 걱정은 됐었는데
파랑의 답변을 보고 상황에 따라 누구에게 로직을 주는 게 맞을 지 고민해보았고 어느 정도 정리가 된 것 같아요 !
지금도 31개의 예약 데이터가 있는 상황에서 한 화면에 예약 내역이 한 눈에 안들어온다는 점이 불편해
페이징을 고려할 수 있을텐데 페이징이 적용된다면 쿼리로 해결하게 될 것 같기도 하구요 🤔

각 상황들을 고려해 어떻게 적용해야할지는 너무 많은 상황들이 있어 정리하기는 힘들었지만
트레이드 오프의 영역이라 생각해, 지금 서비스 규모에 적절하게 설계하는 것이 적절하다고 판단했어요 😃

---

예약을 가져 올때 날짜, 시간, 생성일을 기준으로 정렬하는 부분은
서비스 로직에서 복잡하게 처리하는 것보다 쿼리로 작성하는 것이 오히려 가독성 측면에서 좋다고 생각이 들었어요 🤔
하지만 waitings에서 filter를 사용하지 않고 조건에 맞는 데이터를 가져오는 쿼리를 사용하게 된다면

filter 로직은 빠지고 memberId가 몇 번째 순서에 있는지만 구하면 될 것 같긴한데
예약 대기 상태인 동일한 테마마다 조회 쿼리를 보내고 테마별로 회원의 대기 번호를 구해야했어요.
하지만 조회 쿼리가 성능에 가장 큰 영향을 미친다고 알고 있어 
이 부분은 애플리케이션 단에서 처리하는게 성능상 유리하지 않을까 생각했는데
파랑은 어떻게 생각하시나요 ??

2024-05-24 11:52 UTC, hyeon0208 commented
파랑의 답변으로 많은 점을 배울 수 있었습니다 👍🏻 🐳
리뷰에 대한 반영사항은 댓글로 남기고
이 외에 오류로 인한 변경 사항을 정리해 다시 리뷰 요청드립니다 ! 🙇🏼‍♂️

---
### 📌 변경 사항

> 렌더링 문제

List<>가 아닌 이를 감싼 DTO로 응답하도록 수정 한뒤
관리자가 예약 조회 할 시 화면에 데이터가 정상적으로 렌더링 되지 않는 문제가 있어
`reservation-with-member.js` 의 일부 코드를 수정했습니다.

<br>

> 인기테마 조회 로직 오류

인기테마 관련 테스트가 실행할때마다 결과가 바뀌는 문제가 있었어요 😅
알아보니 `PopularThemes` 에서 Map의 `getOrDefault`로 예약된 테마 수를 카운팅 할 때 `Theme` 객체의 동일성을 비교하는데
주소값이 달라 동일한 값을 가진 테마임에도 개별적으로 카운팅되는 문제가 있었어요
이 문제를 해결하기 위해 `equals()`와 `hashCode()`를 오버라이딩 해야하나 생각했는데
ID값은 다르기 때문에 ID를 빼고 오버라이딩 해야했어요 

하지만 LMS의 피드백 문서를 보니 다른 트랜잭션에서 동일한 엔티티를 조회하는 경우 equals()와 hashCode() 가 식별자(id) 기준으로 오버라이딩 되어 있지 않으면 동일한 객체임에도 다르다고 인식하는 문제가 있더라구요

그래서 id를 제외한 오버라이딩은 제쳐두고
테마의 이름을 key값으로 해 카운팅한 뒤 stream으로 List<Theme>를 반환하도록 수정해보았습니다!

<br>

> 중복된 예약 시간 추가 검증

예약 시간을 추가하는 부분에 대해서는 중복을 확인하는 부분이 빠져
해당 검증을 추가해 이미 있는 예약 시간일 경우 추가하지 못하도록 변경했습니다!

2024-05-25 16:18 UTC, summerlunaa requested changes
카키 안녕하세요~

추가로 발견한 오류와 검증 누락도 추가해주셨네요 👍 쿼리를 좀 더 활용하는 방향으로 수정된 부분도 확인했습니다. 추가 코멘트 남겨드렸으니 읽어해보시고 코멘트로 이어서 얘기 나눠보면 좋을 것 같아요!

2024-05-25 16:18 UTC, summerlunaa commented on src/main/java/roomescape/reservation/domain/Waitings.java
> +    public int findMemberRank(Reservation reservation, Long memberId) {
애플리케이션 단에서 처리하기 위해서는 `findAllByReservationStatusFromDate`를 먼저 수행하지 마시고 아래의 순서대로 하면 더 효율적일 것 같아요.

1. `findAllByMemberIdFromDateOrderByDateAscTimeAscCreatedAtAsc`를 통해 데이터를 가져온다.
2. 이 중에 대기 상태인 예약만 뽑아서 테마와 예약일시가 같은 대기 예약들을 가져온다.
3. rank를 구한다.

여기서 한 번에 반환하는 본인 예약의 개수를 제한하고(페이지네이션), 하나의 (테마, 일시)에 대기할 수 있는 예약 인원에 제한을 두면 데이터가 많아진다 해도 어플리케이션 단에서 처리 가능할 수 있겠네요.

혹은 rank 컬럼이나 별도 테이블을 추가하는 등의 다른 방식도 생각해보셨는지 궁금합니다~

2024-05-26 04:50 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private ReservationStatus reservationStatus;
클래스명에서 이미 예약이라는 뜻이 명시되어 있어서 필드는 status로 두는게 자연스럽고 변수 길이 측면에서도 좋은 것 같네요 👍🏻
같은 맥락으로 reservationTime의 변수명도 time으로 수정해보았습니다

2024-05-26 10:16 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/Waitings.java
> +    public int findMemberRank(Reservation reservation, Long memberId) {
우선 DB에 2번의 접근으로 가져온 리스트를 통해 대기 순서를 애플리케이션으로 처리하는 것과
DB에 여러번 접근해 DB에서 대기 순서를 구하는 것 중
어떤 방식이 더 빠른 응답이 가능할지가 궁금해 1000개의 예약 데이터로 요청 수를 조절 해가며
예약 대기 순서를 애플리케이션에서 구하는 것과 DB에서 `count()` 쿼리로 구하는 것으로 나눠 테스트해봤습니다!

컨트롤러에서 요청 수(`RestAsserd`를 반복문으로 실행)를 100이라 가정했을 때는 차이가 없었고
요청 수를 1000이라 가정 했을 땐 애플리케이션에서 처리하는 것이 2초 가량 더 빨랐어요
하지만 여기서 요청수를 조금 더 늘리는 순간 서버의 메모리가 터지더라구요 🤯

실제로는 여러 상황과 변수가 있겠지만 요청 수만 가정해보자는 식으로 테스트했고
부하 테스트가 아닌 요청 수를 반복문으로 테스트해 확실한 결과인지는 모르겠지만…
이 테스트 결과로 각 서버의 자원을 적절하게 배분해 사용해야한다는 것을 느낄 수 있었어요

복잡한 쿼리문으로 많은 프로시져가 사용되어 DB에 부하를 줄 수 있다면
차라리 수평 확장이 쉬운 애플리케이션 쪽에서 해당 로직을 처리하는 것이 적절하다고 생각이 들었고
지금 처럼 쿼리문이 그렇게 길지도 않고 여러 프로시져를 사용하는 것도 아닌 상황에서는 
서비스에서 해당 로직의 흐름을 클래스를 들어가보며 이해하는 것 보다
쿼리문으로 작성하는 게 오히려 가독성이 좋을 수 있다고 생각이 들어
파랑이 말씀해주신 순서에서 rank를 구하는 것을 쿼리로 해결하도록 수정했습니다!

혹시 제가 잘못 생각하고 있는 부분이 있다면 짚어 주시면 감사하겠습니다 ! 🙇🏼‍♂️

> 한 번에 반환하는 본인 예약의 개수를 제한하고(페이지네이션), 하나의 (테마, 일시)에 대기할 수 있는 예약 인원에 제한을 두면 데이터가 많아진다 해도 어플리케이션 단에서 처리 가능할 수 있겠네요.

한 번에 반환되는 예약 개수에 제한이 없어 무수히 많은 예약 데이터가 나온다면  
이 데이터에 대한 모든 필드를 JVM에 올리면서 DB로 부터 데이터를 받아오는 네트워크 소요 시간이 너무 길어 지는 문제가 있었어요
그래서 애플리케이션에서 로직을 처리할 때 이러한 점도 고려해야한다는 것을 테스트를 통해 몸소 느낄 수 있었어요 👍🏻

이와 같은 맥락으로 첫 번째 대기자를 구하는 로직도 `List<>` 형태로 받아와 `Watings` 도메인이 구하지 않고
데이터베이스에서 처리된 결과를 가져오도록 수정하는 편이 네트워크 부하를 줄일 수 있다고 생각해 수정 후
`Waitings` 도메인은 필요없어지게 되어 제거하게 됐어요

위 답변 처럼 회원을 대기 순번을 `List<>`형태의 데이터를 가져와 구하는 것이 아닌
데이터베이스에서 처리된 결과를 가져오게 됨으로써
네트워크 통신 비용 증가에 대한 부분이 해결되었다고 생각하는데 
이점에 대해서도 테스트를 통해 잘 이해한 것인지 알고 싶어 파랑은 어떻게 생각하시는 지 듣고 싶습니다! 😄

> rank 컬럼이나 별도 테이블을 추가하는 등의 다른 방식도 생각해보셨는지 궁금합니다~

rank 컬럼도 첫 구현 때 생각은 했었는데, rank 컬럼을 추가하게 되면 예약 대기 특성상
예약 확정이 취소 되면 그 예약 대기자들의 대기 번호가 1 씩 줄어 들텐데 이 때 update 쿼리가 빈번하게 발생할 것 같아 적용하지 않는 쪽으로 했고

만약 예약 대기에 대한 요구사항이 점점 많아진다면 Reservation에 관련된 계층들이 점점 뚱뚱해질텐데
이 때는 분리를 고민 해볼 것 같아요 

특히 개인적인 생각으로는 예약 취소라는 데이터는 중요하게 관리될 수 있다고 생각하는데
예약 대기 취소 데이터는 해당 예약 날짜가 지나면 제거 되어도 상관없을 데이터라고 생각해
만약 이러한 요구 사항이 생긴다면 예약 대기 테이블을 추가해 관리하는 것도 좋을 것 같다는 생각이 들어요 !

지금 상황에서는 예약 대기라는 것이 예약의 상태로만 표현된다고 느껴져
하나의 테이블로 관리하는 쪽으로 그대로 가보게 되었습니다 ! 😄

특히 DB에 대해서 아직 공부가 많이 필요하다고 생각해 적절히 판단한지 모르겠네요 ..
이유가 타당하다고 볼 수 있을까요 ?? 🤔

2024-05-26 13:38 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/PopularThemes.java
> +                .toList();
[예약 대기 번호 로직 코멘트](https://github.com/woowacourse/spring-roomescape-waiting/pull/118#discussion_r1614759643)

위 코멘트에서 정리한 생각처럼
인기 테마를 구하는 것도 애플리케이션에서 처리하는 것보다 
DB에서 처리된 결과를 한번에 받아오는 것이 성능이 더 좋다고 생각이 들었어요

```
select t
from Theme t
join Reservation r
on t.id = r.theme.id
where r.date between :startDate and :endDate
group by t.id
order by count(r) desc
limit :limitCount
```
이 쿼리문은 나름 여러 개의 프로시져들이 사용돼서 애플리케이션 로직이 더 성능이 좋지 않을까 생각했는데
실제로 DB에서 처리된 결과를 받아오는 것이 처리 속도가 더 빠른걸 보니
프로시져 사용을 피해야하는 상황이 되려면 쿼리의 로직이 훨씬 더 복잡해졌을 때가 될 것 같네요 🤔

또한 `findReservationsOfLastWeek()` 로 지난 주에 대한 예약을 전부 들고와 
인기 테마를 애플리케이션에서 처리했을 때에는 예약이 데이터가 그렇게 많진 않을테니 괜찮을 거라 생각했지만
말씀해주신 것 처럼 월간, 연간 인기 테마라는 요구사항이 생긴다면 무수히 많은 예약 데이터를 불러와야 해
DB 네트워크 통신 시간에 무리가 갈 것 같다고 생각해
처음 처럼 쿼리문으로 인기 테마를 조회해 오도록 수정했어요 ! 😄

또한 파라미터를 추가로 받고 날짜 기간을 관리하는 `Period` Enum 클래스를 추가해  
일간, 주간, 월간, 연간 인기 테마를 조회할 수 있도록 적용해보았습니다! 👍🏻

2024-05-26 14:36 UTC, hyeon0208 commented
안녕하세요 파랑 🐳
로직을 애플리케이션에 두느냐 DB에서 처리하느냐에 대해 많은 생각을 해볼 수 있었어요 !
지금 프로젝트에서 어느 정도의 규모까지 예상해 어떻게 로직을 나눌 지가 참 애매해더라구요…
(너무 지금의 규모에서 관련 없는 “프로시져 사용을 피해야하는 이유”라는 주제에 대해 매몰된게 아닌가 싶기도 하네요 😅)

그래도 언젠가는 이러한 점을 고민해볼 시기가 올테니
확실히 정리하고 싶어져 테스트를 통해 비교해보며 생각을 정리해볼 수 있었던 것 같아요 !
하지만 잘못된 생각을 정리했을 수도 있을 것 같아 몇 가지 궁금한점을 코멘트에 추가로 달았습니다! 🙇🏼‍♂️

위로 스크롤해 코멘트 찾기 불편하실까봐 코멘트 바로가기 링크 첨부합니다 😃

[예약 상태 필드명 변경 코멘트](https://github.com/woowacourse/spring-roomescape-waiting/pull/118#discussion_r1615022286)
[예약 대기 번호 로직 코멘트](https://github.com/woowacourse/spring-roomescape-waiting/pull/118#discussion_r1615150352)
[인기 테마 로직 코멘트](https://github.com/woowacourse/spring-roomescape-waiting/pull/118#discussion_r1615205304)

추가로 Test Fixture를 좀 더 활용해 테스트 가독성이 좋을 수 있도록 적용해보았습니다!

2024-05-27 10:38 UTC, summerlunaa commented on src/main/java/roomescape/reservation/domain/Waitings.java
> +    public int findMemberRank(Reservation reservation, Long memberId) {
> DB에 대한 접근이 반복문으로 n 번씩 요청되는 점이 좀 우려되긴하네요 ...

저도 같은 생각입니다. 한 페이지에 보여주는 예약이 50개만 되어도 select 문이 50번이 날라갈텐데 굉장히 비효율적인 것 같아요. 처음 말씀드린대로 한 번에 조회할 수 있는 예약 개수에 제한을 걸고, 최대 대기 개수도 제한을 걸어서 예약을 모두 가져와 어플리케이션에서 처리하는 게 아무래도 속도도 빠르고 db 조회도 한 번만 하면 되어서 더 나아 보이네요.

사실 가장 간단하게 쿼리 한 방으로 처리하기 위해서는 self join을 이용할 수 있어요. 계속 DB 쿼리와 어플리케이션 로직 사이에서 적절한 선을 찾고 계신 것 같아서 말씀 안 드렸는데 self join을 사용하면 간단하게 해결될 수도 있습니다. 한번 고민해보세요.

> 지금 상황에서는 예약 대기라는 것이 예약의 상태로만 표현된다고 느껴져 하나의 테이블로 관리하는 쪽으로 그대로 가보게 되었습니다 ! 

네 좋습니다 👍 진짜 분리가 필요하다 느낄 때 분리하면 될 것 같아요.

2024-05-27 10:48 UTC, summerlunaa approved these changes
카키 안녕하세요~

이번 미션에서는 DB 쿼리 사용과 어플리케이션 레이어에서의 로직 처리 사이에 고민이 많았던 것 같네요ㅎㅎ 이것저것 시도해보면서 스스로 많이 배웠을 것 같습니다. 이제 충분히 리팩토링된 것 같아서 방탈출 예약 대기 미션은 여기서 머지하겠습니다. 레벨2도 이제 막바지에 왔네요 끝까지 파이팅입니다~~

2024-05-27 10:48 UTC, merged