[1, 2단계 방탈출 예약 대기] 폴라(장유진) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #12
Opened 2024-05-15 06:28 UTC by jinchiim

안녕하세요 아서

2024-05-16 11:02 UTC, Hyunta requested changes
안녕하세요 폴라,
1,2단계 미션 잘 진행해주셨네요!
관련해서 몇가지 커멘트 남겨드렸는데 확인 부탁드립니다.
궁금하거나 이해가 안가는 부분이 있으면 DM 주시거나 커멘트로 알려주세요!

2024-05-17 02:07 UTC, jinchiim commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +public interface MemberRepository extends Repository<Member, Long> {
사용하지 않는 내부 구현 메서드들이 많아서, `Repository` 를 선택하게 되었습니다!
실제로 직접 만든 메서드와 내부 구현 메서드가 헷갈려 잘못 선택해 삽질한 경험이 있어, 사용하지 않는 메서드는 노출되지 않는게
좋겠다고 생각했습니다. 🥲

 `Repository` docs 에도

`Domain repositories extending this interface can selectively expose CRUD methods by simply declaring methods of the same signature as those declared in CrudRepository.`

라고 나와있어, 모든 `CRUD` 메서드가 필요한 것이 아니라면 `Repository`를 상속 받아도 문제 없다고 여겼습니다!

2024-05-17 04:23 UTC, jinchiim commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +    Optional<Member> findMemberByEmail_EmailAndPassword_Password(String email, String password);
단순히 컬럼 값을 넘겨야 한다고 생각했는데, 
`PR`을 날리고 크루와 얘기하다 보니.. 객체를 넘겨도 됐었다는 사실을 뒤늦게 깨달았습니다 😞

이번 `PR`에서 수정해보겠습니다!
특히 로그인 부분에서는 도메인에 있던 검증 메서드에 의해 검증도 될 수 있어 좋네요! 🤔

2024-05-17 04:26 UTC, jinchiim commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        System.out.println("여기서 났나요?");
앗... 🤨

2024-05-17 05:05 UTC, jinchiim commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private Member member;
기존 프로젝트 코드를 작성했을때는 늘 `@JoinCoulmn` 을 붙여주었는데요.
이번 미션을 진행하면서 찾아보다보니 생략이 가능하다는 것을 알게되어 떼어보았습니다!

해당 애노테이션을 생략했을때는 제가 매핑해준 `Entity` 이름을 기반으로,
`000_id` 라는 이름으로 자동으로 연관관계 `column`을 만들어주는 것으로 알고 있습니다!

2024-05-17 05:53 UTC, jinchiim commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
객체를 생성할때 `Reflection API` 를 사용해서 생성하기 때문으로 알고 있습니다.
해당 `API`가 파라미터가 있는 생성자를 인식하는 방식이 아니라서, 아무것도 없는 생성자를 이용하는 것도 하나의 이유가 되겠지만,

또 `LAZY` 라는 지연로딩 방식을 선택하면 기존 엔티티를 상속하는 `Proxy` 라는 가짜 객체도
생성자를 필요로 하기 때문도 하나의 이유로 알고 있습니다.

이 `@Entity` 어노테이션에 대해 공식 문서에서도 이와 같이 언급하고 있더라구요!
![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/105053478/8f1ba2b8-64dd-4480-801f-237bf42d636c)


그러고 보니 반드시 `public` 해줄 이유는 없었네요 🤔
`protect`로 바꿔보겠습니다.

2024-05-17 06:13 UTC, jinchiim commented on src/main/java/roomescape/reservation/domain/Reservation.java
>          return new Reservation(date, timeId, themeId, memberId);
앗.. 이전에는 `DB`에서 결과와 매핑해주는 생성자와 처음 생성을 할때 사용하는 생성자에  따른
`validation`이 따로 필요했기 때문에 명시적으로 `save~`라는 표현을 썼던 것인데요.

지금은 결과를 매핑해주는 생성자를 제가 만들어줄 필요가 없었네요 🤔 == 이전 미션의 잔해 입니다.
삭제하겠습니다! ☺️

2024-05-17 08:04 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Member.java
> +    private MemberRole role;
`ORIGINAL` 과 `STRING` 두가지가 있는 것으로 아는데요!

`ORIGINAL`의 경우는 순서 값을 저장하기 때문에, 바뀔 수 있는 순서에 너무 의존적이라고 생각했습니다.
`MemberRole`은 보통 기획적인 정책에 의해 이름이 결정되어, 바뀔 여지가 없다고 생각해 ` EnumType.STRING ` 으로 지정해주었습니다!

2024-05-17 08:12 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Password.java
>      }
말씀하신 질문이 두가지로 해석이 되어서 두가지 모두 답변을 드리자면

## 왜 null을 받는것이 아닌, 내부에서 정해주나요?

현재 처음 `Reservation`을 생성하는 경우와 `Password` 그 자체를 생성하는 경우 두가지의 
정적 팩토리 메서드가 있는데요

메서드 이름을 다르게 하더라도, 파라미터를 받도록 하는 모습부터 언제든 어떤 값으로든 생성 가능하다는 의도처럼 보였습니다.
(실제로는 validation이 필요한데도 불구하구요.)

그래서 파라미터를 받지 않도록 수정하게 되었습니다.

## 왜 기본 생성자를 안썼나요?

기본 생성자의 경우 `new` 라는 키워드를 사용해야 하고,
그럼으로써 팩토리 메서드의 존재 여부 자체를 모를수도 있겠다는 생각이 들었습니다.

그렇다면 의도 하지 않은 에러가 발생할 수 있지 않을지 고민했습니다. (생성자로 형식에 맞지 않는 비밀번호 만들기)

기본 생성자를 막아두면 적어도 메서드 이름이나 파라미터 값으로 구분이 가능할 것이라고 생각했어요. 🤔

2024-05-17 09:06 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Member.java
>                  MemberRole.MEMBER);
`dto`에서 객체를 만드려고 하다보니 이런 혼란스러운 메서드가 만들어져 버렸네요 🤔

`id`로 `Member`를 만드는 생성 전략이 생기지 않도록 삭제했습니다!

2024-05-17 09:20 UTC, jinchiim commented on src/main/java/roomescape/reservation/service/ReservationService.java
>      }
`adminReservationService`에는 넣었는데.. 구현하면서 놓친 부분인가보네요 🥹
추가했습니다!!

2024-05-17 09:25 UTC, jinchiim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        ReservationResponse.fromReservation(reservationRepository.save(saveReservation));
우선 파라미터로 받는 값이 다르기도 하지만,
권한에 따라서 할 수 있는 행동이 더 다양할 것이라고 생각했습니다!

`reservation` 보다는 `admin` 자체에 조금 더 중점을 두어 설계했던 것 같습니다 🤔

2024-05-17 09:28 UTC, jinchiim commented on src/main/java/roomescape/reservation/status/ReservationStatus.java
> +package roomescape.reservation.status;
엇 그렇네요. 
처음에는 단순히 `status`로 빼야겠다는 생각만 했던 것 같습니다.

지금 패키지도 그렇고 도메인 안에 들어가는게 어울릴 것 같네요! 수정했습니다!

2024-05-17 09:32 UTC, jinchiim commented on src/main/java/roomescape/theme/domain/Theme.java
> +    private Name name;
현재는 요구사항이 다르지 않아 같은 `Name`을 공유하도록 했습니다!

특히 지금 하고 있는 `Validation`의 경우, 이름이라면 당연히 해야하는 부분들(null)을 검증하고 있기 때문에
아직은 분리할 필요성을 느끼지 못했던 것 같습니다!

2024-05-17 09:51 UTC, jinchiim commented on src/main/java/roomescape/member/service/MemberService.java
> +                .orElseThrow(() -> new RoomEscapeException(MemberExceptionCode.ID_AND_PASSWORD_NOT_MATCH_OR_EXIST));
개인적으로 이와 같이 구현했던 이유는 요구사항 추가, 도메인 추가에 따른 `Exception` 추가가 없는 것을 추구했기 때문이었습니다.

(== Exception Handler에 영향이 가거나, 추가적인 클래스나 객체를 만드는 일이 없기를 바랬습니다..!)

`DM`으로 말씀해주신 부분 중, 

>  findMember 이후에 멤버가 조회되지 않았다면 해당 Exception을 떠올리는건 비교적 일관적으로 가져갈 수 있는 부분이라고 생각이 들어서요.

은 정말 납득이 많이 가 고민했으나, 그렇게 된다면 지금처럼 커스텀 `Exception`에 `RoomEscapeException`이 아닌,
좀 더 상세한 `Exception`을 앞으로도 던져줘야 할 것 같다는 생각이 들었습니다.
(`MemberNotFoundException`을 보다가 해당 `Exception`을 보면 컨벤션이 깨진다는 느낌을 받을 것 같았어요.)

그래서 해당하는 `Exception`을 `MEMBER_NOT_EXIST_EXCEPTION`을 던져주려고 합니다.
이에 대해 어떻게 생각하실까요?!

## 의견

그래서 전부 `MEMBER_NOT_EXIST_EXCEPTION`을 줘야할지 고민했으나,
아이디와 비밀번호로 `Login`을 하는 경우에는 해당하는 멤버가 존재하지 않는다는 에러보다는 

아이디와 비밀번호가 일치하지 않거나 존재하는 회원이 아니라는 문구를 던져주는게 더 어울린다고 생각하기도 하고,
예상하지 못할 문구는 아니라는 생각이 들어 이는 그대로
`ID_AND_PASSWORD_NOT_MATCH_OR_EXIST`를 던져주고 싶은데 아서는 어떻게 생각하실까요?! ☺️

2024-05-17 14:40 UTC, Hyunta commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +public interface MemberRepository extends Repository<Member, Long> {
<img width="888" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/75936123/1fc6fa62-89ed-42fe-aad3-95078553db94">

SpringDataJpa에서 [Repository 인터페이스](https://docs.spring.io/spring-data/jpa/reference/repositories/core-concepts.html)는 `Marker Interface`가 주된 역할이라고 나와있습니다.
그럼 [마커 인터페이스](https://johngrib.github.io/wiki/pattern/marker-interface/)는 무엇을 의미하는 걸까요? 말 그래도 마킹을 하기 위함입니다.
여기서는 `Repository` 라는 인터페이스는 레포지토리라는 마킹을 하는 인터페이스겠죠.

여기서부터는 개인적인 생각인데, 추상화 수준이 한단계 위에 있다고 여겨집니다.
Repository - CrudRepository 에서는 CRUD 기능을 Repository라는 기능을 명시해주고 있어요.
Repository - MemberRepository 에서는 Member와 관련된 Repository 라는 특정 도메인을 위한 Repository를 나타내고 있습니다.
그렇다면 CrudRepository와 MemberRepository가 같은 수준으로 묶일 수 있을까 고민해봐야할 것 같은데, 아무래도 CrudRepository가 조금 더 추상적이라고 생각이 듭니다. 그래서 저는 Repository를 직접 사용하는 것 보다는 기능 명세가 된 Repository를 사용하는게 적절하다고 보여져요.
만약 Repository를 사용하고 싶다면 그 사이에 단계를 만들어서 사용한다면 괜찮을 것 같습니다 `MyCrudRepository` 처럼요.

찾아보다가 알게된 [내용](https://docs.spring.io/spring-data/jpa/reference/repositories/definition.html)인데 여전히 Repository를 상속받아서 사용하고 싶다면 `@NoRepositoryBean` 애노테이션을 추가해주세요.
<img width="919" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/75936123/353e6381-74a2-436c-a83d-4550daf636fc">

2024-05-18 07:54 UTC, Hyunta requested changes
안녕하세요 폴라,
피드백 반영을 잘 해주셨네요.
남겨준 커멘트에는 피드백 달아놨습니다.
file change가 좀 많아서 혹시 제가 누락한 부분이 있을 수도 있을 것 같습니다.
그래서 한번더 RC 보내드리고 확인하신 후에 요청 주시면 merge 하도록 하겠습니다.
궁금하거나 이해가 안가는 부분이 있으면 DM 주거나 커멘트로 알려주세요.

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/member/service/MemberService.java
> +                .orElseThrow(() -> new RoomEscapeException(MemberExceptionCode.ID_AND_PASSWORD_NOT_MATCH_OR_EXIST));
> 그렇게 된다면 지금처럼 커스텀 Exception에 RoomEscapeException이 아닌,
좀 더 상세한 Exception을 앞으로도 던져줘야 할 것 같다는 생각이 들었습니다.

더 나은 예외 처리 방향에 대해서 같은 곳을 바라보고 있는 것 같습니다ㅎㅎ
귀찮은 작업이겠지만 예외에 대해서 처리할 때는 프로젝트 단위로 묶기 보다는 기능 단위로 묶어주는 것이 관리하기 유용할 것 입니다. 
지금처럼 예외마다 핸들링 해줘야하는 방법이 다를 수도 있기 때문이죠.

만약에 여력이 되신다면 예외처리에 대해서 고민해보시고 반영해주시고,
번거로움이 더 크다고 느껴지신다면 기존 구조를 유지하셔도 괜찮습니다.

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/member/service/MemberService.java
> +                .orElseThrow(() -> new RoomEscapeException(MemberExceptionCode.ID_AND_PASSWORD_NOT_MATCH_OR_EXIST));
저는 컨벤션을 중요한 장치라고 생각해요.
findByXXX는 일반적으로 `Optional<Object>` 를 반환할텐데 컨벤션으로 ObjectNotFoundException을 반환하도록 구현되어있다면 새로운 Domain이 추가됐을 때도 추가하기가 쉬우니까요.
폴라가 말해준 것처럼 의미 전달하는데는 크게 무리가 없을 것 같아요 그런데 유지보수함에 있어서 해당 로직은 여러 도메인에서 쓰일 로직이라 규격을 만들어두면 편할 것 같다고 생각합니다ㅎㅎ

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private Member member;
명시해주는 것보다는 생략하는게 낫다고 생각하셔서 작성해주셨군요👍🏻
개인적으로는 명시해줌으로 오는 안정성을 중요하게 생각하지만, 폴라의 의견도 합리적이라고 생각합니다!

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
JPA에 대해서 잘 알고 계시군요👍🏻
기본적으로 프록시를 만들어서 관리하고 있기 때문에 Hibernate의 구현 특성상 기본 생성자를 필수로 요구하고 있습니다.
말씀해주신 것처럼 접근제어자는 protected로 사용하는 것이 좋아보이네요ㅎㅎ

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/reservation/domain/Reservation.java
>          return new Reservation(date, timeId, themeId, memberId);
리팩터링을 진행하다보면 기존 구조에서 변형되어야할 필요가 있을때가 있어요.
원인을 잘 파악해주셨네요 수정 감사합니다!

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/member/domain/Member.java
> +    private MemberRole role;
`ORIGINAL` -> `ORDINAL`
설명해주신 내용 합리적입니다!👍🏻

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
id를 받아와서 생성하는 정적 팩토리 메서드는 현재 테스트에서만 사용되어지고 있는 것 같은데요.
id의 생성전략이 DB에 의존하고 있는데 id를 주입받아서 생성해야할 경우가 있을까요?

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/member/domain/Password.java
> +    }
해당 메서드를 사용하지 않는 것 같은데 확인 부탁드립니다.

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/member/domain/Password.java
>      }
개인적으로 만약에 null로 생성이 필요하다면 필요한 시점에 직접 null로 넣어주는게 명시적이라 좋아보입니다.

그리고 validation이 필요한 생성자와 validation이 필요없는 생성자가 필요하다면 
해당 내용에 대해서도 메서드에 명시를 해주는 것이 사용하기 좋을 것 같아요.

위에서 커멘트로 남기긴했는데, 해당 기능이 더이상 사용되는 것 같지 않아서 한번 확인 부탁드릴게요.

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/reservation/service/ReservationService.java
>      }
리팩터링하고 난뒤 코드가 아주 깔끔해졌군요👍🏻

2024-05-18 07:54 UTC, Hyunta commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        ReservationResponse.fromReservation(reservationRepository.save(saveReservation));
네 합리적인 대응이라고 생각됩니다ㅎㅎ

아래는 개인적인 생각인데 한번 고민해봐주세요.
코드를 할 때 중복가능성을 포착했을 때 크게 두가지 방법으로 대응할 수 있을 것 같아요.
1. 중복된 코드를 사용 -> 분리 가능성이 보였을 때 분리
2. 분리된 동일한 코드를 사용 -> 분리 가능성이 보였을 때 분리된 곳에 구현

분리 가능성이 보이게된다면 조삼모사격이 되기 때문에 1,2번 중에 뭐가 낫다고 판단할 수 없을 것 같습니다.

그런데 만약 끝까지 분리 가능성이 보이지 않으면 어떻게 될까요? 코드를 두벌 관리하는 것 자체가 리소스니 합치자는 의견이 나올 것입니다. 
1번의 경우에는 아무 작업이 필요하지 않죠. 
2번의 경우 혹시 기능이 다른지 확인한 후에 코드르 합치고 정상 작동하는지 테스트를 해야합니다. 비용이 발생하게 되죠.

그래서 개인적으로는 추후에 분리 가능성이 보였을 때 중복 코드를 분리하는 것이 
미리 분리 가능성을 예측하여 분리하는 것 보다는 낫다고 생각합니다.

2024-05-18 08:58 UTC, jinchiim commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +public interface MemberRepository extends Repository<Member, Long> {
> 여기서부터는 개인적인 생각인데, 추상화 수준이 한단계 위에 있다고 여겨집니다.
Repository - CrudRepository 에서는 CRUD 기능을 Repository라는 기능을 명시해주고 있어요.
Repository - MemberRepository 에서는 Member와 관련된 Repository 라는 특정 도메인을 위한 Repository를 나타내고 있습니다.
그렇다면 CrudRepository와 MemberRepository가 같은 수준으로 묶일 수 있을까 고민해봐야할 것 같은데, 아무래도 CrudRepository가 조금 더 추상적이라고 생각이 듭니다. 그래서 저는 Repository를 직접 사용하는 것 보다는 기능 명세가 된 Repository를 사용하는게 적절하다고 보여져요.

오... 굉장히 좋은 내용이네요 🤨 
좋은 자료와 좋은 의견 감사합니다. 너무 좋아서 캠퍼스에서 춤을 추고 있어요.

저도 개인적인 의견을 말씀드려보려고 하는데요!

개인적으로는 `CRUD` 기능을 필요로 하지 않았고 말씀하신 대로 
**레포지토리 라는 마킹**만을 필요로 했기 때문에 위와 같이 선택한 것이 맞습니다!

다만, `CrudRepository` 와 `ListCrudRepository`는 추상화 수준보다는 해당 `Repository`를 사용하려는 유저의 편의성을 위해 나왔다고 생각하고 있습니다!
(단순히 이를 상속받고 CRUD 같은 기능들은 굳이 명시하지 않아도 사용할 수 있도록)

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/105053478/c4a4dede-5079-456d-93c8-1f2a8bc7251b)
`Repository` 에 들어갔을때 이와 같은 내용이 적혀있었는데요.

> 해당 인터페이스를 상속받은 도메인 인터페이스들은 같은 시그니처를 사용해서 메서드들을 선언해 선택적으로 사용할 수 있다

고 해석했습니다. (~제 해석이 요상하다면 꼭 말씀해주세요!~)

또, 해당 `Defining Repository Interfaces` 를 확인했을때 보이는 첫번째 문단에서의 내용인데요,

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/105053478/1993c8b8-6c53-4eb6-8bba-4f55a8614c5a)

따라서 저는 `CrudRepository`는 단순히 해당 메서드를 선언하지 않고도 사용하게 하도록 편의성을 위해 만들어두었을 뿐,
사용하지 않고 상속받아 같은 메서드를 선언하는 것 만으로 그 도메인에 대한 기능 명세의 역할을 해줄 수 있다고 생각합니다!

만약 기능 명세를 위해서 중간에 단계를 두어 해당 `Repository`를 공유하는 방식으로 둔다면 
결국 특정 도메인에서 사용하는 메서드들이 노출이 되어지고, 메서드들을 추가할때마다 중간 단계에도 메서드들을 추가해야 하는
일들이 발생하지 않을까요?

그렇다면 저는 단순히 메서드를 하나 추가해 사용하는 `JPA`의 장점을 누리지 못하는 것은 아닌지 고민이 됩니다 🤔

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/105053478/97ad8c8c-0dd6-4297-800e-db7dddf615bb)

또, 좀 더 확인해보니 이와 같이 `@Entity` 혹은 `@Document` 를 부착하게 되는 방식도 권장하는 것 같더라구요!

다만, 저도 `@NoRepositoryBeans` 에 대해서는 왜 예시에서는 붙이지 않았는지 궁금해 확인해보니

![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/105053478/46d9c807-a8ca-4298-8d36-3102bab62c51)
해당 어노테이션의 경우, `Repository`를 상속받아 실제 사용하는 `CustomRepository`를 이용하는 것이 아닌,
또 다른 `BaseRepsitory`를 만드는 경우에 실제 사용하는 `Repository`가 아님을 명시하기 위해 사용하는 듯 했습니다!
(스프링 빈도 생성하지 않구요!)

이에 대해서 아서의 의견은 어떠실까요?! 🥰
좋은 자료 감사합니다 덕분에 더 생각해볼 수 있었네요!

2024-05-18 09:02 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Member.java
> +    private MemberRole role;
어... `ORIGINAL`.... 😅 
개떡같이 말했는데...  감사합니다 ㅋㅋㅋㅋㅋㅋㅋ 왜 오리지날이라고 했을까요...

2024-05-18 09:05 UTC, jinchiim commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private Member member;
사실 웃기게도 말씀드렸던 서비스 코드에서는 `@JoinCoulmn`을 전부 명시해주고 있긴 합니다 ㅋㅋㅋ
같이 일하는 사람이 있으면 확실히 명시해주는 것이 더 좋게 여겨지더라구요.. (실수하기도 좋고..)

그저.. 새로운 사실을 알게 되어서 신기해서 떼어보았습니다 😁
저도 안정성이 좋아 다음 PR때 다시 붙여보겠습니다!

2024-05-18 09:14 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Password.java
>      }
`Member` 생성자를 수정하면서 사용을 더이상 안하게 되었던걸 캐치를 못한 것 같습니다ㅜ
`Email`에 존재하는 생성자도 사용을 안해 같이 지우겠습니다!

2024-05-18 10:14 UTC, jinchiim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        ReservationResponse.fromReservation(reservationRepository.save(saveReservation));
좋은 의견이라고 생각합니다!

실제로 페어와 프로그래밍을 하다가도 해당 메서드는 `admin` 에 두어야 할지, `Member`에 두어야 할지 고민하기도 했는데
여기서 비롯되었을 수 있을 것 같다는 생각이 드네요 🤔

다만 `admin` 권한은 너무나도 큰 도메인이다보니 아직까지 분리 가능성이 보이지 않을 수 있을까..? 에는 조금 고민이 들어
다음 미션을 진행하면서 조금 더 고민해보겠습니다!

2024-05-18 10:14 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Password.java
> +    }
삭제했습니다!

2024-05-18 12:14 UTC, jinchiim commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
이전 미션의 남은 잔해가 많네요 🤔

확실히 이제 `JDBC Template`이 아니니 주입 받을 일이 없을 것 같습니다.
`id` 를 파라미터로 받는 모든 생성자를 없애줬습니다!

2024-05-18 13:05 UTC, jinchiim commented on src/main/java/roomescape/member/service/MemberService.java
> +                .orElseThrow(() -> new RoomEscapeException(MemberExceptionCode.ID_AND_PASSWORD_NOT_MATCH_OR_EXIST));
새로운 동료가 들어온다면 `NotFound` 정도는 있는게 확실히 좋을 것 같네요 
`Enum`에서 원하는 이름으로 정한다면 찾는것에 시간이 꽤 걸릴 수도 있을 것 같긴 합니다. 

물론 문서로 컨벤션이 있겠지만 **코드로 존재하는 것만큼 확실**한게 없겠죠 🤔🤔
이번 요청에서 해당 부분을 반영해보았는데요! 아서가 의도하신 방향이 아니라면 꼭 말씀 부탁드립니다!

## 구현 방식

기존에 `RoomEscapeException`을 상속받도록 해 `handler`에는 영향이 가지 않도록 구현했는데요.

다만 처음에 `Enum`을 받도록 하다보니 메시지는 그대로 있어야 하는 일이 발생했고 
그런다면 `ObjectNotFoundException`이 있더라도 기존 방식처럼
 `RoomEscapeException(MemberExceptionCode.~~)` 를 사용해 구현하는 일이 발생할 것 같아 

생성자를 추가하는 방식으로 변경했습니다.

```java
public class RoomEscapeException extends RuntimeException {

    private final HttpStatus httpStatus;
    private final String message;

    public RoomEscapeException(ExceptionCode exceptionCode) {
        super(exceptionCode.getMessage());
        this.httpStatus = exceptionCode.getHttpStatus();
        this.message = exceptionCode.getMessage();
    }

    public RoomEscapeException(String message, HttpStatus httpStatus) {
        super(message);
        this.httpStatus = httpStatus;
        this.message = message;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }

    public String getMessage() {
        return message;
    }
```


```java
public class ThemeNotFoundException extends RoomEscapeException {

    private static final String THEME_NOT_EXIST_MESSAGE = "해당하는 테마가 존재하지 않습니다.";

    public ThemeNotFoundException() {
        super(THEME_NOT_EXIST_MESSAGE, HttpStatus.BAD_REQUEST);
    }
}

```

그 후 `NotFound~` 메시지들은 `Enum`에서 지운 뒤

```java
    public MemberLoginCheckResponse findLoginMemberInfo(long id) {
        Member member = memberRepository.findMemberById(id)
                .orElseThrow(MemberNotFoundException::new);

        return new MemberLoginCheckResponse(member.getName());
    }
```
이와 같이 사용하도록 변경해보았습니다 어떻게 생각하실까요?? 
점점 `Exception`에도 컨벤션이 생기는 것 같아 좋네요! 😁

2024-05-18 13:32 UTC, Hyunta commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +public interface MemberRepository extends Repository<Member, Long> {
깊게 학습을 해보셨군요ㅎㅎ
나열해주신 근거가 합리적이라고 생각합니다.
일단 Repository로 진행하시죠!

그러게요 애노테이션 부분은 필요 없을 것 같습니다

2024-05-18 13:33 UTC, Hyunta commented on src/main/java/roomescape/member/service/MemberService.java
> +                .orElseThrow(() -> new RoomEscapeException(MemberExceptionCode.ID_AND_PASSWORD_NOT_MATCH_OR_EXIST));
네네 수정해주신 방향대로 구현하시면 앞으로 확장하는 방향에 대한 컨벤션이 갖춰지겠네요.
아주 좋습니다👍🏻

2024-05-18 13:35 UTC, Hyunta commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        ReservationResponse.fromReservation(reservationRepository.save(saveReservation));
네 괜찮습니다 다음 단계 진행해보시면서 고민을 해보시죠ㅎㅎ!

2024-05-18 13:36 UTC, Hyunta approved these changes
안녕하세요 폴라,
피드백 확인을 아주 빠르게 해주셨네요ㅎㅎ
JPA를 깊게 학습해주셔서 저도 같이 찾아보게되서 좋았습니다.
남겨주신 커멘트들 확인 했습니다.
다음 단계 진행하시면서 계속 고민해보시죠!

2024-05-18 13:36 UTC, merged