[3 - 4단계 방탈출 예약 대기] 테니(나아연) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #121
Opened 2024-05-23 04:35 UTC by ay-eonii

안녕하세요 제이! 
3-4단계 미션 리뷰도 잘 부탁드립니다 🙇‍♀️

미션을 진행하면서 고민했던 부분이 있습니다.
아래는 제가 작성한 기능 요구사항입니다.
> - [ ] 예약이 존재하지 않을 때 예약 대기 요청을 보내면 예약 대기 대신 예약 성공합니다.
>
> - [ ] 예약 취소가 발생 시 예약 대기자가 있는 경우 예약 승인이 되는 기능을 구현하세요.
    - 자동으로 승인 : 예약 취소가 발생하는 경우 예약 대기가 있을 때 우선순위에 따라 자동으로 예약이 되도록 할 수 있다.

자동 승인 로직을 구현하면서 WaitingServiced의 create 메서드와 ReservationService에서 delete 메서드에서 Reservation 생성까지 수행하도록 했더니 하나의 메서드가 너무 많은 일을 한다고 느꼈습니다.

그래서 현재는 AutoReserveService를 만들어 예약이 없고, 대기가 있는 경우 자동으로 예약으로 변경하도록 구현했습니다.
  
하지만 이 경우에도 객체들끼리 메시지를 던지고 객체가 자신이 알고있는 부분에 대해서만 일을 한다는 느낌이 잘 들지 않는 것 같습니다. 제가 생각하기에는 AutoReserveService가 WaitingService와 ReservationServicer가 알고 있는 것 (ReservationServicer, WaitingService)를 알고 있기 때문에 객체의 역할이 불분명하게 느껴지는 것 같습니다.

```java
@Service
@Transactional
public class AutoReserveService {
    private final ReservationRepository reservationRepository;
    private final WaitingRepository waitingRepository;
    ...
```

```java
@Service
@Transactional
public class WaitingService {
    private final WaitingRepository waitingRepository;
    private final MemberRepository memberRepository;
    private final ReservationRepository reservationRepository;
    ...
```
```java
@Service
@Transactional
public class ReservationService {
    private final ReservationRepository reservationRepository;
    ...
}
```
**정리하자면 service는 객체지향적으로 설계하기 어려운 것인지, 그게 아니라면 제가 service를 잘못 사용하고 있는 것인지 궁금합니다.**

추가적으로, 대기를 예약으로 변경하는 API를 생성하고 클라이언트에서 해당 API를 따로 요청하는 게 나을까 라고 생각도 했습니다. 
하지만 아래의 판단을 기준으로 현재와 같이 구현했습니다 (+ js에 대해 잘 모른다는 이유도 있습니다😅)
1. 대기를 예약으로 변경하는 것이 예약 삭제(또는 예약없이 대기 생성)이 하나의 컨텍스트로 이루어지는 게 자연스럽다
2. 두 개의 API를 호출해야한다는 관리포인트가 하나 더 늘어난다

감사합니다 제이😊

2024-05-24 02:48 UTC, JunHoPark93 requested changes
안녕하세요 테니~
미션 구현하느라 고생많으셨습니다.
고민을 많이 해주신게보이네요. 추가적으로 미션에 대한 요구사항도 정의해보신게 인상깊었습니다.
질문주신 부분에도 코멘트 남겨두었는데 확인해보시고 의견 및 반영부탁드려요~

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/AutoReserveService.java
> +    private final WaitingRepository waitingRepository;
> 자동 승인 로직을 구현하면서 WaitingService의 create 메서드와 ReservationService에서 delete 메서드에서 Reservation 생성까지 수행하도록 했더니 하나의 메서드가 너무 많은 일을 한다고 느꼈습니다.
> 
> 그래서 현재는 AutoReserveService를 만들어 예약이 없고, 대기가 있는 경우 자동으로 예약으로 변경하도록 구현했습니다.
> 
> 하지만 이 경우에도 객체들끼리 메시지를 던지고 객체가 자신이 알고있는 부분에 대해서만 일을 한다는 느낌이 잘 들지 않는 것 같습니다. 제가 생각하기에는 AutoReserveService가 WaitingService와 ReservationService가 알고 있는 것 (ReservationRepository, WaitingRepository)를 알고 있기 때문에 객체의 역할이 불분명하게 느껴지는 것 같습니다.
> 추가적으로, 대기를 예약으로 변경하는 API를 생성하고 클라이언트에서 해당 API를 따로 요청하는 게 나을까 라고 생각도 했습니다.
> 하지만 아래의 판단을 기준으로 현재와 같이 구현했습니다 (+ js에 대해 잘 모른다는 이유도 있습니다😅)
> 
> 대기를 예약으로 변경하는 것이 예약 삭제(또는 예약없이 대기 생성)이 하나의 컨텍스트로 이루어지는 게 자연스럽다
> 두 개의 API를 호출해야한다는 관리포인트가 하나 더 늘어난다
> 

> 정리하자면 service는 객체지향적으로 설계하기 어려운 것인지, 그게 아니라면 제가 service를 잘못 사용하고 있는 것인지 궁금합니다.

잘못사용하고있기보다는 현재 판단기준으로는 잘 사용하셨습니다. 다만 뭔가 이상함을 느끼고 계셔서 질문을 주신거같아요.
그럼 판단기준이 잘못되었나를 생각해보시면 어떨까요?

예약삭제와 동시에 대기를 예약으로 변경하는것이 하나의 컨텍스트로 이루어지는게 자연스러울까요?
예시를 들어볼게요, 나는 빨리 예약을 삭제하고싶은데 다른 모르는 누군가의 대기에 문제가 생겨서 내 예약이 삭제가 계속 안되거나 지연이 생기면 어떤 사용자 경험을 줄까요?

실제로 이런 문제를 해결하기위해 느슨한 결합을 가지도록 설계를 합니다. 지금 이 미션에서의 주요목표와는 살짝 거리가 있는듯하고 테니가 추가로 구현하신 내용이라 여기까지만 코멘트 남길게요. 혹시나 꼭 개선을 해보고싶다하면 고민해보시고 다시 말씀주시면 같이 해결해보아요.

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/AutoReserveService.java
> +    }
optionalWaiting의 get을 호출하지않고 로직을 개선해볼수있을까요?

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/dto/reservation/AutoReservedFilter.java
> +public record AutoReservedFilter(
네이밍을 왜 filter라고 지으셨나요?

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +        }
validation기능의 depth를 맞춰보면 어떨까요?

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +
위부분을 메서드로 분리하여 cancel메서드의 가독성을 높여보면 어떨까요?

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +        if (!exists) {
if (!waitingRepository.existsById(waitingId)) ... 
한줄로 써도 될거같아요

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/domain/reservation/Waiting.java
> +    public Waiting() {
다른 접근제한자도 가능할까요?

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        e.printStackTrace();
이부분은 넣으신 이유가있을까요?

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/AutoReserveService.java
> +    }
이부분도 로컬변수쓰지 않아도될거같아요.

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +        }
중요한 부분인데 놓치지 않고 검증해주셨네요 👍🏼👍🏼

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +        final Waiting waiting = waitingRepository.findById(waitingId)
전체적으로 메서드가 복잡해지면서 검증과 로직이 같이 있게 되는 상황입니다. 이부분도 분리를해서 가독성을 높여보면 좋을거같아요.

2024-05-24 02:48 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +@Transactional
모든 메서드에서 필요한 부분일까요?

2024-05-24 02:50 UTC, JunHoPark93 commented on src/main/java/roomescape/service/AutoReserveService.java
> +    private final WaitingRepository waitingRepository;
혹은 AutoReserveService 의 기능을 다른 서비스에 합치는것도 고민해보시면 좋을거같아요.

2024-05-26 05:50 UTC, ay-eonii commented on src/main/java/roomescape/service/AutoReserveService.java
> +    private final WaitingRepository waitingRepository;
> 예약삭제와 동시에 대기를 예약으로 변경하는것이 하나의 컨텍스트로 이루어지는게 자연스러울까요?
예시를 들어볼게요, 나는 빨리 예약을 삭제하고싶은데 다른 모르는 누군가의 대기에 문제가 생겨서 내 예약이 삭제가 계속 안되거나 지연이 생기면 어떤 사용자 경험을 줄까요?

들어주신 예시로 생각해보니, 예약취소부터 대기 승인을 하나의 컨텍스트로 다룸으로써 하나의 오류가 더 많은 곳에 영향을 미칠 수 있겠다는 생각이 들었어요. 서로 영향을 적게 받도록 느슨한 설계를 한다는 것도 이해했습니다. api를 분리하지 않는 이상 서비스를 분리하는 것이 가장 느슨한 결합이라고 생각했기에 지금의 상태를 유지하고자 합니다.

그런데 아래에 말씀해주신 부분에 대해서는 궁금한 점이 있어요.

> 혹은 AutoReserveService 의 기능을 다른 서비스에 합치는것도 고민해보시면 좋을거같아요.

저는 AutoReserviceService를 분리함으로써 다른 서비스와의 결합도를 낮췄다고 생각해요. 만약 자동 승인 정책이 없어지거나 바뀐다면 controller 에서 호출하는 부분만 제거하면 되지만, 다른 서비스와 합치는 경우 예약을 삭제하는 로직을 만져야할 것 같아요. 

제이는 어떻게 생각하시나요? 위 코멘트를 남겨주신 의도가 궁금합니다 🥹

2024-05-26 22:33 UTC, JunHoPark93 commented on src/main/java/roomescape/service/AutoReserveService.java
> +    private final WaitingRepository waitingRepository;
결합도를 낮췄다고 생각하셨지만, 실제로 중복 repostiory들에 대한 정의가 신경쓰여서 최초에 이 코멘트를 남겨주신거같아요.
그럼 더 느슨하게 분리하거나, 다시 합치거나 둘중의 하나의 방법을 선택해야하고 2가지 방법을 말씀드린거였어요~

첫 번째 방법은 이벤트를 발행해야하니 지금당장은 어렵고 다시 합치는것은 테니가 말씀주신것처럼 단점이 존재하네요. 현상유지 해주시면 될거같아요!

2024-05-26 22:38 UTC, JunHoPark93 commented on src/main/java/roomescape/dto/reservation/AutoReservedFilter.java
> +public record AutoReservedFilter(
메서드가 아니라 클래스라서 단순필터외에 전,후처리가 기대가 됐긴했었습니다. (현재 내부에 단순히 from메서드에서 필드추출밖에 없어서요) 개인취향이니 참고만해주세요!

2024-05-26 22:41 UTC, JunHoPark93 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        e.printStackTrace();
예외메세지를 따로 로그에 남기고싶어서 사용하신거군요. 불편함을 잘 찾아주셨네요!
추후에는 해당 작업의 단점을 찾아보시고 프로젝트하실때는 다른 방법을 시도해보셔요!

2024-05-26 22:52 UTC, JunHoPark93 commented on src/main/java/roomescape/service/WaitingService.java
> +@Transactional
읽기전용은 메서드에 따로 명시를 해주시는정도로 기대를 했는데요, (잘 반영해주셨어요)

말씀주신것처럼 없으면 LazyInitializationException이 발생을합니다. 근데 서비스의 단위테스트가 없으면이라는 말이 어떤 말씀이실까요? 테스트코드가 없으면 transactional을 쓰지 않아도 될지에 대한 내용일까요?

테스트유무와는 관계없이 transactional로 경계는 만들어주셔야합니다. 테니가 위에 각 메서드별로 판단해주신 기준에 따라 묶으신건 잘하셨어요.

혹시 해결이 되지 않는다면 다시말씀해주세요!

2024-05-26 22:53 UTC, JunHoPark93 approved these changes
안녕하세요 테니~
리뷰 반영하느라 고생많으셨어요.
해결되지 않는 부분이 있다면 다시 말씀해주세요.
다음 미션도 화이팅입니다!

2024-05-27 22:55 UTC, merged