[STEP 3,4] 이든(최승준) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #122
Opened 2024-05-23 05:25 UTC by PgmJun

2024-05-23 14:39 UTC, seovalue commented
> 테스트코드가 원래 이렇게 긴가요? 😵
> 테스트 코드를 아는대로 작성하다보니 뭔가 중구난방 테스트 코드가 된 것 같습니다..
> 로직이 너무 길어서 나중에 제가 봐도 이해하기도 어려울 것 같아요.
> 그래서 최근 테스트 코드에 대한 고민이 많아졌는데 혹시 추천해주실만한 래퍼런스나 조앤의 팁을 얻을 수 있을까요?!

테스트코드의 가독성은 비즈니스 코드만큼이나 중요하다고 생각해요.
테스트코드의 가독성이 떨어지면 유지보수할 때 스트레스를 받게 되고 이는 코드 제거로 이어진다고 생각해요.
잘 작성할 수 있는 방법은.... 사실 없는 것 같습니다! ㅋㅋ
최대한 주석을 잘 활용하고 중복된 부분을 분리하면서 개선해나가는 수 밖에 없는 것 같아요..ㅎㅎ
Given/When/Then 구조도 비슷한 맥락인 것 같고요ㅎㅎ
주석을 잘 활용해보시는 거 추천드려볼게요

2024-05-23 14:46 UTC, seovalue commented
> HttpServletRequest에 JWT 파싱 값을 넣어 HandlerMethodArugmentResolver로 넘겨주는 방식은 좋지 않은가요?
> 현재 JWT의 AccessToken을 파싱하고 토큰 내부에 있는 값을 HttpServletRequest에 담아 ArgumentResolver에 넘겨주고 있습니다.
> 그런데 크루원들이 이야기 하는 걸 듣다가, 요청을 받은 이후 Request에 데이터를 담는 것이 안티 패턴이라는 이야기를 들었습니다.
> 유저로 부터 요청받은 순수한 Request 정보에 변경을 일으키는 일은 좋지 않다는 이야기인 것 같았는데
> 조앤은 이 부분에 대해서 어떻게 생각하시는 지 궁금합니다!
> (저는 맞는 말인 것 같아서 변경을 고민하고 있습니다..!)

AuthInterceptor의 setAttribute 부분 말씀하시는 건가요?
기존 값에 대한 변경이라기 보다는 새로운 값을 추가한다는 느낌이긴 한데. 저는 크게 문제없다고 생각하긴 해요.
만약 이 방법이 아니라면 Cookie나 헤더에 담아서 읽는 방식으로의 변경을 고민하시는 걸까요?
그리고 변경을 일으키는 일은 좋지 않다에 공감하시게 된 이유도 궁금~

2024-05-23 15:03 UTC, seovalue requested changes
안녕하세요 이든~
미션 잘 수행해주셨네요ㅎㅎ 
코멘트 남겼는데 리팩터링 후 리뷰 요청 주세요!
전체적으로 메서드를 가볍게 개선해보면 좋을 것 같아요~!

2024-05-23 15:03 UTC, seovalue commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public ReservationResponse addReservationWaiting(final ReservationRequest request, final Long memberId) {
그리고 이 메서드도 굉장히 무거워요. 공통된 부분은 분리하고 Waiting만에 필요한 값들이 있다면 그 부분이 잘 드러나도록 개선해보면 좋을 것 같아요.

2024-05-23 15:03 UTC, seovalue commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @DeleteMapping("/reservations/waitings/{reservationId}")
취소와 삭제에 대해서 어떻게 생각해요? 취소는 삭제인가요?

2024-05-23 15:03 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +public interface MemberReservationRepository extends JpaRepository<MemberReservation, Long> {
모든 쿼리가 JOIN하고 있는데 개선할 수 있는 방법은 없을까요?

2024-05-23 15:03 UTC, seovalue commented on src/test/java/roomescape/reservation/controller/ReservationControllerTest.java
> +        Reservation reservation1 = reservationRepository.save(new Reservation(LocalDate.now(), reservationTime, theme, member));
공통으로 사용되는 Fixture를 한 군데서 관리해보면 어떨까요.
그리고 네이밍도, reservation1이라고 하면 어떤 예약인지 알기가 어렵다고 생각해요. (인간1 vs 조앤)
테스트코드는 가독성이 중요하니깐, 한글 변수를 써봐도 괜찮을 것 같아요ㅎㅎ

2024-05-23 15:03 UTC, seovalue commented on src/test/java/roomescape/reservation/controller/ReservationControllerTest.java
> +        Reservation reservation1 = reservationRepository.save(new Reservation(LocalDate.now(), reservationTime, theme, member));
관련해서 전체적으로 리팩터링해보면 좋을 것 같아요~~

2024-05-24 04:41 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/MemberReservation.java
> +public class MemberReservation {
예약대기가 없었을 때는, 하나의 예약 정보(Reservation)에 대해 한 명의 회원(Member)만 예약을 할 수 있었습니다.

하지만 예약대기가 추가되면서
하나의 회원(Member)이 여러 예약 정보(Reservation)에 예약 요청을 할 수 있고
하나의 예약 정보(Reservation)에 여러 회원(Member)이 예약/예약대기 을 할 수 있게 되었습니다.
이때 N:M 관계가 형성되었습니다.

보통 N:M 관계가 형성되었을 때, 제2정규화에 의해 중간 테이블이 분리되는 걸로 알고 있는데
저희는 데이터베이스에서 순차적으로 증가시켜주는 auto_generated id를 PK로 사용하고 있어서 제2 정규화에 해당되는 문제는 크지 않겠지만
N:M 형태의 테이블을 분리하지 않을 시,
reservation 테이블이 무거워지고 동일한 예약 정보(테마/시간/날짜)임에도 불구하고 유저 정보, 예약 상태가 다르다는 이유로 테이블에 중복 정보(테마/시간/날짜)가 계속 저장되어야 합니다.

하지만 중간 테이블을 분리하면, reservation 테이블에서 동일한 예약 정보(테마/시간/날짜)를 계속 생성할 필요없이 이미 같은 정보로 생성된 레코드가 있다면 재활용할 수 있었고,
회원의 예약 추가 시, 가벼운 정보만을 member_reservation에 담을 수 있었습니다.
데이터 저장 코드도 훨씬 가볍게 됩니다. (ex. new Reservation(member, theme, time, date, order) -> new Reservation(theme, time, date), new MemberReservation(member,reservation,order))

그런데 답변을 남기면서 코드를 살펴보니 설명드린 의도대로 코드를 만들어나가고 있지 않았더라구요..!
이 부분은 한 번 리팩토링 해보겠습니다..!!

2024-05-24 05:08 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/MemberReservation.java
> +    private ReservationStatus status;
Reservation을 재활용해서 사용하려다보니 status가 MemberReservation에 들어가게 되었는데요..! 어색하게 느끼시는 포인트를 알 것 같습니다. 네이밍이 가장 큰 문제인 것 같은데요.

Reservation이 현재 예약 세부 정보(테마,시간,날짜)를 담고 있으니 ReservationDetail로 바꾸고
유저의 예약 정보를 관리하는 MemberReservation을 Reservation으로 변경해보면 어떨까요??
우선 한 번 변경해보겠습니다!!

2024-05-24 06:14 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/MemberReservation.java
> +    }
order 컬럼은 
관리자 예약 대기 정보 조회 시에, 1번째 대기 정보만 조회해야해서 어떻게 해야 순서를 편하게 조회할까 생각하다가
발생하게 된 설계 미스라는 생각이 되어요..
DB에서 등록된 순서대로 생성되는 ID(PK)를 사용해도 될 것 같은데 그 당시에 생각이 나지 않았던 것 같습니다 😅

지금 상태는 `예약 취소`, `예약 대기 승인`, `예약 대기 취소` 시에
하위의 order를 재정렬해주기 위해 여러 건의 UPDATE 쿼리가 발생하게  되는데, 이건 좋지 않은 설계인 것 같다고 느껴집니다.

그래서 현재 변경하고자 하는 방향은 order 컬럼을 제거하고
1번째 대기 예약 정보를 조회하는 로직을
reservation_id 별로 GROUP BY 한 후, 상태가 WAITING이고 그 중 가장 id가 작은(가장 최근에 생성된) member_reservation을 조회하는 것이 좋을 것 같습니다. 쿼리는 어떻게 짜야할 지 고민이 되네요
한 번 변경해보겠습니다!

2024-05-24 06:16 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/MemberReservation.java
> +    public void increaseOrder() {
오더 증가와 상태 변경은 다른 기능인 것 같아 분리하는 게 좋다고 생각이 드네요!

+ 그런데 [위에서](https://github.com/woowacourse/spring-roomescape-waiting/pull/122#discussion_r1612875506) 답변드렸다시피 order를 제거하면서 이 부분의 로직이 변경될 것 같습니다!

2024-05-24 06:17 UTC, PgmJun commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        changeWaitingOrdersStatus(reservation);
정말 맞는 말씀입니다.. 안그래도 비효율적인 부분이라고 생각이 들었어요
[여기서](https://github.com/woowacourse/spring-roomescape-waiting/pull/122#discussion_r1612875506) 말씀드린대로 제거하는 방향으로 리팩토링 해보겠습니다!

2024-05-24 06:25 UTC, PgmJun commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @ResponseStatus(HttpStatus.CREATED)
응답 정보를 더 풍부하고 구체적으로 보내줄 수 있는 응답 정보의 확장성을 얻기 위해
ApiResposne, ErrorResponse 객체를 만들어주었는데,
다양한 DTO를 받기 위해 ApiResponse도 제네릭을 사용하다보니 `ApiResponse<ResposneDTO>` 형태가 되었습니다.

그런데 여기서 `ResponseEntity`를 사용하게 되면
`ResponseEntity<ApiResponse<ResponseDTO>>` 형태가 되어서
Response 타입 지정 코드가 너무 길어졌습니다.

이 시점에서 제가 현재 ResponseEntity를 사용하고 있는 이유를 고민했는데, 상태 코드를 설정해주기 위한 목적이 강했습니다.

저는 ResponseStatus로 상태코드를 설정해줄 수 있는 걸 알고 있었기 때문에 
`ResponseEntity<ApiResponse<ResponseDTO>>`로 응답하던 형태에서 
`ApiResponse<ResponseDTO>, ResponseStatus()` 형태로 변경을 적용해보니
훨씬 보기 좋기 깔끔하다는 생각이 들어 이 방식을 적용하게 되었습니다.

2024-05-24 06:27 UTC, PgmJun commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public void removeWaitingReservationById(final Long reservationId, final Long memberId) {
저도 비즈니스 로직이 너무 길지 않나? 라는 생각이 들긴 했습니다..!
레벨1을 돌아보면서 전반적인 코드를 수정해보겠습니다!

2024-05-24 06:38 UTC, PgmJun commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @DeleteMapping("/reservations/waitings/{reservationId}")
Soft Delete에 관련된 질문같다고 느껴집니다!
현실에서의 `취소`가 데이터 측면에서는 `상태변경` OR `삭제` 둘 중 하나의 결과를 만들 수 있을 것 같아요

`예약 대기`의 경우 실제로 결제 또는 예약이 되지 않은 상태이기 때문에 예약 대기는 취소 요청 시 데이터 삭제로 이어져도 괜찮을 것 같다고 생각합니다.

하지만 예약의 경우는 방탈출 카페 운영에 있어서 정말 중요한 요소라고 생각해요.
회원의 예약 취소 시, 삭제되도록 구현하는 경우
갑자기 누군가가 예약 시간이 얼마 남지 않았을 때 예약을 취소해서 DB의 데이터가 삭제된다면
관리자 측에서는 예약 시간 직전에 예약자 정보가 갑자기 사라져서 어리둥절한 상황이 발생할 것 같다고 생각이 듭니다.
이러한 상황에는 상태 변경으로 처리를 해야할 것 같다고 생각해요!

하지만 현재 구현된 상태에서 회원은 예약이 확정된 경우 직접 예약을 삭제할 수 없고,
방탈출 카페에 전화해서 예약을 조정해야 한다는 가정 하에 설계해두었습니다.
그럼 예약 취소를 관리자가 직접하기 때문에 예약 취소 시, 삭제로 이어지도록 구현했습니다.

> 그런데 이렇게 개발하게 되면 회원이 서비스를 이용하기 불편할 것 같다는 생각이 들어서
만약 개발할 수 있는 시간이 더 많았다면, 이렇게 구현하지 않고 예약 취소 신청 기능을 구현해서 관리자 측에 취소 의사를 요청할 수 있도록 구현했을 것 같습니다!

2024-05-24 07:12 UTC, PgmJun commented on src/test/java/roomescape/reservation/controller/ReservationControllerTest.java
> +        Reservation reservation1 = reservationRepository.save(new Reservation(LocalDate.now(), reservationTime, theme, member));
오호.. 한글 변수명 의견을 주신 것도 신기해서 찾아보았는데
토스 페이먼츠 팀에서 `세종대왕 프로젝트`라는 걸 진행했던 기록이 있네요 (컨벤션도 제공해주네요!)
https://tosspayments-dev.oopy.io/chapters/frontend/posts/hangul-coding-convention

프로덕션 코드까지는 아니더라도 테스트 코드에서는 충분히 시도해볼만한 방법인 것 같아요
높은 가독성의 테스트 코드.. 만들어보겠습니다.

2024-05-24 07:16 UTC, PgmJun commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public ReservationResponse addReservationWaiting(final ReservationRequest request, final Long memberId) {
요 부분은 다른 예약 대기 부분은 /reservations/waitings 엔드포인트로 구분되는데
예약 대기 추가만 /reservations 로 요청을 받는 것이 어색해서 구분해주게 되었습니다.

물론 조앤의 말씀대로 사실상 예약 상태만 다른 거의 동일한 비즈니스 로직이기 때문에
이 부분을 개선하려면 /reservations/waitings 라는 엔드포인트 사용에 대해서 먼저 고민해보아야할 것 같습니다.
한번 고민하고 적용 후에 다시 리뷰요청 드리겠습니다.
좋은 포인트를 짚어주셔서 감사합니다!

2024-05-24 07:28 UTC, PgmJun commented
> AuthInterceptor의 setAttribute 부분 말씀하시는 건가요? 기존 값에 대한 변경이라기 보다는 새로운 값을 추가한다는 느낌이긴 한데. 저는 크게 문제없다고 생각하긴 해요. 만약 이 방법이 아니라면 Cookie나 헤더에 담아서 읽는 방식으로의 변경을 고민하시는 걸까요? 그리고 변경을 일으키는 일은 좋지 않다에 공감하시게 된 이유도 궁금~

https://github.com/woowacourse/spring-roomescape-member/pull/134#discussion_r1597678025
위 리뷰에서 오리 말씀해주신 내용이 고민의 시작점이었는데요!

너무 깊게 파고든 생각이 아닐까 싶긴 하지만
유저가 HTTP를 통해 Request한 정보에 setAttribute를 통해 값을 추가해준다면
순수한 유저의 요청 내용에 변화가 생기는건데 그래도 되는걸까? 라는 생각이 들었어요. 그래서 변경을 해야할까 고민도 되었구요!
그래도 되는 지 잘 모르기 때문에 발생한 고민같아요

2024-05-26 09:39 UTC, PgmJun commented
안녕하세요 조앤 2번째 리뷰요청 드립니다!
조앤이 리뷰를 통해 짚어주신 부분 관련해서 수정이 많이 있었습니다.

## 주요 작업
- [order 컬럼을 제거](https://github.com/woowacourse/spring-roomescape-waiting/pull/122#discussion_r1612875506)하는 작업
- [MemberReservation, Reservation 테이블가 설계했던 의도와 조금 다르게 사용되고 있던 점](https://github.com/woowacourse/spring-roomescape-waiting/pull/122#discussion_r1612729161) 수정
- 어드민용 API 에 `/admin` endpoint 추가
- 테스트코드 리팩토링 및 보충(리팩토링은 가능한 최대한 하였는데, 픽스쳐를 사용하는 부분은 DM으로 질문을 드려서, 조앤의 답변이 오면 반영하겠습니다!)

2024-05-27 01:34 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +public interface MemberReservationRepository extends JpaRepository<MemberReservation, Long> {
네네 제가 이 코멘트를 남긴 이유는 중간 테이블이 사실상 중간 테이블 자체로만 조회될 때 성능상의 이점을 가져다 주는 것 같은데, 그렇지 않고 매번 source table을 Join해야한다면 하나의 소스테이블로 관리하는게 낫지 않을까?라는 생각이었어요. @PgmJun

2024-05-27 01:35 UTC, seovalue commented on src/test/java/roomescape/reservation/controller/ReservationControllerTest.java
> +        Reservation reservation1 = reservationRepository.save(new Reservation(LocalDate.now(), reservationTime, theme, member));
ㅋㅋㅋㅋㅋㅋ오 저도 이런건 첨봤네요! 👍

2024-05-27 01:40 UTC, seovalue commented
> > AuthInterceptor의 setAttribute 부분 말씀하시는 건가요? 기존 값에 대한 변경이라기 보다는 새로운 값을 추가한다는 느낌이긴 한데. 저는 크게 문제없다고 생각하긴 해요. 만약 이 방법이 아니라면 Cookie나 헤더에 담아서 읽는 방식으로의 변경을 고민하시는 걸까요? 그리고 변경을 일으키는 일은 좋지 않다에 공감하시게 된 이유도 궁금~
> 
> [woowacourse/spring-roomescape-member#134 (comment)](https://github.com/woowacourse/spring-roomescape-member/pull/134#discussion_r1597678025) 위 리뷰에서 오리가 말씀해주신 내용이 고민의 시작점이었는데요!
> 
> 너무 깊게 파고든 생각이 아닐까 싶긴 하지만 유저가 HTTP를 통해 Request한 정보에 setAttribute를 통해 값을 추가해준다면 최종적으로 서버가 받는 정보는 순수한 유저의 요청 내용이 아닌, 변화가 생긴 요청내용이 되는건데 이렇게 처리해도 되는걸까? 라는 생각이 들었어요.
> 
> 아직 관련 이슈에 대해서는 경험이 없어서 적극적으로 공감가는 부분은 아니었지만 `이렇게 처리해도 되는걸까?` 라는 생각이 드는 순간부터 학습 차원에서 변경에 대한 고민이 시작되었습니다.
> 
> 그런데 리뷰요청을 드린 지 조금 지난 현 시점에서는 개발자들간에 규칙만 잘 정하고 문서화 해놓는다면, 그 규칙내에서 요청 정보를 아주 살짝 건드리는 `setAttribute` 작업 정도는 괜찮을 것 같다는 생각이 들어서 변경은 하지 않을 것 같습니다:)
> 
> ## 만약 변경한다면?
> 만약 변경을 하게 되면 요청정보를 WAS 내에서 수정하는 것에 대해서 문제를 느꼈으니, 요청 값에 손을 대는 것 보다 `@RequestScope`을 사용할 것 같네요!
> 
> 요청이 도달하는 동안의 생명주기를 갖는 Spring Bean을 `@RequestScope`을 사용해서 만들고 거기서 memberId를 관리할 것 같습니다. 하지만 아직 관련 문제가 제대로 파악되지도, 발생하지도 않은 지금 상황에서 이렇게까지 하는 건 오버엔지니어링이라고 생각이 되네요!

대박 이거 Quote Reply 누르니깐 바로 위에처럼 되네요? 항상 복붙해서 바꿔줬는데ㅎㅎ

---

저 코멘트를 말씀해주신 의도는 저도 공감해요. 다만 저분의 의견을 100% 받아들이기보다는 왜?에 대해서 더 생각해보고, 이든만의 의견을 갖는게 저는 더 중요하다고 생각해요.
만약 다르게 생각해본다면 우리가 요청에 가끔 커스텀 헤더를 넣을 때도 있잖아요? 예를 들어 auth token과 같은 것을 header에 추가해서 넘겨주는 방법 등이 있을 것 같아요. 그럼 이런 것도 지양해야하는걸까요? 우리가 커스텀하는 부분들이 어디까지가 지양해야하고 어디까지를 지향해야하는 걸까요?

setAttribute를 통해 지정해준 값은, 지정된 Key를 통해서만 조회할 수 있어요. Key가 존재한다는 것은 구성원간의 맥락이 존재한다는 뜻이고요. 우리가 예를 들어 캐시에 값을 추가한다고 해볼게요. 캐시에 이든이라는 키로 값을 추가한다고 약속했을 때, 우리는 조앤이라는 키로 값을 조회하나요? 그렇지 않고, 약속한 이든이라는 key로 값을 조회할거예요.
마찬가지로 setAttribute를 통해서 약속한 key에 값을 저장하는 것은, request를 오인하는데에 큰 영향을 주지 않을 수 있다는 생각이긴 합니다ㅎㅎ

다방면으로 생각해보실 수 있게 의견을 드리는거라, 어느게 맞다 틀렸다는 본인이 선택해주시면 될 것 같아요!

2024-05-27 02:11 UTC, seovalue requested changes
안녕하세요 이든!
전체적으로 질문 남겨뒀는데 한번 확인 부탁드릴게요~~!
해피 월요일.. 오늘도 화이팅...

2024-05-27 02:11 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/ReservationDetail.java
> +public class ReservationDetail {
저는 계속 헷갈리는게, member_reservation과 reservation_detail을 분리한다면 reservation은 무엇인가? 라는 생각이 들어요.

member 없이 reservation_detail이 존재할 수 있나?
member 없이 reservation_detail이 존재한다고 가정했을 때, 그 예약의 상태는 어떻게 조회할 수 있나? (지금 member에 있음.)

> 회원의 예약 추가 시, 가벼운 정보만을 member_reservation에 담을 수 있었습니다.
> 데이터 저장 코드도 훨씬 가볍게 됩니다. (ex. new Reservation(member, theme, time, date, order) -> new Reservation(theme, time, date), new MemberReservation(member,reservation,order))

가벼웠을 때 어떤 이점이 있나? 등등 고민이 되는 것 같아요.. 🤔

2024-05-27 02:11 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +    List<MemberReservation> findAfterAndEqualDateReservationByMemberOrderByIdAsc(final Member member);
어차피 jpql 쓰는데 메서드 명을 좀 더 직관적으로 써보는거 어때요?

2024-05-27 02:11 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +    List<MemberReservation> findFirstOrderWaitingMemberReservationByReservationDetail(ReservationDetail reservationDetail);
다른 곳들도 JPQL 쓴다면 jpa 컬럼명을 꼭 넣어야하는 이유는 없으니 가독성있게 메서드명을 변경해주시면 좋을 것 같아요! 너무 긴 것 같아요

2024-05-27 02:11 UTC, seovalue commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        List<MemberReservation> memberReservationsOnReservationDetail = memberReservationRepository.findFirstOrderWaitingMemberReservationByReservationDetail(memberReservationToApprove.getReservation
이거 reservation 정보로 waiting 상태 중 top1만 조회해서 비교하는 건 어때요?

2024-05-27 02:11 UTC, seovalue commented on src/test/java/roomescape/theme/controller/ThemeControllerTest.java
>                  .when().get("/themes")
이제는 공통된 RestAssured 코드들을 Step으로 나눠서 네이밍해봐도 좋을 것 같아요.

```java
class ThemeSteps {
    static ... getThemes() {
        return RestAssured.given()..
    }
}
```

2024-05-27 06:16 UTC, PgmJun commented on src/main/java/roomescape/member/controller/MemberController.java
> +    @GetMapping("/admin/members")
고려하지 못했던 부분인데 너무 좋습니다!
유지보수 측면에서 크게 이점이 있을 것 같아요!

2024-05-27 06:17 UTC, PgmJun commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @GetMapping("/admin/reservations")
저는 아닌 것 같긴 하지만 조앤 말씀에 적극 동의합니다.
지금 API가 많지도 않은데 지금도 찾기 조금 헷갈린다는 느낌을 받았거든요!
그렇게 관리했을 때, 유지보수 측면에서도 훨씬 이점이 있을 것 같아요.
요번에 변경사항이 크고 많아서 클래스 분리까지는 생각하지 못했는데 짚어주셔서 너무 감사합니다:)
바로 반영해보겠습니다!

2024-05-27 06:32 UTC, PgmJun commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public MemberReservationsResponse findUnexpiredReservationByMemberId(final Long memberId) {
제가 메서드명에서 구분해줄 필요를 느낀 이유는 해당 메서드가 memberId로 회원의 모든 예약정보를 찾는게 아니라
회원의 예약정보 중, 아직 시간/날짜가 지나지 않은(Unexpired한) 예약 정보를 찾아오는 로직이기 때문이었습니다.

그런데 `Unexpired` 라는 키워드에 의해서 '날짜가 지나지 않은' 이 아니라 '검증이 된' 의 느낌으로 이해가 될 수도 있겠다고 생각이 들었습니다.
그래서 혹시 메서드 이름은 `findUnFinishedReservationByMemberId` 와 같은 느낌은 어떨까요??

2024-05-27 07:27 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +    List<MemberReservation> findFirstOrderWaitingMemberReservationByReservationDetail(ReservationDetail reservationDetail);
Repository의 메서드 네이밍은 길더라도 기능을 명시할 수 있다면 좋다고 생각했는데 그렇지 않은걸까요??
우선 더 좋은 네이밍이 있을 지 고민하고 찾아보겠습니다!

2024-05-27 07:27 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +    List<MemberReservation> findAfterAndEqualDateReservationByMemberOrderByIdAsc(final Member member);
아래 남겨주신 리뷰랑 같은 결의 리뷰네요!
마찬가지로 더 좋은 네이밍이 있을 지 고민하고 찾아보겠습니다!

2024-05-27 09:56 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/ReservationDetail.java
> +public class ReservationDetail {
중간에 테이블명이 바뀌어서 조앤에게 혼란이 있을 수도 있을 것 같다고 생각이 들어요!
다시 설명드리자면
- `reservation_detail` 은 예약 세부정보로 theme, reservationTime, date 를 가집니다.
- `member_reservation`은 회원 예약 정보로 member, reservation_detail, reservation_status(RESERVED, WAITING)을 가집니다.
- `member`는 아시다시피 회원 정보를 담고 있습니다.

---
그런데 조앤..!

제가 중간 테이블을 분리했던 가장 큰 이유는 조앤이 위쪽 리뷰에서 말씀해주셨던 것과 같이
`중간 테이블 자체로만 조회될 때 성능상의 이점`을 얻기 위해서 였습니다.

변경 이전의 테이블에는 order라는 정보를 중간테이블에서 직접 관리해주고 있었기 때문에
중간테이블 분리의 효과가 있었는데요.
하지만 order를 관리하게 되면 예약 상태 변동 시,
다른 예약 정보의 상태도 그에 맞춰 변경하기 위한 다수의 업데이트 쿼리가 발생하기 때문에 성능에 좋지 않은 영향을 미친다는 점을 인지하였고
중간 테이블에서 order를 제거하면서, 중간테이블의 효용이 거의 없어진 것 같습니다.

오히려 reservation과 member를 N:1로 관리하게 되면 단 한 번의 조인만 발생하거나, 조인이 발생하지 않아도 되지만
지금처럼 중간테이블을 두게 되면 불필요하게 JOIN만 늘어나고 성능 저하만 일으키는 등 전혀 도움이 되지 않습니다.

중간 테이블 제거 작업은 order 컬럼을 제거하면서 같이 인지하고 처리했어야 했는데 그러지 못했던 것 같아요.
계속 개발하면서 왜 이렇게 죄다 JOIN이 필요하지? 싶었는데 이 포인트를 놓쳤기 때문이었네요 ㅎㅎ..

조앤이 좋은 리뷰 남겨주셔서 이 점을 다시 인지할 수 있었네요!
시간이 조금 걸리겠지만 오늘안에 중간테이블 제거해서 다시 리뷰요청 드리겠습니다!
감사합니다:)

2024-05-30 13:30 UTC, PgmJun commented on src/test/java/roomescape/theme/controller/ThemeControllerTest.java
>                  .when().get("/themes")
그런 방법도 있겠네요...!!
테스트 고수의 길은 정말 멀고도 험한 것 같습니다..

2024-05-31 05:41 UTC, PgmJun commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public MemberReservationsResponse findUnexpiredReservationByMemberId(final Long memberId) {
제가 메서드명에서 구분해줄 필요를 느낀 이유는 해당 메서드가 memberId로 회원의 모든 예약정보를 찾는게 아니라
회원의 예약정보 중, 아직 시간/날짜가 지나지 않은(Unexpired한) 예약 정보를 찾아오는 로직이기 때문이었습니다.
(status를 사용하지는 않습니다!)

이후에 기간이 지난 예약도 조회해오는 메서드가 존재하게 된다면 구분이 어렵지 않을까? 라는 생각에 해당 네이밍을 작성해주었는데
이러한 생각 또한 메서드 명에서 추상화시켜야하는 걸까요??

만약 그게 좋을 것 같다고 생각하신다면 메서드의 동작에 대해
메서드명에 어느정도까지 표현해주어야할 지에 대한 조앤의 생각도 들려주시면 정말 감사할 것 같습니다:)

2024-05-31 06:20 UTC, PgmJun commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @GetMapping("/admin/reservations")
반영을 하면서 Controller, Package 분리까지는 적용을 하였는데
아직 DTO까지 분리할 만큼 Admin 컨트롤러가 기능이 다르지 않아서 우선은 위 두가지만 분리해두었습니다:)

2024-05-31 06:22 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/ReservationDetail.java
> +public class ReservationDetail {
조앤! 이 부분은 다음 미션에서 동일한 작업을 수행하게 되어서
혹시 위에 제 생각이 이상하지 않고 조앤만 괜찮으시다면, 다음 미션에서 저 생각을 반영해보아도 괜찮을까요??
거의 동일한 작업을 하게 될 것 같아서요..ㅎㅎ

2024-05-31 06:44 UTC, PgmJun commented
안녕하세요 조앤! 페어 프로그래밍이 시작되어서 리뷰 반영이 많이 늦어졌습니다.
죄송합니다 🥲

말씀해주신 남겨주신 부분들 최대한 생각해보고 반영해보았습니다!
특히 테스트 코드가 Fixture를 도입하면서 많이 바뀌었습니다..!
Integration테스트, Service테스트 두 대분류로 작성해두었는데 확인부탁드립니다!

## 질문있어요 👋🏻
### 인수테스트와 통합테스트의 차이
테스트를 개선하면서 지금 작성한 Controller 테스트(이번 리뷰반영에서 Integration 테스트로 네이밍이 변경되었습니다.)가 통합테스트와 인수테스트 중 무엇인지 차이를 정확히 알고 싶었습니다.

제 생각은 모든 시나리오를 RestAssured로 유저가 실제 요청하듯이 테스트 하는 것이 인수테스트
Fixture로 테스트에 필요한 모든 데이터를 조작해두고 RestAssured를 통해 특정 작업 단위를 통합적으로 테스트하는 것이 통합테스트라고 생각이 들었습니다.
이 의견에 대해서 조앤은 어떻게 생각하시는지, 그리고 현업에서는 어떻게 둘은 구분하는 지 등이 궁금합니다!
감사합니다:)

2024-06-01 01:16 UTC, seovalue commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public MemberReservationsResponse findUnexpiredReservationByMemberId(final Long memberId) {
아하! 저는 메서드는 가장 핵심적인 행위만 나타내고 별도의 필터링은 파라미터로 주는게 어떨까하는 의견이었어요ㅎㅎ
우선은 지금은 맥락상 명시적으로 나타내주는 것이 더 깔끔할 수 있을 것 같아서, 이대로 유지해도 괜찮을 것 같아요!

2024-06-01 01:17 UTC, seovalue commented on src/test/java/roomescape/theme/controller/ThemeControllerTest.java
>                  .when().get("/themes")
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ가독성 주는게 엄청 힘든 것 같아요. 가독성 준다고 줬는데 나중에 다시보니 또 아닐 수도 있고..ㅎㅎ 항상 그 순간 최선의 방법을 선택하는 걸로!

2024-06-01 01:18 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +    List<MemberReservation> findFirstOrderWaitingMemberReservationByReservationDetail(ReservationDetail reservationDetail);
아하 이거는 좀 컨벤션 문제일 수 있을 것 같은데요,
메서드의 길이가 너무 길어지면 가독성이 떨어지는 것 같아서요!

지금의 케이스를 나눈다면 
```
findFirstOrderWaitingMemberReservationByReservationDetail
->
findFirstWaitingByReservationDetail
```
이정도로 줄여보는 걸 생각했어요!

2024-06-01 01:24 UTC, seovalue approved these changes
이든. 리팩터링 해주시느라 고생 많으셨어요!
우선 남겨뒀던 코멘트는 말씀주신대로 다음번에 반영해보셔도 좋을 것 같습니다!
전체적으로 단순한 구조를 가져가는 것에 신경을 써보시면 좋을 것 같아요!
그리고 몇가지 코멘트 추가로 남겼는데 다음 미션 진행하시기 전에 한번 봐주세요~

2024-06-01 01:24 UTC, seovalue commented on src/main/java/roomescape/auth/service/AuthService.java
> +        List<Member> all = memberRepository.findAll();
없어도 되는 로직같아요?

2024-06-01 01:24 UTC, seovalue commented on src/main/java/roomescape/reservation/controller/admin/ReservationAdminController.java
> +public class ReservationAdminController {
👍 
위에 `@RequestMapping("/admin")` 로 통일해준다면 아래 들어가는 메서드들이 전부 admin 하위 api들임을 좀더 직관적으로 나타낼 수 있을 것 같아요!

2024-06-01 01:24 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/MemberReservation.java
> +        return this.member == anotherMember;
??

isMemberSame이 되어야하는거 아닌가용?

2024-06-01 01:24 UTC, seovalue commented on src/test/java/roomescape/integration/ReservationTimeIntegrationTest.java
> +                .when().delete("/admin/times/" + time.getId())
👍

2024-06-01 01:24 UTC, seovalue commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @DisplayName("예약 승인을 요청한 대기 중인 예약을 승인 시, 같은 날짜/시간/테마에 이미 예약이 있어도 가능한 것으로 판단하고 하나 더 받는다.")
대기중인 예약을 승인하면 
예약을 하나 더 받는다는 말이 어떤 의미예요??

2024-06-01 01:25 UTC, merged

2024-06-03 05:48 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/repository/MemberReservationRepository.java
> +    List<MemberReservation> findFirstOrderWaitingMemberReservationByReservationDetail(ReservationDetail reservationDetail);
저도 비슷한 형태로 줄이게 된 것 같아요! `findFirstOrderWaitingByDetail` 이렇게요!
리뷰를 반영하면서
특정 Entity에 대한 Repository이면 그 엔티티에 대한 작업을 수행한다는 당연한? 기대가 있을테니
Entity명을 꼭 명시해줄 필요는 없었는데 왜 저렇게 네이밍했을까 싶었습니다.
좋은 의견 감사합니다 조앤:)

2024-06-03 05:49 UTC, PgmJun commented on src/test/java/roomescape/theme/controller/ThemeControllerTest.java
>                  .when().get("/themes")
감사합니다..! 더 노력해볼게요!! 테스트코드 화이팅..!!!!!

2024-06-03 05:50 UTC, PgmJun commented on src/main/java/roomescape/auth/service/AuthService.java
> +        List<Member> all = memberRepository.findAll();
?!? 테스트 해본다고 찍었던 부분을 그대로 커밋해버렸네요..! 체크 감사합니다ㅠ
더 신경쓸게요!!

2024-06-03 05:52 UTC, PgmJun commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @DisplayName("예약 승인을 요청한 대기 중인 예약을 승인 시, 같은 날짜/시간/테마에 이미 예약이 있어도 가능한 것으로 판단하고 하나 더 받는다.")
서비스의 규칙 상 특정 시간에 예약을 하나만 받을 수 있지만 "관리자가 이미 예약이 있는 시간에 대한 예약 대기를 승인하는 경우 그 규칙을 무시하고 하나 더 승인한다" 라는 내용입니다..ㅎㅎ
말이 너무 어렵네요..ㅎㅎ 고쳐보겠습니다!

2024-06-03 05:57 UTC, PgmJun commented on src/main/java/roomescape/reservation/domain/MemberReservation.java
> +        return this.member == anotherMember;
바로 정정하겠습니다..
엄청 큰 실수를 해버렸네요