[3 - 4단계 방탈출 예약 대기] 폭포(이성주) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #139
Opened 2024-05-24 05:50 UTC by BurningFalls

안녕하세요 러너덕, 폭포입니다!

3 - 4단계 방탈출 예약 대기 구현 완료하여 PR 보냅니다.

리뷰 부탁드립니다. 감사합니다.

---

## API 및 DB 설계

3~4단계는 확실한 API 및 DB 명세가 정의되어 있지 않아, 자유도가 매우 높았습니다. 제가 무엇을 기반으로 설계를 했는지 알려드리기 위해 설계 Notion 링크를 첨부합니다.

[[Notion] API 및 DB 명세서](https://darkened-gaura-622.notion.site/3869e046a0bc4b04a951563653e04d87)

위 명세를 만든 이유는 다음과 같습니다.

*

2024-05-25 14:55 UTC, Deocksoo requested changes
안녕하세요 포케, 러너덕입니다.
필요한 부분들을 스스로 잘 정리하시고, 깔끔하게 구현해주셨네요 👍 
구조를 이렇게 잡은 이유들도 명확해 보이네요.
생각해보시면 좋을 만한 부분들 코멘트 남겨두었으니 확인 한 번 부탁드려요.

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/controller/AdminReservationController.java
> +    @DeleteMapping("/admin/reservations/all/{id}")
all은 왜 필요한가요?

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/domain/Reservation.java
>      public boolean equals(Object o) {
이런 euquals와 hashCode를 entity에 구현하는 것은 별로 유용하지 않은데,
엔티티에 대해서는 '같다' 에 대한 보편적인 합의를 생각하기가 어렵기 때문이에요.
id만 같으면 같은 엔티티라고 볼 수도 있고, 상태까지 모두 일치해야 동일한 엔티티라고 볼 수도 있죠.
그리고 매번 필드가 추가될 때마다 이렇게 신경써서 로직을 수정해줘야 하는 것도 번거롭죠. 
만약 어디에선가 equals나 hashCode를 쓰고 있는 로직이 있는데, 필드가 새로 추가되고 나서 equals와 hashCode를 고쳐주는 것을 깜빡하면 장애로 이어질 수도 있어요.

위와 같은 이유에서 entity에 대해서는 id를 꺼내 직접 비교하는 것을 권장해요. 이렇게 equals 와 hashCode를 따로 구현해서 쓰는 것은 지양하는 것이 좋아요.

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        return reservationRepository.findByStatus(status);
이렇게 enum으로 검색하는 경우에 추후 enum이 늘어나게 될 것을 고려하면
List<Status> 로 검색하도록 미리 만들어두는 것도 좋은 방법이에요. 

다만 지금도 동작하는데에 문제는 없겠네요.

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        Reservation reservation = findReservationById(id);
서버는 이 로직이 있건 없건 이 메서드가 수행되면 동일한 결과를 보장하죠.
개발하다보면 이런 로직들이 생각보다 꽤 귀찮아질 수 있는데,
불필요한 에러가 발생하는 경우에 프론트에서 불필요한 예외처리를 해야 할 수도 있죠.
그래서 이런 경우에는 굳이 체크하지 않는게 나을 수도 있어요.

delete 전에 find 과정이 꼭 필요한 상황이 있을까요?

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +    public Reservation addReservationWait(ReservationWaitAddRequest reservationWaitAddRequest) {
이 로직에서는 검증 순간부터 저장이 완료되기 전까지 DB 상태가 동일하다는 것이 보장되어야겠네요 :)
해결할 수 있는 방법이 있을까요?

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +    public Reservation updateReservationStatus(Long id, Status status) {
Ditto

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +    private boolean isBookedTime(List<ReservationTime> bookedTimes, ReservationTime time) {
이런 부분들이 서비스에서 도메인 로직으로 내리기 좋은 로직들이에요.
그러면 테스트하기도 쉬워지고, 재사용성도 높아지죠.

다만 저번 미션 범위였던것같기도 해서, 필요하면 리펙토링 해봐도 좋겠네요.

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        if (reservation.isStatusReservation()) {
delete 방식을 soft delete로 바꾸면 이런 로직들도 도메인의 delete 메서드 안으로 옮겨서 쉽게 테스트하고 처리할 수 있게 돼요.
다만 변경사항이 꽤 많을 수 있으니, 필요에 따라 선택하셔도 좋겠네요.

2024-05-25 14:55 UTC, Deocksoo commented on src/test/java/roomescape/domain/reservation/service/ReservationServiceTest.java
> +        assertThatThrownBy(() -> reservationService.updateReservationStatus(20L, Status.RESERVATION))
이 테스트의 TestFixture는 어디에 있나요?
겹치는 예약이 어디에서 저장되고있는지 잘 모르겠네요 :)

2024-05-25 14:55 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/domain/Status.java
> +public enum Status {
이런 일반적인 Enum 이름은 애초부터 피하는 것이 좋아요.
Status는 거의 항상 또다른 엔티티에 생기기 마련이거든요.
어떤 Status인지 이름에서 명시해주는 것은 어떤가요?

2024-05-26 07:22 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/controller/AdminReservationController.java
> +    @DeleteMapping("/admin/reservations/all/{id}")
<img width="500" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/30232837/4a5ad0e1-c33b-45b7-bb3d-083d7a2ad6b9">

2024-05-26 08:17 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/controller/AdminReservationController.java
> +    @DeleteMapping("/admin/reservations/all/{id}")
### 방법1 - endpoint로 나누기

* `DELETE reservations/{id}` -> 예약 또는 예약대기 삭제
* `DELETE reservations/wait/{id}` -> 예약대기 삭제

이렇게 하면 예약만을 삭제하는 api와 예약 또는 예약대기를 삭제하는 api가 구분이 가지 않아, 전체적인 endpoint 정의 규칙에도 어긋나고 어색합니다.

### 방법2 - 쿼리 파라미터 사용

* `DELETE /reservations{id}?type=reservation` -> 예약 또는 예약대기 삭제

일반적으로 DELETE 메서드에 쿼리 파라미터를 사용하는 경우는 **대량 삭제** 혹은 **조건부 삭제**의 경우입니다. 따라서 특정 예약 하나를 삭제하기 위해 쿼리 파라미터를 사용하는 것은, 자원의 식별자만을 이용해서 조작하는 REST 원칙에 어긋납니다.

### 방법3 - HTTP request body

Request Body에 status를 담아서 보낼 수 있지만, 이 또한 DELETE 메서드에서는 권장되지 않는 방식입니다.

2024-05-26 10:28 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/domain/Reservation.java
>      public boolean equals(Object o) {
실제로 필드를 추가할 때마다 equals나 hashCode를 변경해주어야 해서 굉장히 번거롭다고 느꼈고, 고치는 것을 깜빡했을 때의 위험성도 짐작할 수 있었습니다.

id만 같아도 같은 엔티티라고 볼 수 있는지에 대해서 합의점을 찾기 힘들기 때문에, 디폴트로 모든 상태가 일치해야 동일한 엔티티로 간주하는 equals와 hashCode를 정의하는 것은 좋지 않다는 사실을 알게 되었습니다.

다만 id를 꺼내 직접 비교하는 것을 권장한다고 말씀해주셔서, 메서드 내부에서 id가 같은지 검증하는 방식과의 차이가 궁금해졌습니다.

```java
// 메서드 내부 로직으로 id가 같은지 검증하는 방식
Entity entity1 = new Entity(1L);
Entity entity2 = new Entity(1L);
boolean isSame = entity1.hasSameId(entity2);
```

```java
// id를 꺼내 직접 비교하는 방식
Entity entity1 = new Entity(1L);
Entity entity2 = new Entity(1L(;
boolean isSame = (entity1.getId() != null && entity1.getId().equals(entity2.getId()));
```

캡슐화 관점에서 보면 내부 로직으로 처리하는 것이 더 좋아보이는데, id를 꺼내 직접 비교하는 방법의 더 큰 장점이 있는 건가요?

2024-05-26 11:51 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        return reservationRepository.findByStatus(status);
[[commit] refactor: 여러 Status를 갖는 모든 예약 조회 가능하게 하기](https://github.com/woowacourse/spring-roomescape-waiting/pull/139/commits/7a65754e969b46977702b74f2f0fc7ce3a85f2fa)

2024-05-26 12:24 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/domain/Status.java
> +public enum Status {
`XXStatus`와 같이 구분되어야 하는 경우가 생기겠네요! `ReservationStatus`로 바꾸어 이름에서 해당 Enum을 확실하게 정의했습니다.

[[commit] refactor: Status를 ReservationStatus로 명시](https://github.com/woowacourse/spring-roomescape-waiting/pull/139/commits/44128a6ab91809549ce8f3bb2bcf56e62e60f242)

2024-05-26 14:58 UTC, BurningFalls commented on src/test/java/roomescape/domain/reservation/service/ReservationServiceTest.java
> +        assertThatThrownBy(() -> reservationService.updateReservationStatus(20L, Status.RESERVATION))
해당 메서드를 봤을 때

[[commit] refactor: 겹치는 예약 객체 명시](https://github.com/woowacourse/spring-roomescape-waiting/pull/139/commits/38a7545ef42dd49414b3a2d195e98f2955a20c2b)

2024-05-26 15:51 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        if (reservation.isStatusReservation()) {
```java
// Reservation.java
public class Reservation {
  private Long id;
  // ...
  // private boolean isDeleted = false;
  // ...
  public boolean isStatusReservation() {
    return status.isReservation();
  }
  public void delete() {
    if (this.isStatusReservation()) {
      throw new IllegalArgumentException("예약은 삭제할 수 없습니다.");
    }
    this.isDeleted = true;
  }
}
```

```java
// ReservationService.java
public void removeReservationWait(Long id) {
  Reservation reservation = findReservationById(id);
  reservation.delete();
  reservationRepository.save(reservation);
}
```

2024-05-26 23:34 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +    private boolean isBookedTime(List<ReservationTime> bookedTimes, ReservationTime time) {
레벨1때 습득한 내용을 제대로 활용하지 못했었네요. 반드시 수정이 필요한 부분이라고 생각합니다! 

말씀해주신대로 코드를 수정하니, 기존에 private이었던 메서드가 public으로 바뀌면서 테스트하기 쉬워졌고, 다른 서비스에서 해당 로직을 사용할 수 있게 되어 재사용성도 높아졌다는 느낌을 받았습니다.

[[commit] refactor: 예약된 시간인지 확인하는 기능 도메인 로직으로 내리기](https://github.com/woowacourse/spring-roomescape-waiting/pull/139/commits/ff3561ea7a795e4a2201f50d26c6c443c4e73318)

2024-05-27 06:10 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        Reservation reservation = findReservationById(id);
지금 코드와 https://github.com/woowacourse/spring-roomescape-waiting/pull/139#discussion_r1615253338 에서 변형된 코드 둘다 reservation의 status가 "RESERVATION"인지 검증하는 로직이 필요해서 `findReservationById`로 reservation을 가져와야 했습니다.

만약 "예약대기"만 삭제가 가능하게 하는 작업을 프론트만으로 충분히 처리 가능하다면 status를 체크하는 로직이 필요 없을 수도 있습니다. 하지만 UI가 아닌 다른 방법으로 요청을 보내는 경우를 생각하면, status를 체크하는 로직은 필요하다고 생각됩니다.

제가 미처 생각하지 못한 이 문제를 해결할 수 있는 방법이 있는 것인가요? 궁금합니다.

2024-05-27 06:53 UTC, BurningFalls commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +    public Reservation updateReservationStatus(Long id, Status status) {
이 메서드 또한 find와 save 사이에 데이터가 변경될 가능성이 있네요! 똑같이 다음 미션에서 고민해보고자 합니다.

2024-05-27 07:02 UTC, BurningFalls commented
상세한 리뷰 감사합니다, 러너덕! 🙇 

Soft Delete와 동시성(Transaction, 잠금 메커니즘)은 더 공부해보고 개념을 적용해보고자 합니다.

크리티컬한 부분들, 더 공부가 필요한 부분들을 짚어주셔서 성장에 큰 도움이 되었습니다!

+ 포케라고 잘못 적으셨던데, 미션에 지쳐있었는데 덕분에 큰 웃음 얻어갈 수 있었습니다 😄

2024-05-28 09:32 UTC, Deocksoo approved these changes
안녕하세요 폭포, 
포케라니... 제가 저번에 거의 반 가사상태로 리뷰를 남겼나봐요, 죄송해요 🥲  그래도 큰 웃음 드렸다니 다행이네요 ㅎㅎ;

리뷰 꼼꼼하게 잘 반영해주셨네요 💯 
깊이 있게 고민하신 흔적이 잘 보여서 좋네요. 
커밋 링크도 필요한 곳에 일일이 달아주셔서 보기 편했어요 👍 

이번 미션에서 필요한 부분들은 충분히 고민해보신 것 같아서 미션 머지하도록 할게요.
가벼운 리뷰 하나 남겨두었으니, 나중에 확인 부탁드려요.

미션 진행하시느라 고생 많으셨어요 :)

2024-05-28 09:32 UTC, Deocksoo commented on src/main/java/roomescape/domain/reservation/service/ReservationService.java
> +        Reservation reservation = findReservationById(id);
상태에 따라 검증하는 로직이 필요하다면 조회를 해야할것같은데,
지금 이 로직에서는 

```java
    private Reservation findReservationById(Long id) {
        return reservationRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("해당 id를 가진 예약이 존재하지 않습니다."));
    }
```

위 메서드 하나만 거치고 있고, 조회한 reservation을 가지고 뭘 따로 하는것같지 않아서요.

사실상 아래와 같이만 처리해도 논리적으로 동일한 결과를 불필요한 예외 없이 항상 보장하지 않는가 하는 뜻이었어요.

```java
public void removeReservation(Long id) {
        reservationRepository.deleteById(id);
}
```

뭔가 제가 놓친 부분이 있나보네요. 
지엽적인 내용이니 그냥 넘어가셔도 좋겠네요 :)

2024-05-28 09:32 UTC, merged