[3 - 4단계 방탈출 예약 대기] 짱수(장혁수) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #149
Opened 2024-05-25 15:42 UTC by zangsu

안녕하세요, 제이미! 
오래 걸렸지만, 돌아왔습니다...! ㅎㅎ

이번에도 궁금한 부분을 description 과 코드의 comment 로 남겨둘게요!

## 서비스 정책

- 예약 대기는 자동으로 생성되도록 하였습니다. 
  - 늦은 예약을 예약 대기로 취급하도록 하였습니다. 
- 예약이 삭제가 되면 자동으로 남은 예약 대기 중 가장 빠른 시간의 예약 대기가 예약으로 변경됩니다. 
  - 변경 된다고 적었지만, `Reservation` 은 테이블이 분리되어 있지도 않고, 상태도 가지지 않으므로 내부적으론 아무런 변화가 없습니다.

2024-05-25 15:45 UTC, zangsu commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    );
### Spring data Jpa 라는 환경에 도메인 / 서비스 레이어의 코드가 의존하는 것은 아닐까?

저는 레벨 1에서와 같은 순수 자바 어플리케이션 (웹 X, 데이터베이스 X) 와 레벨 2에서의 웹 어플리케이션 (웹 O, 데이터베이스 O) 모두 동일한 도메인, 서비스 코드를 사용할 수 있는 것이 가장 이상적이라 생각하고 있어요. 

그런데, 지금 저의 `XXXService` 가 의존하고 있는 `XXXRepository` 는 인터페이스이지만, 사실은 구현체와 다름이 없다는 생각이 자꾸 듭니다. 메서드 명이 Spring data jpa 의 규칙에 따라 작성된 것이 가장 큰 이유 같아요. 
Jpa 를 사용하지 않는다면 저는 위의 메서드와 같이 `calculateIndexOf()` 라는 메서드를 사용하겠지만, Jpa 를 사용한다면 아래와 같이 `countByDateAndThemeAndTimeAndCreatedAtLessThanEqual()` 라는 이름을 사용하게 되겠네요.
임시로 `default` 메서드로 감싸긴 했지만 올바른 해결 방법은 아닌 것 같습니다. 

이를 해결하기 위해선 Step1-2 에서 시도했던 것 처럼 다시 새로운 Repository 레이어를 둘 수 있겠죠. 필드로 Jpa가 제공하는 인터페이스를 가지는 구현체를 만들고요. 

다음과 같은 느낌이겠네요. 
```java
interface ReservationRepository {

    Reservation save(Reservation reservation);

    //== 이하 생략 ==//
}

@Repository
class ReservationRepositoryJpaImpl implements ReservationRepository {

    @Autowired
    JpaReservationRepository jpaReservationRepository;

    @Override
    public Reservation save(Reservation reservation) {
        return jpaReservationRepository.save(reservation);
    }

    //== 이하 생략 ==//
}
```

그런데, 이렇게 구현하는 것은 현실을 무시하고 이상만 추구하는 코드라는 생각이 강하게 들어요. 
이유는 다음과 같습니다. 
1. 복잡도가 크게 증가하는 반면 얻을 수 있는 장점은 매우 작다.
2. Jpa 를 사용하는 환경에서 Jpa 를 제거하는 경우는 매우 드물 것으로 예상함.

제 생각처럼, 이정도의 환경에 대한 의존은 타협을 해야 하는 부분일까요? 아니면, 애초에 문제가 되지 않는 부분을 제가 잘못 생각해서 문제삼고 있는 것일까요?

원래라면 코드에 직접 반영을 해서 피드백을 받는 것이 좋겠지만, Files changed 가 너무 커질 것을 우려해 description 에 간단하게만 적어보았어요!

2024-05-25 15:51 UTC, zangsu commented on src/test/java/roomescape/service/FixtureUsingTest.java
> +public class FixtureUsingTest {
## 변경 사항 공유

### 동일한 Context 를 공유하는 테스트 작성하기 

이전까지 특정 환경을 여러 테스트가 공유하도록 만들기 위해 `@Nested` 를 적극 활용했습니다. 그러나, 결국 `@BeforeEach` 부분이 반복되는 것은 마찬가지였습니다. 이 때문에 도메인이 변경될 때 마다 테스트의 많은 곳을 수정해 주어야 했어요. 

그래서 기본적인 환경을 공유할 수 있는 새로운 방법으로 특정 환경이 세팅되어 있는 테스트 클래스를 상속하는 방법을 선택해 보았습니다. 

이제 부모 클래스에서는 기본적인 환경을 만들어 줍니다. 
대신, 특정 동작을 확인하기 위해 given 절이 중요한 역할을 한다면 ( "사용중인 예약 시간" 을 삭제할 수 없다 와 같이 조건이 중요한 경우) given 절을 테스트 내부에서 확인할 수 있도록 하였습니다.

2024-05-25 15:53 UTC, zangsu commented on src/main/java/roomescape/controller/AdminOnly.java
> +public @interface AdminOnly {
이전에까지는 `"/admin"` 으로 시작하는 URL 에 대해서만 관리자 권한을 검증했었는데요. URL 이 접근 권한의 여부를 나타내는 것이 어색하게 느껴졌습니다. 
그래서 관리자 권한이 필요하다는 것을 Controller 에서 나타낼 수 있도록 어노테이션을 활용해 보았습니다.

2024-05-26 10:47 UTC, jamie9504 requested changes
안녕하세요, 짱수 😄 리뷰어 제이미입니다.

잘 구현해주셨네요! 코멘트 남겨두었습니다.

오늘도 좋은 하루 보내세요~!

2024-05-26 10:47 UTC, jamie9504 commented on README.md
>  > HTTP/1.1 204
예약 취소 API도 bad case가 있지 않나요? (본인 예약이 아닌데 삭제한다던가...)

2024-05-26 10:47 UTC, jamie9504 commented on README.md
> +    - [x] 동일한 날짜와 시간, 테마에 예약 생성 요청 시 첫 번째 예약만 성공, 나머지 예약은 예약 대기
> 예약이 삭제가 되면 자동으로 남은 예약 대기 중 가장 빠른 시간의 예약 대기가 예약으로 변경됩니다.

만약 남은 예약 대기를 수동으로 예약으로 변경해야한다고 요구사항이 바뀐다면, 변경 범위는 어디까지일까요?
작업할 필요는 없고 그냥 아 어느정도 수정이 되어야겠구나 정도만 생각해봐도 좋을 것 같아요!

2024-05-26 10:47 UTC, jamie9504 commented on README.md
>      - [x] ISO 8601 표준에 따른 hh:mm 포맷에 해당하지 않는 요청 시 에러
요 부분도 한 번 확인해주세요~

1. 같은 날짜, 같은 시간에 한 명이 여러 예약/예약 대기를 걸어도 되는가? (의도한 구조인가)
<img width="981" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/59511689/1a50dcdf-a9f1-4e3f-bf20-7dd2a52350ba">

2. 예약 삭제시, 첫 번째 예약 대기가 예약이 되지만 두 번째 예약 대기는 여전히 두 번째인데 이는 의도된 바인가?
<img width="938" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/59511689/8bd48c79-68f1-4e26-b8e1-77c0cc7852a7">

3. 이 상황에서 대기 취소시 왜 500이 뜨는가!
<img width="1265" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/59511689/a92a3ae1-9ad0-4c47-bffc-667dc0c529e7">

2024-05-26 10:47 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
메서드 구조가 거의 같은 것 같은데, 하나의 delete 메서드 내에서 분기하는 것과 메서드를 아예 분리했을 때는 어떠한 차이가 있을까요?

2024-05-26 10:47 UTC, jamie9504 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +        @DisplayName("관리자는 다른 사람의 예약을 삭제할 수 없다.")
만약 이러한 요구사항이 명확하다면, `deleteWaitingByAdmin` 내부 구조를 바꿔야 할 수도 있겠네요!

현재 구현을 확인했을 때, waiting만 삭제할 수 있는 메서드인가요?

만약 해당 서비스의 메서드를 다른 개발자가 컨트롤러에서 사용해버리면 어떻게 될까요?

2024-05-26 10:47 UTC, jamie9504 commented on src/main/java/roomescape/config/AdminAuthInterceptor.java
>          if (!loginMemberRequest.role().isAdmin()) {
코드를 보다가 생각한건데요, 만약 Admin이었다가 강등된 사용자가(?) Admin일때의 토큰을 가지고 있다면 어떻게 동작하게 되나요?

2024-05-26 10:47 UTC, jamie9504 commented on src/main/java/roomescape/domain/Reservation.java
> +    @Column(nullable = false)
`@CreatedDate`, `@EnableJpaAuditing`에 대해 알아보세요!

2024-05-27 05:58 UTC, zangsu commented on README.md
>      - [x] ISO 8601 표준에 따른 hh:mm 포맷에 해당하지 않는 요청 시 에러
2번에 해당하는 내용은 서로 다른 예약에 대한 예약 대기라서 정상 동작인 것 같습니다.
14번 예약은 5/28일 (테스트 시점에서의 다음 날) 의 테마 2, 12시 시간에 대한 예약 대기입니다. 
동일한 예약으로 admin 의 12번 예약, 아서의 13번 예약이 존재하기 때문에 2번째 예약 대기로 표기 되는 것이 맞습니다!
위의 각 예약들을 제거하면 예약 대기 순번이 정상적으로 줄어들거나 에약으로 변경되는 것을 확인할 수 있습니다!

2024-05-27 06:33 UTC, zangsu commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    );
오...! Collection 이라는 친구와 JPA 라는 친구가 "내가 작성하지 않은 무언가에 대한 의존" 이라는 관점에선 상당히 유사하군요!
실제로 이번의 comment 처럼 컨버터 소스를 도입하는 방법도 고민을 해 봤고, 다른 크루의 "이럴 거면 JPA 안쓰고 JdbcTemplate 쓰고 싶다." 라는 이야기에도 공감한 적이 있어서 너무 재미있는 답변이네요 ㅎㅎㅎ

컨버터 소스를 도입해 JPA 라는 환경 자체가 없어지더라도 Service 레이어의 수정이 일어나지 않는 코드를 작성하는 것이 지극히 개인적인 저의 취향 입니다. 다만, 이전 comment 에서 적어 둔 것과 같은 이유로 굳이 도입을 하진 않을 것 같네요!

JPA 라는 환경에 의존하는 것이 너무 마음이 불편했는데, 제이미 덕분에 생각을 잘 정리해 볼 수 있었습니다 🙇 
+) 저만의 원칙을 지켜 나가는 것은 원칙에 벗어나는 코드를 작성하지 않는 것이 아니라, 원칙에 벗어나는 코드를 작성할 때 무엇을 트레이드 오프 하는지 명확하게 파악하고 선택하는 것 같네요!

2024-05-27 06:40 UTC, zangsu commented on src/main/java/roomescape/config/AdminAuthInterceptor.java
> +        HandlerMethod handlerMethod = (HandlerMethod) handler;
프리코스때 패턴 매칭을 발견하고 엄청 신기해 하고, 좋아하던 기억이 있었네요!!!
바로 반영해 보았습니다 ㅎㅎ

2024-05-27 06:44 UTC, zangsu commented on src/main/java/roomescape/config/AdminAuthInterceptor.java
> +        return false;
앗,,, 단지 신경을 쓰지 못했을 뿐입니다....ㅎㅎ
수정하였습니다.

2024-05-27 11:04 UTC, zangsu commented on README.md
> +    - [x] 동일한 날짜와 시간, 테마에 예약 생성 요청 시 첫 번째 예약만 성공, 나머지 예약은 예약 대기
지금은 예약 대기 라는 문제를 "가장 빠른 예약을 성공한 예약, 나머지 예약을 예약 대기로 취급한다" 라는 방법으로 해결하고 있는데요. 

수동으로 예약을 변경하게 된다면 가장 먼저 도메인이 변경될 것 같아요. 상태 값을 가지거나, 예약 대기 도메인이 생겨나겠네요. 도메인이 변경되면서 자연스럽게 Repository 계층이 변경될 것 같고요, Service 계층 (비즈니스 로직) 역시 변경이 되겠네요. 마지막으로 API 추가를 위해 Controller 계층도 추가될 것이고...

변경 범위가 엄청 크네요 😮 
미래의 변경에 최대한 유연하게 대응할 수 있는 코드를 작성하는 것이 중요할 것 같다는 생각이 들어요. 
다만, 항상 코드를 변경할 때 미래의 모든 변경을 고려하는 것은 어려울 것 같다는 생각도 들어요. 
제이미는 보통 변경에 대응할 때 어떤 식으로 접근하시는 편이신가요?

2024-05-27 11:16 UTC, zangsu commented on src/main/java/roomescape/config/AdminAuthInterceptor.java
>          if (!loginMemberRequest.role().isAdmin()) {
정상적인 흐름을 먼저 고민을 해 볼게요. 
토큰을 가지고 있다 라는 것은 웹 스토리지에 쿠키를 가지고 있는 상황과 동일할 것이고, 이 경우라면 쿠키를 지워주는 것으로 어느 정도 해결할 수 있을 것 같아요. 

문제는, 사용자가 쿠키 값을 어딘가 복사를 해 두고 사용하는 상황이 될 것 같은데요. 이 경우 서버에서 해당 토큰을 만료시킬 방법이 마땅히 떠오르지는 않아요. 
그나마 토큰의 만료 시간을 짧게 잡는 방법이 가능할 것 같아요. 

+) 사실, 토큰과 관련된 이야기가 나올 때 마다 드는 생각이 서버에 부하가 심하지 않은 상황이라면 세션이 훨씬 안전하지 않나... 하는 생각도 들긴 하는군요...ㅎㅎ

2024-05-27 11:47 UTC, zangsu commented on README.md
>      - [x] ISO 8601 표준에 따른 hh:mm 포맷에 해당하지 않는 요청 시 에러
3번에 해당하는 내용은... 제가 잘못된 URL 을 js 파일에서 사용하고 있었네요 🫢
수정 했습니다! 더 꼼꼼하게 테스트 하겠습니다...ㅎㅎ

2024-05-27 11:57 UTC, zangsu commented on src/main/java/roomescape/service/ReservationService.java
> +    }
지극히 개인적인 취향인데요. 
저의 `deleteByUser()` 와 `deleteWaitingByAdmin()` 는 삭제를 시도하는 흐름을 구분하기 위함이었습니다. 
관리자 권한으로 삭제를 하는 것은 특수한 상황이고, `delete()` 메서드 내에서 삭제를 하는 사람의 권한을 확인해 분기하는 것 보다 메서드 자체를 나누는 것이 가독성 또한 좋아 보이기도 했고요. 
때문에 코드의 중복이 존재하더라도 별개의 메서드를 구현했습니다.

다만, 메서드 구조와는 별개로 상위 레이어에서 단 하나만 있는 `delete()` 메서드를 사용하는 것과 `deleteByXXX()` 를 사용하는 것을 생각해 보면 전자가 조금 더 인지적 부담이 존재하지 않아 편할 것 같기도 하네요.

2024-05-28 00:57 UTC, zangsu commented on README.md
>  > HTTP/1.1 204
앗....ㅎㅎ 바로 반영 했습니다!

2024-05-29 13:27 UTC, zangsu commented on src/main/java/roomescape/domain/Reservation.java
> +    @Column(nullable = false)
알아보고 적용하느라... 시간이 꽤나 걸렸네요...!
(사실 무서워서 하루정도 미뤘...습니다...ㅎㅎ)

한번 [Baeldung - Database auditing JPA (main)](https://www.baeldung.com/database-auditing-jpa) 와 [Spring Boot Guide (sub)](https://docs.spring.io/spring-data/jpa/reference/auditing.html) 를 따라서 적용을 하고 테스트까지 만들어 보았는데요.

관련 고민이 하나 생겨 코드에 코멘트 남깁니다!

2024-05-29 13:34 UTC, zangsu commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +        assertThat(savedReservation.getCreatedAt()).isNotNull();
이 부분이 고민이 되었던 부분인데요. 
자동으로 생성된 날짜를 저장해 주는 것을 "어떻게" 확인할 수 있을까? 라는 부분이 고민이었습니다. 

처음엔 "생성된 날짜를 테스트 한다 == 저장된 시점이 잘 담겨 있다는 것을 테스트 한다" 라고 생각해서 `Reservation.createdAt` 의 값을 검증하려고 했어요. 물론 저장되는 순간의 시간을 캡쳐할 수가 없으니, 다음과 같이요..ㅋㅋ
```java
assertAll(
        () -> assertThat(savedReservation.getCreatedAt().isAfter(LocalDateTime.now())).isTrue(),
        () -> assertThat(savedReservation.getCreatedAt()).isBefore(LocalDateTime.now().minusMinutes(1))
);
```

뭔가 굉장히 짜쳐서....ㅋㅋ 옆에 있는 크루한테 물어보니 자기는 값이 들어있는지만 검증할 것 같다고 했어요. 
결국, 외부의 무언가 (라이브러리, API, 프레임워크...) 를 사용할 때는 어느 정도는 그 대상을 믿고 사용해야 한다는 결론을 내렸어요.
값이 들어있다면 정상적인 값이 들어있겠지 라는 생각에 위와 같이 테스트를 변경하였습니다. 

이런 생각의 흐름이 안전한 흐름일지, 외부에서 제공하는 값이라도 검증을 최대한 제공해 주는 것이 좋을 지 고민이네요 🤔

2024-05-30 06:05 UTC, jamie9504 approved these changes
안녕하세요, 짱수 😄 리뷰어 제이미입니다.

이번 미션 고생 많으셨습니다. 👏 👏 

코멘트는 조금만 남겨두었으니 시간되실 때 가볍게 읽어 보시면 좋을 것 같아요.
2레벨 마지막 미션 진행중인 부분도 화이팅입니다. 💪 

오늘도 좋은 하루 보내세요!

2024-05-30 06:05 UTC, merged