[3 - 4단계 방탈출 예약 대기] 알파카(최휘용) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #155
Opened 2024-05-26 06:34 UTC by slimsha2dy

안녕하세요 스티치, 알파카입니다!
페어의 코드에 기능을 추가하면서, 한 기능을 구현하더라도 일관성을 위해 익숙하지 않은 구조에 맞춰 구현하다보니 시간이 더 걸리게 되네요..ㅜ
이번 리뷰에서도 스티치의 가르침을 통해 코드와 저의 괄목할 만한 성장을 기대하고 있습니다. 잘 부탁드립니다!!
저번 리뷰에서 새롭게 남긴 의견도 확인 부탁드립니다: [링크](https://github.com/woowacourse/spring-roomescape-waiting/pull/68#discussion_r1615035805)

>예약 대기 승인
>예약 취소가 발생 시 예약 대기자가 있는 경우 예약 승인이 되는 기능을 구현하세요.
>여러가지 방법 중 하나를 선택해서 구현할 수 있습니다
>ex) 수동으로 승인하는 경우
>예약 대기 관리 페이지에서 승인 버튼을 만들어 직접 승인하게 할 수 있다.
>ex) 자동으로 승인하는 경우
>예약 취소가 발생하는 경우 예약 대기가 있을 때 우선순위에 따라 자동으로 예약이 되도록 할 수 있다

해당 요구사항에 대해, 예약 취소 시 자동으로 승인되도록 구현했습니다!

## 테스트용 계정
이름 | 이메일 | 비밀번호 | 권한
-- | -- | -- | --
John Doe | john@example.com | password123 | ADMIN
Jane Smith | jane@example.com | abc12345 | USER
Alice Lee | alice@example.com | qwerty1234 | USER

2024-05-27 03:07 UTC, lxxjn0 requested changes
알파카, 미션 구현하시느라 수고하셨습니다 :)

간단한 부분들에 대해서 피드백 남겨봤는데 한번 확인 부탁드릴게요! 추가로 이전 리뷰에 대한 코멘트도 남겨두었으니 같이 확인 부탁드릴게요.

2024-05-27 03:07 UTC, lxxjn0 commented on src/main/java/roomescape/repository/WaitingRepository.java
> +    List<WaitingWithRank> findWaitingsWithRankByMemberId(Long memberId);
서브쿼리가 아닌 다른 방식으로 해결할 수 있진 않을까요?

2024-05-27 03:07 UTC, lxxjn0 commented on src/main/java/roomescape/service/ReservationService.java
>      }
해당 메서드를 실행하다가 특정 레퍼지토리의 메서드가 실패하는 경우 어떻게 될까요?

2024-05-27 03:07 UTC, lxxjn0 commented on src/main/java/roomescape/service/WaitingService.java
> +                !Objects.equals(loginMemberRequest.role(), Role.ADMIN.getValue())) {
복잡한 조건식의 경우 어떠한 조건을 의미하는지 메서드를 통해 표현한다면 가독성을 높일 수 있습니다. 추가로 객체에 메시지를 보내는 형식으로 해결해보는 것은 어떨까요?

2024-05-27 06:50 UTC, slimsha2dy commented on src/main/java/roomescape/domain/reservation/WaitingWithRank.java
> +    private final Long rank;
생각해보니 단순히 `Waiting`과 대기 순위를 전달만 하는 객체이므로 dto로 분류하는 것이 더 적절하겠네요.
패키지를 dto로 옮겼습니다!

2024-05-27 07:10 UTC, slimsha2dy commented on src/main/java/roomescape/domain/reservation/Waiting.java
> +    private LocalTime createdAt;
당연히 `LocalDateTime`으로 해야 하는데 놓친 부분 같네요..ㅜㅜ
해당 부분 수정했습니다!

2024-05-27 11:47 UTC, slimsha2dy commented on src/main/java/roomescape/repository/WaitingRepository.java
> +    List<WaitingWithRank> findWaitingsWithRankByMemberId(Long memberId);
찾아보니 서브 쿼리는 데이터를 실제로 저장하지는 않아 성능 상 여러 문제(연산 비용, I/O 비용, 최적화 문제 등)가 발생하게 되는군요.
해당 부분을 JOIN 문으로 수정해봤습니다.

2024-05-27 11:53 UTC, slimsha2dy commented on src/main/java/roomescape/controller/api/dto/request/WaitingRequest.java
> +    }
사실 이 부분은 페어의 코드에서 유지되던 구조라 미션 구현에 집중하기 위해 굳이 바꾸지 않고 따랐던 부분입니다.
다만 제가 이해했던 바로는, 컨트롤러 단과 서비스 단 DTO 네이밍을 분리해야 하는데 요청-응답의 방향성을 반영하는 단어 중에 적절한 것을 선택했고, 서비스 단은 들어오는 요청을 서비스의 요구에 맞게 변화시켜서 받는 느낌이라 Input / Output 으로 접근했기 때문입니다.

2024-05-27 12:22 UTC, slimsha2dy commented on src/main/java/roomescape/service/ReservationService.java
>      }
생각하지 못했는데 중간에 실패하게 된다면 예약만 삭제되고 예약 대기가 승인되지 않는 상황이 발생할 수 있겠네요..
`@Transactional` 어노테이션을 추가하여 성공했을 때만 commit되고 예외가 발생할 시 rollback될 수 있도록 해보았습니다.

2024-05-28 09:01 UTC, lxxjn0 commented on src/main/java/roomescape/controller/api/dto/request/WaitingRequest.java
> +    }
해당 부분은 특별히 수정할만한 부분은 아닐 것 같아서 넘어가도록 하겠습니다!

2024-05-28 09:50 UTC, lxxjn0 approved these changes
알파카, 미션 구현하시느라 수고하셨습니다 👍🏼 

이번 미션에 대해서 추가로 구현할만한 부분에 대해서는 다 잘 마무리된 것 같아요! 추가로 피드백을 드릴 범위는 아니지만 예약이 동시에 들어오면 어떻게 처리가 될 것인지, 또 예약을 실제 DB에서 삭제하는 것이 아닌 상태만 바꾸는 소프트 딜리트에 대해서도 추가로 공부해보시면 좋을 것 같습니다 :)

미션 진행하시느라 수고 많으셨습니다.

2024-05-28 09:50 UTC, lxxjn0 commented on src/main/java/roomescape/controller/api/dto/request/LoginMemberRequest.java
> +    }
`role` 문자열에 해당하는 Role을 찾아와서 비교하는 것이 어떨까요? 또는 메시지를 해당 문자열로 보내도 좋고요.

2024-05-28 09:50 UTC, lxxjn0 commented on src/main/java/roomescape/repository/WaitingRepository.java
> +            """)
👍🏼

2024-05-28 09:50 UTC, lxxjn0 commented on src/main/java/roomescape/service/WaitingService.java
> +        return waiting.getMember().getId() != loginMemberRequest.id();
메시지를 보내서 해결할 수 있지 않을까요?

2024-05-28 09:50 UTC, merged