[방탈출 예약 대기 - 3~4단계] 아토(이혜린) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #164
Opened 2024-05-26 18:56 UTC by hyxrxn

2024-05-28 04:56 UTC, Hyeon9mak requested changes
안녕하세요 아토! 3~4단계 잘 진행해주셨어요.

이전 단계에 질문주신 내용에 대해 답변을 함께 드리고자 했는데,
제가 아토의 의중을 완벽하게 파악하지 못했어요 🙏 😢 

["코드의 양이나 효율에 차이가 없다"](https://github.com/woowacourse/spring-roomescape-waiting/pull/88#discussion_r1615186449) 에 대한 조금 더 상세한 설명을 들어볼 수 있을까요?!
그럼 저도 더 자세한 답변을 드릴 수 있을거 같아요!!

그 외에도 궁금하신 점 언제든지 질문 남겨주세요!

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/controller/response/MemberResponse.java
> +        this(member.getId(), member.getName(), member.getEmail());
오호~ 생성자 체이닝으로 변경해주셨군요 😮

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/controller/response/ReservationResponse.java
> +                new MemberResponse(member));
오! 팩터리 메서드를 제거하고 생성자를 활용하는 방향으로 결정한 이유도 궁금해요!

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        logger.info("[ERROR] ", exception);
info 로그와 warn 로그를 선택한 기준이 궁금하네요~

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
>                  HttpStatus.INTERNAL_SERVER_ERROR);
예상치 못한 오류에 대해서는 민감하게 반응하기 위한 error 로그 선택 👍

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/model/Waiting.java
> +        this(0,
dbms 에 따라 id 가 1이 아닌 0부터 시작할 수도 있을텐데요,
현재 0이 id 가 없는 초기 상태의 엔티티임을 나타내줄 수 있으면 더 좋겠네요.
0 을 상수로 분리하고 이름을 부여해보는 것은 어떨까요? 😉

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/service/WaitingService.java
> +    }
현재 reservation, time, waiting 등에서 비즈니스 관련 검증 사항들이 service 계층을 거쳐서 진행되고 있어요.
동료 개발자가 waiting 관련 비즈니스 정책을 파악하고자, 혹은 유지보수하고자 할 때
어디에 어떤 코드가 존재하는지 확인하기 위해선 `WaitingService` 100 라인을 모두 읽어봐야할 것 같아요.

저희가 객체지향 프로그래밍을 공부하는 이유는 유지보수 시점에
더 적은 코드를 읽고, 더 적은 코드를 수정하고, 더 빠른 퇴근을 하기 위함일거에요!

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/java/roomescape/service/WaitingService.java
> +    }
아토가 상상하시기에 "비즈니스 정책이 변경되었네? 관련 코드를 수정해야겠어!" 라고 하면
 service 패키지와 domain 패키지 중 어느 곳을 먼저 열어보실 것 같나요?

2024-05-28 04:56 UTC, Hyeon9mak commented on src/main/resources/static/js/reservation-mine.js
>       */
구현이 완료된 부분이라면 불필요해진 todo 주석은 제거! 😉
동료 개발자가 TODO 주석을 읽고 "추가 구현해야하나?" 궁금해할 수도 있겠어요.

2024-05-29 13:14 UTC, hyxrxn commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        logger.info("[ERROR] ", exception);
예약에서 사용하고 있는 테마와 시간을 삭제하려 할 때의 안내가 다른 예외보다 더 중요하다고 생각해 warn을 선택했는데,
생각해보니 어드민만 중요하게 알면 되는 정보인듯 하네요... 😅
변경하겠습니다

추가로 잘못된 예외 종류를 던지는 곳을 발견해 함께 수정했습니다!

2024-05-30 01:54 UTC, hyxrxn commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        logger.info("[ERROR] ", exception);
예상하지 못한 부분에서 예외가 터지는 것이 더 위험하다고 생각해 runtime과 illigalstate를 error로 설정하고,
어디서 문제가 생겼는지 명확한 커스텀 예외와 변환 중 생기는 예외는 warn으로 설정했습니다!

2024-05-30 02:03 UTC, hyxrxn commented on src/main/java/roomescape/controller/response/MemberResponse.java
> +        this(member.getId(), member.getName(), member.getEmail());
주생성자 하나를 이용하도록 정해야 원하지 않는 형태의 생성을 막기에 유리하다고 생각해 변경했습니다...!

2024-05-30 02:07 UTC, hyxrxn commented on src/main/java/roomescape/controller/response/ReservationResponse.java
> +                new MemberResponse(member));
팩터리 메서드는 메서드에서 의미있는 일을 하고 그것을 이름으로 표현하기 좋을 때 사용한다고 생각합니다.
그런데 of, from 등은 그 의도에 부합하지 않는다고 생각해 최대한 없애려고 했습니다.
저는 오히려 가독성이 떨어진다고 느껴지더라구요 🫨

2024-05-31 09:39 UTC, hyxrxn commented
### 1. Interceptor에 AuthService 의존성 존재하는 경우
#### 1. Interceptor를 Component로 등록
```
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

    private CheckAdminInterceptor checkAdminInterceptor;

    public WebMvcConfiguration(CheckAdminInterceptor checkAdminInterceptor) {
        this. checkAdminInterceptor = checkAdminInterceptor;
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(checkAdminInterceptor)
                .addPathPatterns("/admin/**");
    }
}
```
#### 2. 등록하지 않음
```
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

    private AuthService authService;

    public WebMvcConfiguration(AuthService authService) {
        this. authService = authService;
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new CheckAdminInterceptor(authService))
                .addPathPatterns("/admin/**");
    }
}
```

### 2. Interceptor에 AuthService 의존성 존재하지 않는 경우
#### 1. Interceptor를 Component로 등록
```
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

    private CheckAdminInterceptor checkAdminInterceptor;

    public WebMvcConfiguration(CheckAdminInterceptor checkAdminInterceptor) {
        this. checkAdminInterceptor = checkAdminInterceptor;
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(checkAdminInterceptor)
                .addPathPatterns("/admin/**");
    }
}
```
#### 2. 등록하지 않음
```
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new CheckAdminInterceptor())
                .addPathPatterns("/admin/**");
    }
}
```
저는 AuthService에 대한 의존성이 존재했던 첫 코드에 대해 설명했습니다.
제가 작성했던 코드는 아니지만 왜 WebMvcConfiguration에서 생성하지 않고 컴포넌트를 붙였을지 추측해본거죠!
Interceptor를 빈으로 등록하지 않아도 WebMvcConfiguration에 AuthService의 의존성 주입이 필요하기 때문에
1-1과 1-2를 비교하면 길이에 큰 차이가 없습니다. 오히려 제 눈엔 1-2가 더 가독성이 좋다고 느껴지고요.
빈으로 하나 더 등록하는 것이 효율에서 큰 손해도 아니라고 생각했습니다.

그런데 의존성이 존재하지 않으면 차이가 납니다.
2-1과 2-2를 비교하면, 2-2가 필드와 생성자가 모두 필요하지 않기 때문에 확연히 짧습니다.
그러면 이 때는 코드 길이로 보나, 빈으로 등록한 개수로 보나 아래 경우가 훨씬 낫다고 생각합니다.

그런데 의존성이 존재했을 때(1-1, 1-2의 경우) 컴포넌트를 붙인 이유를 물어보셔서 그 때는 코드 길이나 효율이 큰 차이가 없다고 생각한다고 답변드린 것입니다. 별 차이가 없길래 어떤 선택을 해도 상관 없지 않을까 추측한 거구요!
그리고 혹시 제가 모르는 차이가 있어서 물어보신 것인지 궁금해서 질문 드렸습니다.
설명이 좀 더 필요할까요?

2024-05-31 09:40 UTC, hyxrxn commented on src/main/java/roomescape/service/WaitingService.java
> +    }
가장 무거운 waiting/reservation 저장 부분을 분리해보았습니다.
한 번 보시고 피드백 주시면 감사하겠습니다~

2024-06-01 13:42 UTC, Hyeon9mak requested changes
안녕하세요 아토~!! 리팩터링 잘해주셨어요!!! 👍 👍 

### interceptor 에 authservice 의존성이 존재하는 이유

오... 첨부해주신 코드를 읽고나서 '아...!' 하고 느꼈어요!!
자체 주입을 통해 코드 라인수를 줄이는 효과도 있긴하지만,
아토 말씀처럼 코드상 몇 줄 차이가 나지 않는데, 편의를 위해 사용하는 famework 를 사용하는 입장에서
굳이 famework 가 제공해주는 편의를 이용하지 않을 이유가 없죠!!
(spring ioc 를 이용하는 가장 근본적인 이유기도 하겠네요!!)

개인적으로 더 고민해본 점은,
bean 주입을 이용하면 테스트 코드를 작성할 때도 spring bean 으로 등록되어 있으면
autowired 를 이용해서 언제든지 bean 을 가져올 수 있으므로,
테스트 코드를 작성할 때도 편의를 느낄 수 있겠다고 생각했어요 👍 

흐흐.. 아토가 적극적으로 답변주신 덕분에 저도 동기들과 여러가지 논의를 나누면서 많이 배웠어요! 👍 
귀찮으셨을텐데 정성껏 답변해주셔서 감사해요 🙇‍♂️ 저도 많은 생각을 하게 되었습니다.

리뷰 내용과 리팩터링을 잘 진행해주셔서 approve 를 앞두고 있는데요!
혹시 추가로 궁금하신 점이 있으실까 마지막 request chages 남깁니다!
추가로 얼마든지 궁금하신 점 편하게 질문 남겨주세요!

2024-06-14 09:33 UTC, merged