[1 - 2단계 방탈출 예약 대기] 메이슨(김경원) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #45
Opened 2024-05-15 12:22 UTC by masonkimseoul

안녕하세요 안돌! 메이슨입니다.

이번 미션은 제 페어인 리비의 코드로 진행하였습니다.
코드의 변경사항은 다음과 같습니다. [변경사항](https://github.com/woowacourse/spring-roomescape-waiting/pull/45/files/9b5f9a2ec38996287422b3df01451bc6a8d1219b..f2eb4ebc76a6771920f6a602ad873810a584a827)

## 이전의 웹 개발 경험
- Spring Boot와 JPA를 활용해 간단한 서비스를 배포해본 적이 있습니다. 다만 짧은 시간 안에 구현을 마무리해야 해서 작동 원리에 대한 학습이 미흡합니다.

## 테스트용 계정

| 이름  | 이메일              | 비밀번호 | 권한   |
|-----|------------------|------|------|
| 안돌  | andole@test.com  | 123  | MEMBER |
| 파랑  | parang@test.com  | 123  | MEMBER |
| 리비  | libienz@test.com | 123  | MEMBER |
| 메이슨 | mason@test.com   | 123  | MEMBER |
| 어드민 | admin@test.com   | 123  | ADMIN |

## 질문사항
JDBC에서 JPA로 변환하는 과정에서 쿼리 크리에이션을 사용하여 Repository를 구성하였습니다.
메서드명을 보고 쿼리를 만들어주는 점이 좋지만, 특정 메서드의 경우 메서드명이 너무 많이 길어집니다.
```java
List<Reservation> findByMember_IdAndTheme_IdAndDateValueBetween(Long memberId, Long themeId, LocalDate dateFrom, LocalDate dateTo);
boolean existsByDateValueAndTime_IdAndTheme_Id(LocalDate date, Long timeId, Long themeId);
```
이렇게 메서드명만 보고 쿼리를 만들어주는 기능은 편하지만 가독성이 나빠지는 것 같습니다.
이런 식으로 메서드의 가독성이 나빠지면 `@Query` 어노테이션을 사용하는 것과 같이 다른 방법을 쓰는 것이 맞는지 궁금합니다.
또한 안돌의 경우 쿼리 크리에이션에 대해 어떤 기준을 가지고 사용하시는지 여쭤보고 싶습니다!

미숙한 코드를 읽어주셔서 감사합니다. 이번 미션 잘 부탁드립니다! 🙇‍♂️

2024-05-16 03:22 UTC, andole98 requested changes
별로 이야기할 거리가 없을 정도로 상당히 잘 구현해주셨네요 :open_mouth:

적절히 책임을 부여하고 나누어주었어요. 계층별 슬라이스 테스트도 적절하게 잘 작성해주신것 같아요. 

인수테스트 or e2e테스트도 한번 작성해보시길 제안해봅니다.

소소한 코멘트 남겼습니다. 의견 남기고 알려주세요.

2024-05-16 03:33 UTC, andole98 commented
> 메서드명만 보고 쿼리를 만들어주는 기능은 편하지만 가독성이 나빠지는 것 같습니다.

spring data에서 이걸 query method라고 부릅니다. 쿼리메서드의 이점은 간편하게 쿼리를 만들수 있고, spring data가 지원하는 모든 data-storage를 커버할 수 있다는 점이에요. 
현재 프로젝트는 rdb h2를 사용하고 있어요. 만약 mongoDB나 redis같은 data warehouse를 변경한다면, query method는 그대로 동작합니다 (일부 구현에 의존적인 것은 어쩔수 없고요)

단점도 존재해요. 이야기한것처럼 지나치게 길어지는 경우도 있죠. 이런 경우 `@Query`나 native 쿼리 등을 이용하기도 합니다.

다만, 저는 약간 생각이 다른데요. 쿼리가 지나치게 복잡하다면 쿼리로 해결할 문제가 아니라고 생각하는것 같아요. `어떤 data 구조가 현재 기능에 잘 맞지 않으니 쿼리가 복잡해지는것 아닐까` 로 생각하는 것 같네요.

2024-05-19 09:46 UTC, masonkimseoul commented on build.gradle
> +    implementation 'javax.xml.bind:jaxb-api:2.3.1'
지난 미션에서 사용했던 코드를 rebase 하는 과정에서 들어온 것 같습니다.

```
implementation 'io.jsonwebtoken:jjwt-api:0.11.2'
implementation 'io.jsonwebtoken:jjwt-impl:0.11.2'
implementation 'io.jsonwebtoken:jjwt-gson:0.11.2'
````
이번 미션에서 주어진 라이브러리는 위와 같은데요, 제가 사용했던 `io.jsonwebtoken:jjwt:0.9.1`, `javax.xml.bind:jaxb-api:2.3.1`과 어떻게 다른지 찾아보았습니다.

`io.jsonwebtoken:jjwt`은 0.10.0 버전부터 모듈화되어 필요한 부분만 가져와 사용할 수 있습니다.
모듈 중 하나인 `jjwt-api`는 JWT 생성, 검증 등의 처리에 사용되는 인터페이스, 추상클래스가 포함되어 있습니다.
`jjwt-impl`은 직접 참조되지는 않지만 `jjwt-api`의 구현체를 가지고 있으며 내부적으로 사용합니다.
`jjwt-gson`은 Gson을 사용하여 JWT의 페이로드를 JSON 형식으로 직렬화, 역직렬화 하는 기능을 포함합니다.

`javax.xml.bind:jaxb-api:2.3.1`은 XML을 java 객체로 변환해주는 api를 제공합니다.
![image](https://github.com/woowacourse/spring-roomescape-waiting/assets/87306418/0c62b84b-7fa1-4db0-8554-03176135a8a5)
jjwt-impl 내부에서 토큰을 Base64로 encode/decode할 때, javax.xml.bind.DatatypeConverter 객체를 사용하고 있습니다. 이 객체를 사용하기 위해 `jaxb-api`를 추가했던 것으로 보입니다.

또한 `jjwt-api`와 `jjwt-impl`의 버전 변경에 따라 해당 라이브러리를 사용하는 클래스의 코드도 일부 변경하였습니다!

2024-05-19 09:59 UTC, masonkimseoul commented on src/main/java/roomescape/auth/service/AuthService.java
> +        if (!findMember.getPassword().equals(loginRequest.password())) {
Member의 메서드로 isSamePassword를 구현하여 수정하였습니다. 감사합니다!

2024-05-19 12:47 UTC, masonkimseoul commented on src/main/java/roomescape/reservation/domain/ReservationRepository.java
> +    List<Reservation> findByMember_IdAndTheme_IdAndDateValueBetween(Long memberId, Long themeId,
처음 구현할 때 `_`가 없어도 가능할거라고 생각했는데, `Could not resolve attribute 'memberId' of 'roomescape.reservation.domain.Reservation'`과 같은 에러가 계속 발생해 `_`를 부득이하게 붙였었습니다.

에러 원인은 `Member`, `ReseravtionTime`, `Theme`의 id를 `Reservation` 내부에서 `getXxxId`와 같이 사용하는 것에 있었습니다. `Reservation` 엔티티 내부에 `getXxxId` 메서드가 존재함으로 인해, `XxxId` 필드를 찾으려 시도하기 때문에 오류가 발생하였습니다.

사소하지만 잘 보이지 않아 시간을 많이 소모한 것 같습니다 🥲

2024-05-19 12:59 UTC, masonkimseoul commented on src/main/java/roomescape/member/domain/Member.java
> +    @Column(nullable = false)
`@Column` 내에 `length`를 추가하도록 수정하였습니다. 감사합니다!

2024-05-19 13:04 UTC, masonkimseoul commented on src/main/java/roomescape/theme/domain/ThemeRepository.java
> +    List<Theme> findTopByDurationAndCount(LocalDate start, LocalDate end, Pageable pageable);
감사합니다 ㅎㅎ 지난 미션에서 페이지네이션에 대해 학습한 내용을 적용해보았습니다.

2024-05-20 07:24 UTC, masonkimseoul commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    @ManyToOne(fetch = FetchType.LAZY)
구현 당시 연관 관계에서 `LAZY` 설정의 지연로딩을 통해 불필요한 쿼리가 발생하는 문제를 예방하려고 하였습니다. 규모가 크지 않아 `EAGER`로 설정하여도 결과가 크게 달라지지 않겠지만, 프록시 객체 사용으로 `@ManyToOne`에서의 성능 향상을 조금이나마 얻으려고 설정해보았습니다.

코멘트를 받고 발생하는 쿼리를 다시 확인해봤습니다. find 쿼리에서 Reservation은 Member, Theme, ReservationTime을 모두 필요로 하기 때문에 EAGER로 설정해도 쿼리가 같게 만들어지네요. 그런데 `findAllByMemberId` 메서드에 한해서 불필요한 member 조회 쿼리가 EAGER일 때 발생하는 것을 확인하였습니다.

### FetchType.LAZY일 때 findAllByMemberId
```sql
Hibernate: select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id from reservation r1_0 left join member m1_0 on m1_0.id=r1_0.member_id where m1_0.id=?
Hibernate: select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
```

### FetchType.EAGER일 때 findAllByMemberId
```sql
Hibernate: select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id from reservation r1_0 left join member m1_0 on m1_0.id=r1_0.member_id where m1_0.id=?
Hibernate: select m1_0.id,m1_0.email,m1_0.name,m1_0.password,m1_0.role from member m1_0 where m1_0.id=?
Hibernate: select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
```

EAGER일 때 Reservation에 쓰이는 Member도 함께 가져와야해서,  Member에 대한 쿼리가 추가적으로 발생합니다. 다만 Reservation 개수와 관계없이 Member는 1개만 필요하기에 큰 부담은 없을 것 같습니다.

현재 코드에 있어서 EAGER와 LAZY 옵션을 선택하는데엔 큰 차이가 없습니다만, 앞으로의 학습을 위해 LAZY로 설정해보도록 하겠습니다!

2024-05-20 10:29 UTC, masonkimseoul commented
안녕하세요 안돌!
트러블슈팅과 테스트 코드 작성이 길어져서 리뷰 반영이 늦었습니다.
다음 단계에선 조금 더 빠르고 확실하게 진행해보도록 하겠습니다.
감사합니다!

2024-05-20 11:21 UTC, andole98 commented on src/main/java/roomescape/auth/dto/LoginRequest.java
> +        @Size(max = 320, message = "이메일의 길이를 다시 확인해주세요")
entity에 length를 주면서 여기에도 제한을 추가했군요. 꼼꼼하네요 :+1:

2024-05-20 11:29 UTC, andole98 approved these changes
잘 구현해 주셨네요~ 꼼꼼하게 코딩하는걸로 느껴져요.

소소한 코멘트 남겼으니 다음 스텝 진행하며 시간날때 확인해주세요.

2024-05-20 11:29 UTC, andole98 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
기본 생성자가 필요한 이유는 무엇인가요?

2024-05-20 11:29 UTC, andole98 commented on src/test/java/roomescape/reservation/presentation/ReservationControllerE2ETest.java
> +    @TestFactory
매우 좋은 dynamicTest 예시네요 👍

2024-05-20 11:29 UTC, andole98 commented on src/test/java/roomescape/reservation/presentation/ReservationControllerE2ETest.java
> +    Stream<DynamicTest> checkReservationDate() {
다만 이것과 아래 test suit가 하나뿐인 dynamic test들은 굳이? 느낌이 드네요

2024-05-20 11:29 UTC, merged

2024-05-24 04:37 UTC, masonkimseoul commented on src/test/java/roomescape/reservation/presentation/ReservationControllerE2ETest.java
> +    Stream<DynamicTest> checkReservationDate() {
불필요한 테스트를 지우다가 미처 수정하지 못한 것 같습니다 😅 3-4단계를 진행하면서 수정하도록 하였습니다!

2024-06-03 13:50 UTC, masonkimseoul commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
JPA에서 객체(엔티티)를 생성할 때 어떤 타입으로 생성할 지 알 수 없으므로, Reflection을 사용해 동적으로 객체를 생성합니다.
이때 매개변수가 없는 생성자(기본 생성자)가 필요합니다.
객체를 생성할 때 Reflection만으로는 생성자의 매개변수를 받아올 수 없기 때문에, 기본 생성자를 통해 객체를 먼저 생성한 뒤 필요한 필드 값을 매핑해줍니다.
따라서 모든 엔티티에 기본 생성자를 작성할 수 있도록 하였습니다!