[1 - 2단계 방탈출 예약 대기] 도도(김도선) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #55
Opened 2024-05-16 02:40 UTC by ehtjsv2

안녕하세요 수달!

이번 미션 잘부탁드립니다!

**[사용가능한 아이디]**
* admin@gmail.com, 123456 -> admin
* dodo@gmail.com, 123123 -> member

## 스프링 경험
프로젝트를 해본적은 있지만, 그저 복사 붙여넣기 하기 바빴던 프로젝트였습니다!
처음해본다고 생각하고 배울생각입니다!

2024-05-16 16:04 UTC, her0807 requested changes
안녕하세요 도도 

리뷰어 수달입니다!ㅎㅎ
충분히 잘 구현해 주셨어요. 
특히 고전파 식으로 테스트를 작성해주신게 인상 깊네요. 
JPA 는 이번기회에 함께 공부해봐요!
간단한 코멘트 남겨두었습니다.  즐거운 리뷰 기대할게요 🙇🏻‍♀️

2024-05-16 16:04 UTC, her0807 commented on src/main/java/roomescape/domain/member/repository/MemberRepositoryImpl.java
> +    }
JpaMemberRepository 자체로도 인터페이스인데 이것을 한번더 추상화해서 얻는 이점이 있나요?

2024-05-16 16:04 UTC, her0807 commented on src/main/java/roomescape/domain/member/service/MemberService.java
> +
데이터가 무조건 존재해야할 때는 Get, 없을 수도 있을 때는 find 라고 관례적으로 네이밍 하는 것 같습니다.

2024-05-16 16:04 UTC, her0807 commented on src/main/java/roomescape/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new EscapeApplicationException("이메일 또는 비밀번호를 잘못 입력했습니다."));
예외 메세지를 따로 관리해볼까요?

2024-05-16 16:04 UTC, her0807 commented on src/test/java/roomescape/domain/member/service/FakeMemberRepository.java
> +public class FakeMemberRepository implements MemberRepository {
오 도도 고전파 테스트를 작성해주시는군요~

페이크 객체로 테스트를 진행하시면서 어떤 장단점이 있으셨나요?

2024-05-16 23:33 UTC, her0807 requested changes
헉 어제 새벽에 보낸걸 깜빡하고 다시 요청했네요 😅🙏

2024-05-17 07:26 UTC, ehtjsv2 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
명확하게는 알고있지는 않아서 공유해주신 글 읽어보았습니다!

현재 미션에서는 h2를 인메모리 모드로 사용중이라, update를 해도 create한 것과 같은 효과더라구요!

그래서 이번 미션은 임베디드 모드로 하고 db를 어플리케이션 종료해도 유지되는 방향으로하고 옵션을 create, create-drop말고 다른 것으로 하면서 해보겠습니다

이렇게하면 수달의 컴퓨터에도 db파일이 생길거같은데,, 인메모리모드 또한 주석으로 남겨두겠습니다! (혹시 모르니, 파일이름은 wooteco-dodo-h2-db로 했습니다)

라고 할려고 했으나,, 임베디드모드를 사용하니 data.sql을 인식못하거나 실행할때마다 계속 추가되는 오류가 있어서, 공부만 해보고 다시 인메모리로 변경했습니다!

2024-05-17 08:25 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/member/domain/Member.java
> +    private Role role;
실제로 어플리케이션 실행하고 데이터 넣을 때, 에러가 나서 이후 커밋에서 적용했었습니다!
어노테이션을 제거 하니 테이블 생성 시``` role tinyint check (role between 0 and 2),``` 로 선언이 되더라구요!
좋은 정보 감사합니다!

2024-05-18 06:57 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/reservation/repository/ReservationRepository.java
> +    List<Reservation> findByMember_Id(Long memberId);
이부분은 JPA를 상속받은 클래스로 JPA Query Method를 위해 만들어진 메서드입니다!
처음에는 카멜케이스로 했으나 오류가 떴습니다. 
검색해보니 해당테이블의 ID를 참조하는 메서드는 스네이크케이스로 하니 된다고 하더군요.
찜찜했으나, 일단 스네이크케이스로 해서 해결했습니다!

후에 알아보니, Reservation 클래스의 getMemberId()메서드가 문제가 되고 있다는 것을 알게 됐습니다.
getMemberId를 삭제하고 카멜케이스로 변경하니 해결됐습니다!
정확히 Query Method가 생성되는 과정을 알면 왜 문제인지 알 수 있을 것도 같은데, 알아보아도 알기 쉽지않더라구요,, 

일단 문제되는 getter삭제후 모두 카멜케이스로 변경했습니다!

2024-05-18 07:03 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/member/repository/MemberRepositoryImpl.java
> +    }
Fake Repository 사용을 위해 이렇게 만들었습니다!

한번 더 추상화 하지않고 JpaRepository를 상속받은 JpaMemberRepository를 구현한 FakeMemberRepository를 만들기위해서는 JpaRepository위 모든 메서드를 구현해주어야합니다.

FakeMemberRepository가 구현해야하는 메서드의 범위를 실제 필요한 메서드만으로 좁혀주기 위해서 한번 더 추상화했습니다!

2024-05-18 07:09 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/member/service/MemberService.java
> +
이 메서드는 존재하지 않으면 예외를 발생시키니까, 무조건 존재한다고 생각하고 호출하는 메서드이니 get이 맞는  표현일 수 있겠네요!

2024-05-18 08:31 UTC, ehtjsv2 commented on src/test/java/roomescape/domain/member/service/FakeMemberRepository.java
> +public class FakeMemberRepository implements MemberRepository {
2레벨 첫 미션에서 페이크 객체와 모킹에 대해서 궁금증이 생겨 두가지 모두 적용했었습니다! 그때 생각한 두 기술의 장단점을 적어보겠습니다!

### Fake Object
* 장점
  * 테스트 하려는 메서드의 내부 구현을 잘 몰라도 된다. 
* 단점
  * 의존하는 클래스의 내부 상태에 의존적이다. (초기값을 지정해주어야됨) 
  * 복잡한 구현의 메서드를 fake로 구현하는데 비용이 크다.
### Mock
* 장점
  * 의존하는 클래스의 메서드 구현이 어찌되었든, 원하는 반환값만 지정해주면 되기 때문에 편하다.
* 단점
  * 테스트하려는 메서드의 구현을 잘 알아야한다.

2024-05-18 08:40 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new EscapeApplicationException("이메일 또는 비밀번호를 잘못 입력했습니다."));
이 부분은 따로 예외 메세지를 따로 관리했을 때의 이점을 잘 모르겠습니다!
"이메일 또는 비밀번호를 잘못 입력했습니다" 라는 메세지는 여기서만 사용되고, 따로 분리 했을 때 오히려 구조가 복잡해지는 것은 아닐까 라는 생각이 듭니다!
수달은 왜 따로 관리하는 것을 추천했는지 알 수 있을까요?

2024-05-19 01:48 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/member/domain/Member.java
> +    private String password;
컬럼 제약 사항 추가해줬습니다! 길이를 꼭 제한을 둬야하나? 싶은 것들은 Length를 default로 두기로 했습니다!
제약 사항 추가에 따라, 어플리케이션 내에서도 validate를 추가해야되는 상황이 되었습니다. (db로 가기전에, 먼저 검증해서 예외를 발생시키기 위해)
entity 클래스에서 모두하기에는 과한 책임인 것 같아서 원시타입을 VO로 변경하고 각자가 검증하도록 변경했습니다!

2024-05-19 01:56 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/reservation/domain/reservation/Reservation.java
> +    private Member member;
* FetchType.EAGER
  *  조회시, 연관관계가 있는 테이블의 row까지 모두 조회합니다.
* FetchType.LAZY
  * 조회시, 연관관계가 있는 테이블의 객체는 프록시 객체로 저장되어있다가, 실제로 필요한 시점에 쿼리문이 실행된다.
 
공부과정에서 아래와 같은 의문이 들었습니다
  ### 그러면 무조건 LAZY가 좋지 않은가??
* 그렇다고 하기에는 EAGER는 한번에 쿼리를 날려서 데이터를 가져오는 반면, LAZY는 상황에 따라 여러번 쿼리를 날려야한다.
* DB에 접근하는 비용도 존재하기 때문에, 자주 같이 쓰이는 테이블이라면  EAGER가 좋다. 

---
```  
 @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "member_id")
```
로 되어 있을 경우 reservation테이블에 member_id 외래키를 갖고 있게 됩니다!

2024-05-19 02:11 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/reservation/repository/ReservationRepository.java
>      List<Theme> findThemeOrderByReservationCount();
페이징이라는 기술이 있는 지 처음 알았습니다! 정말 유용한 기술이네요!

공부해보니 페이징 기술은 대규모 결과세트에서 모든 결과를 반환하기 보다는 페이지번호와 페이지 크기에 따라 조절하여 결과를 불러올 수 있도록 나온 것 같습니다!

현재의 메소드는 인기테마를 불러오는 메소드로, 테마라는 데이터와 인기테마라는 개념이 대규모 결과를 불러올 것 같지않고 페이지도 구분될 것 같지 않아 현재 상황에서는 사용하지 않아도 될 것 같습니다!!

오히려 reservation의 findAll같은 곳에 적용한다면 효율적일 것 같습니다!

좋은 정보 감사합니다!

2024-05-19 02:33 UTC, ehtjsv2 commented on src/main/java/roomescape/domain/member/domain/Member.java
>      private Long id;
JPA에서의 ID 생성 전략은 총 5가지가 있습니다
1. IDENTITY - 기본 키 생성을 데이터베이스에게 위임한다. (그렇기 때문에 기본 키를 알려면 꼭 DB를 거쳐야한다. -> insert의 지연쓰기 불가)
2. SEQUENCE - 데이터베이스 시퀀스를 사용해서 ID를 생성한다 (여러 방면으로 검색해서 찾아봤는데, 솔직히 이해가 잘안되네요,,평일에 크루들이랑 이야기하며 알아보겠습니다!)
3. TABLE - 키 생성 전용 테이블을 생성하여 데이터베이스 시퀀스를 흉내내어 ID를 생성한다.
4. AUTO - ID필드의 타입과 사용하는 데이터베이스에 따라 전략을 알아서 정해준다.
5. UUID - UUID를 사용하는 방법(순서보장X)

JPA를 적용하기 전 AUTO_INCREMENT를 그대로 유지하기 위해 IDENTITY를 사용했습니다.

2024-05-19 02:39 UTC, ehtjsv2 commented
안녕하세요 수달!! 생각보다 리뷰요청을 늦게 보내게 됐네요!

큰 변경사항은 VO를 적용했다는 점인 것 같습니다!

잘부탁드립니다!

2024-05-20 06:34 UTC, her0807 commented on src/main/java/roomescape/domain/reservation/domain/reservation/Reservation.java
> +    private Member member;
EAGER 로 가져올 때도 단건으로 여러번 쿼리가 나가는 것을 방지하기 위해서 패치 조인을 하거나 배치 사이즈를 설정하여 사용하기도 합니다!

2024-05-20 06:42 UTC, her0807 commented on src/main/java/roomescape/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new EscapeApplicationException("이메일 또는 비밀번호를 잘못 입력했습니다."));
음 저는 테스트에서 메세지도 함께 검증하는 편인데요~
해당 메서드를 상수로 관리하게 되면  비지니스 로직에서 테스트 메세지 변경이 테스트에도 전파되어서 유지보수하기 용이하다고 생각해요. 생각보다 이런 누락으로 테스트가 깨지는 경우가 많이 발생하거든요!

2024-05-20 06:48 UTC, her0807 approved these changes
안녕하세요 도도 ~

커스텀 예외가 추가되고  VO 로 도메인 내부가 깔끔해졌네요.
학습 한 내용 코멘트로 알려주셔서 감사해요.
jpa 에서 쿼리 작성시 꼬였던 부분은 저도 한번 찾아볼게요! 

다음 단계 진행하면서 더 자세히 학습해보시죠!
고생 많으셨습니다.

2024-05-20 06:48 UTC, merged