[1 - 2단계 방탈출 예약 대기] 포케(이무송) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #67
Opened 2024-05-16 06:44 UTC by fromitive

안녕하세요 오리🐤 처음뵙겠습니다 포케입니다 😄 

SpringBoot경험은 우테코가 처음이라고 생각해주시면 되고, 미션을 수행하면서 자기만의 학습 방식을 찾고 있습니다. 🔥 

코드를 작성하면서 고민되거나 궁금한 부분들은 별도로 코멘트 남기도록 하겠습니다 😃 

**브라우저에서 테스트를 하기 위해선 계정정보가 필요합니다** 각 권한 별 계정정보는 아래와 같습니다.

**[관리자 계정]**
id : `admin@email.com`
pw: `admin`

**[일반 사용자 계정]**
id: `user@email.com`
pw: `user`

이번 3단계 미션 잘 부탁드립니다 🙇 감사합니다!

2024-05-16 07:31 UTC, fromitive commented on src/main/java/roomescape/config/deserializer/LocalDateDeserializerWithValidation.java
> +public class LocalDateDeserializerWithValidation extends JsonDeserializer<LocalDate> {
역직렬화를 할 때 `LocaDate`와 `LocalTime`에 잘못된 값( 예: 날짜 포맷은 맞는데 값이 이상한 경우 : 1111-99-88 )에 대한 유효성 검사를 하기 위해 Deserializer를 사용하게 되었습니다.

다른 크루들에게 의견을 들었을 때, Controller에서 `String`으로 받은 뒤, 도메인 객체 생성 시 검증하도록 구성하는 방법도 존재함을 알게되었습니다.

보통 날짜와 시간데이터를 처리할 때 request부분을 시간 관련 객체를 사용하지 않고 문자열을 받은 뒤 처리하는 편인지 궁금합니다!  😄

2024-05-16 07:36 UTC, fromitive commented on src/main/java/roomescape/controller/admin/AdminReservationController.java
> +@RequestMapping("/admin")
`RequestMapping`값이 다른 `Controller`와 일관성이 없네요 ㅎㅎ; 이부분은 바로 수정하겠습니다!!

2024-05-16 07:40 UTC, fromitive commented on src/main/java/roomescape/domain/dto/BookResponse.java
> +public record BookResponse(LocalTime startAt, Long timeId, Boolean alreadyBooked) {
Response에 대한 dto는 DB에서 가져온 Entity를 바탕으로 생성하는데, 유효성 검사가 필요한지 감이 잡히지 않습니다. 언제 Response에 대해서 유효성 검사가 필요한지 궁금합니다 😃

2024-05-16 08:04 UTC, fromitive commented on src/main/java/roomescape/domain/dto/ReservationsMineResponse.java
> +    public static ReservationsMineResponse from(Reservation reservation) {
이 Response 객체만 `XXXResponses`로 Wrapping하지 않았습니다. 😅 
이 부분은 우선적으로 페어랑 짜면서 미션 API양식대로 구현을 했습니다. 
일관성 유지를 위해 Responses로 Wrapping을 하려고 하는데 개인적으로 궁금한 점이 생겨 여쭈어봅니다. 😃 

Responses로 Wrapping을 하는 이유는 아래와 같이 Array보다, Object로 전달할 때 필드에 대한 확장성이 좋아지는 장점이 있다 생각합니다. 

``` 
{
	data : [ ... ] // array Response
	// 아래와 같은 데이터를 넣기 수월해짐
	total : 000 
}
```

단점으로는 변경 시 프론트페이지의 Array로 받는 것들을 전부 변경해야 했습니다. 🥲
계속 API 양식을 바꾸게 되면 잘되던 서비스가 안될 수 있는 상황이 존재 할 것 같은데요. 이처럼 현업에서는 API 요청 양식이 변경될 수 있는 상황이 자주 있는지 궁금합니다!

2024-05-16 09:07 UTC, jinyoungchoi95 requested changes
안녕하세요 포케 😄

방탈출 예약 대기 미션의 리뷰어를 맡은 오리입니다.

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    protected Reservation() {
👍 

jpa는 왜 기본 생성자를 고정스펙으로 두는 걸까요?

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    private LocalDate date;
`@Column`을 명시하지 않아도 동일한 네임의 컬럼일 경우 매핑이 되기는하지만, 테이블 정보를 `@Entity`에 명시하기도 해요. 테이블을 굳이 한번 더 찾아가서 보지 않아도 되게끔 해준다라는 장점이 있는데, 데이터베이스 변경점이 있을때마다 옵션을 관리해주어야한다는 트레이드오프가 있습니다.

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    private Member member;
`@ManyToOne`의 default FetchType은 EAGER입니다. Reservation을 찾는 쿼리를 날릴때 어떤 쿼리가 발생되나요?

`findById`만이 아닌 다른 메소드에 대한 쿼리도 확인해보시면 좋을 것 같아요.

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Password.java
> +@Embeddable
👍

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/test/java/roomescape/repository/ReservationTimeRepositoryTest.java
👍

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +@Repository
여기서 `@Repository`는 어떤 기능을 하나요? 제거하면 어떻게 동작되나요?

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ReservationTimeRepository.java
> +            """)
jpql로 작성된 이유가 있을까요?

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ThemeRepository.java
> +            """, nativeQuery = true)
`nativeQuery`로 작성하게되면 database가 다른 구현체가 되었을때 문법이 달라지면 에러가 나지 않나요?

2024-05-16 09:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ThemeRepository.java
> +    List<Theme> findPopularThemeByDate(final LocalDate fromDate, final LocalDate toDate, final Long count);
interface 파라미터에 final은 제거해도 될 것 같아요.

2024-05-17 04:55 UTC, fromitive commented on src/main/java/roomescape/domain/Reservation.java
> +    protected Reservation() {
JPA 를 사용하기 위해서 protected 또는 public으로 열어둔 no-argument constructor를 사용해야 한다고 합니다. 결정적 이유는 [jarkarta JPA specification](https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0#a18) 에서 반드시(must) constructor를 정의해야 한다고 나와있기 때문이라고 합니다.

이유가 제가 생각하기 납득이 되지 않아 좀 더 검색한 결과 [baeldung](https://www.baeldung.com/jpa-no-argument-constructor-entity-class#reasons-for-no-arg-constructor) 에서 no-argument constructor를 사용해야 하는 이유 2가지를 찾을 수 있었습니다.
```
1. JPA provider가 no-argument constructor를 이용해야만 db와 entity를 유연하게 매핑할 수 있음
	- 유연하게 맵핑한다는 그림이 잘 그려지지 않아 와닿지 않았습니다.
2. JPA 기능 중 지연 로딩을 구현하기 위해선 proxy object를 생성해야 하기 때문 
	- 지연 로딩을 이용해 필요한 데이터만 db에서 불러올 때 proxy object를 활용하는데, 이 때 no-argument constructor를 이용해 빈 값으로 생성뒤 동적으로 데이터를 추가하는 걸로 추측
```

이 정도만 알 수 있었고 자세한 원리는 깊게 찾아봐야 할 것 같습니다.

물증은 없고, 심증으로 크루들에게 물어본 결과 java reflection을 사용하기 위해 no-argument constructor를 사용한다고 하는데, 그부분은 어디서 발견해야하는지 찾을 수가 없었습니다 🥲

2024-05-17 06:43 UTC, fromitive commented on README.md
제가 생각하는 검증의 기준은, `신뢰하지 않는 값이 들어올 수 있는 환경인가?` 라고 생각합니다 😄 

클라이언트의 입력값이 어떤 형태로 올 지 예측이 불가능하니(웹 어플리케이션을 통해 요청하는 게 아닌, json을 직접 보내는 관점에서) `1. 저장 하기 전`, `2. 사용자 입력값으로 비즈니스 로직을 처리하기 전`에 검증하여 어플리케이션이 예측 가능한 기능이 수행하도록 만들어야 한다고 생각합니다 😃 

현재는 검증을 통해 저장하고 있어서 다시 불러오는 부분은 굳이 검증해야할 필요는 못 느끼고 있습니다!

2024-05-17 09:28 UTC, fromitive commented on src/main/resources/application.properties
> +# jpa
`spring.jpa.hibernate.ddl-auto` 옵션은 [`hibernate.hbm2ddl.auto`의 단축어](https://github.com/spring-projects/spring-boot/blob/95145b23ec31c2b2a797434ef29fae7170b0a5b4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/HibernateProperties.java#L50)라고 나와있어서 
 
[이 문서](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl)를 참고하여 제공되는 옵션이 아래와 같이 존재함을 알 수 있었습니다.

```
`none` : spring boot가 동작할 때 ddl쿼리를 실행시키지 않음 
`create-only` : entity에 맞는 db가 생성됨 
`drop` : 기존에 있는 테이블을 삭제함
`create` : 기존에 있는 테이블을 삭제하고 테이블을 다시 생성함
`create-drop` : SessionFactory가 시작할 때 테이블을 제거하고 재생성함 또한 SessionFactory가 종료되면
`validate` : 데이터베이스를 검증함 - 스프링을 실행하기 전 DB에 테이블이 존재하는 지 확인하는 것 같음
`update` : 데이터베이스를 업데이트함 테이블이 존재하지 않으면 자동으로 테이블이 생성됨
```

validate와 update같은 경우 문서만으로는 그림이 그려지지 않아서 약간의 실험을 했습니다.

실험 환경으로는, 테이블이 존재하지 않은 상태에서 `schema.sql`을 만들어 어플리케이션이 실행되기 전에 테이블을 생성하도록 하였고 ddl-auto옵션을 `validate`, `update`로 바꿔봤습니다

실험 결과, **jpa ddl-auto 옵션부터 실행되고 schema.sql 이 실행되는 것 같아요.** schema.sql으로 테이블을 사전에 만들고 `validate`, `update` 옵션을 테스트해봤는데 `valitdate` 같은 경우 테이블이 존재하지 않아 실행이 되지 않았고, `update` 옵션같은 경우 `schema.sql`을 실행하기 전에 실행되기 때문에 테이블을 생성해주었습니다 😄

2024-05-17 10:17 UTC, fromitive commented on src/main/java/roomescape/domain/Reservation.java
> +    private Member member;
ReservationRepository에서 findByMember가 있어 해당 메서드로 실험해봤습니다!
`@ManyToOne`어노테이션이 붙여있는 부분을 전부 LAZY 혹은 EAGER로 붙여본결과, EAGER에서 select가 여러번 호출되는 것을 확인할 수 있었습니다 😃 

여러번 조회하는 것은 db에게 충분히 부담이 될 수 있으니 LAZY로 변경하겠습니다!

개인적으로 궁금한 사항이 있어 여쭈어봅니다. 
오늘 수업으로 영속성을 공부했는데, DB에서 select한 결과로 얻은 객체들은 entityManager를 통해 관리 영속성 관리 대상으로 등록되는 것으로 알고 있습니다.
그렇기 때문에 등록된 객체들이 존재하기 때문에 findAll 재요청시 DB에 select쿼리문이 날라가지 않음을 확인할 수 있었습니다.  
그러나 서로 다른 2개의 브라우저 (예: 사파리, 파이어폭스)에서 똑같이 findAll을 수행하게 되는 API를 요청했을 때 날아가는 쿼리를 확인해 본 결과 똑같이 select 문이 나가는걸 확인할 수 있었습니다. 🥲 entityManager는 스프링에서 관리하는 객체라고 추측하여 싱글톤으로 관리하여 select문이 한번만 나가는 줄 알았는데 그게 아니였나봅니다.  이러한 원리에 대한 근거는 어떻게 찾아야 할까요? (사실 안찾고 그런가보다로 넘어가도 좋을 부분일까요?)


#### Eager 결과 
```
Hibernate: select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id from reservation r1_0 where r1_0.member_id=?
Hibernate: select m1_0.id,m1_0.email,m1_0.name,m1_0.password,m1_0.salt,m1_0.role from member m1_0 where m1_0.id=?
Hibernate: select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
Hibernate: select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
Hibernate: select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
Hibernate: select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
```

#### LAZY 결과
```
Hibernate: select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id from reservation r1_0 where r1_0.member_id=?
```

2024-05-18 03:46 UTC, fromitive commented on src/main/java/roomescape/repository/ReservationRepository.java
> +@Repository
제거해도 정상 작동하는 것을 알게되었습니다 😃
그 이유는 상속받은 인터페이스인 `JpaRepository`의 구현체가 Bean으로 등록되기 때문에 정상작동하는 것 알게도었습니다!

중복된 Annotation이므로 제거하겠습니다!

2024-05-18 04:10 UTC, fromitive commented on src/main/java/roomescape/repository/ReservationTimeRepository.java
> +            """)
처음에는 조건에 만족하는 테이블이 `Reservation`에 있기 때문에 Jpql로 작성해야 할 필요성을 느꼈고, `ReservationTimeRepository`에서 `ReservationTime`들을 조회하는게 자연스러워 보였습니다 😅 

그러나, 저 jpql을 사용하는 서비스(`ResesrvationTimeService`)는 이미 `ReservationRepository`를 사용하고 있었고, getter로 reservationTime을 가져올 수 있으니 해당 jpql은 필요가 없어지게 됨을 알게되었습니다 😄

2024-05-18 12:24 UTC, fromitive commented on src/main/java/roomescape/repository/ThemeRepository.java
> +            """, nativeQuery = true)
h2가 아니라, mysql과 같은 항상 동작하는 sql쿼리문을 고려하지 않았네요 🥲

해당 부분은 limit 문법을 사용하기 위해서 native query를 사용하게 되었습니다. 이부분은 조사 후 jpql로도 표현할 수 있다고 하여 변경시켰습니다!

2024-05-18 12:26 UTC, fromitive commented on src/main/java/roomescape/repository/ThemeRepository.java
> +    List<Theme> findPopularThemeByDate(final LocalDate fromDate, final LocalDate toDate, final Long count);
해당 부분 final 제거 완료했습니다!

2024-05-18 12:29 UTC, fromitive commented
안녕하세요 오리🐤 포케입니다 😃 

리뷰주신 부분 코멘트를 남겨놓았습니다.  확인 부탁드립니다! 🙇‍♂️ 

그 외에 궁금한 부분은 코멘트 남겨놓았습니다! 😄

2024-05-18 12:42 UTC, fromitive commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional(readOnly = true)
`FetchType.LAZY`를 적용한 후 `Service`를 테스트를 하니 stream API를 사용하지 않은 테스트를 제외한 모든 테스트가 `LazyInitializationException`를 발생하게 되면서 실패했습니다.. 🥲 

**이상한 점**이, controller 테스트는 통합 테스트이기에 API 요청시 mock이 아닌 같은 서비스 메서드를 호출하는데 예외가 발생하지 않았고, `Repository`도 마찬가지로 `findAll()`을 수행할 때 예외가 발생하지 않았습니다.

오류를 검색한 결과, `FetchType.LAZY`를 하게 되면 연관관계에 있는 객체가 실제 객체가 아닌 **프록시 객체**가 저장되며, 필요할 때마다 쿼리문이 나간다고 합니다. 

그리고, stream API()를 사용하기 이전에, findAll()로 불러왔던 세션이 종료되면서, 조회할 때 세션이 없으니 예외가 발생하게 되는 것이라고 하네요. 이를 해결하기 위해 `@Transactional`으로 Session이 종료되지 않게 범위를 지정해주었습니다.  
 
 이렇게 지정하니, controller나, service에서 나가는 쿼리문이 `FetchType.EAGER`로 지정했을 때와 동일하게 나가는데 원래 이렇게 사용하는 건지 감이 잡히지 않습니다 😞

2024-05-18 17:30 UTC, jinyoungchoi95 commented on README.md
이미 검증된 domain에서 response로 넘기는데 response에서 굳이 검증을 해야하나 싶어요. request도 domain에서 반복된 유효성검사를 하고 있다면 저는 불필요하다고 생각합니다.

2024-05-18 17:33 UTC, jinyoungchoi95 commented on src/main/resources/application.properties
> +# jpa
default값이 무엇인지 확인해보시고 지양해야하는 정보라면 다른 옵션을 활용해보세요. table에 대한 정의는 sql 파일로 초기화한다고 가정하고 옵션에 대한 설정들을 해보시면 좋을 것 같아요.

2024-05-18 17:36 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    protected Reservation() {
java reflection은 어떤 constructor건 사용할 수 있어 잘못된 표현인 것 같아요.

jpa가 java reflection을 활용하여 쿼리를 통해 entity를 생성하고 있고, 그 생성하는 방법으로 기본 생성자를 사용한다. 로 정의하시면 될 것 같아요.

작성해주신 2번은 1번에 포함되는 내용이기 때문에 proxy object 때문에 no-arg가 아닌 db와 entity를 매핑하는 방법으로 no-arg를 쓴다까지만 이해하시면 될 것 같습니다.

2024-05-18 17:40 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    private Member member;
`findById`에 대해서도 EAGER 동작을 비교해보세요. 그 후 왜 EAGER를 지양해야한다라는 이야기가 나오는지 학습해보시면 좋을 것 같습니다. (findByMember는 왜 동작이 다른지도 포함해서요.)

> 그렇기 때문에 등록된 객체들이 존재하기 때문에 findAll 재요청시 DB에 select쿼리문이 날라가지 않음을 확인할 수 있었습니다.
그러나 서로 다른 2개의 브라우저 (예: 사파리, 파이어폭스)에서 똑같이 findAll을 수행하게 되는 API를 요청했을 때 날아가는 쿼리를 확인해 본 결과 똑같이 select 문이 나가는걸 확인할 수 있었습니다.

무슨말인지 이해가 가지 않아요. EntityManager는 싱글톤으로 관리되지 않습니다. jpa가 entity를 어떤 단위로 관리하고 있는지 transaction과 함께 학습해보세요.

2024-05-18 17:54 UTC, jinyoungchoi95 requested changes
안녕하세요 포케 😄

코멘트에 대한 답변과 몇가지 추가 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-18 17:54 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional(readOnly = true)
> controller나, service에서 나가는 쿼리문이 FetchType.EAGER로 지정했을 때와 동일하게 나가는데 원래 이렇게 사용하는 건지 감이 잡히지 않습니다 😞

무엇에 대한 문제를 말씀하시는건지 이해가 잘 안가네요.

1. `@Transactional`로 되었을 때 왜 entity lazy init 에러가 나는지 원인을 학습 (session에 대한 표현이 아닌 다른 표현이어야합니다.)
2. EAGER로 했을 때로 쿼리가 나가는 것이 무엇이 문제인가요? 어떤 차이가 있나요?

2024-05-18 17:54 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    boolean existsByThemeId(Long themeId);
테스트가 누락된 것 같아요.

2024-05-18 17:54 UTC, jinyoungchoi95 commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +@DataJpaTest
`@DataJpaTest`에는 `@Transactional`이 포함되어있어요. 위에서의 코멘트에서 학습 후 테스트에서 `@Transactional`을 사용하면 어떤 문제가 있는지 학습해보시면 좋을 것 같아요.

2024-05-20 13:51 UTC, fromitive commented on src/main/resources/application.properties
> +# jpa
아하! `schema.sql`을 다시 정의하고, ddl-auto=validate까지 하면 효과가 없었습니다
하지만, domain을 보고도 테이블 컬럼에 대한 조건을 한눈에 확인하기 위해서 @Table과 @Column으로 명시하니 db의 테이블과 매핑이 되지 않으면 예외가 발생함을 알게되었습니다.
또한, 사전에 테이블을 생성해주기 위해 `spring.jpa.defer-datasource-initialization=true`를 사용했는데 이를 주석처리 하니,

2024-05-21 02:52 UTC, fromitive commented on src/main/java/roomescape/domain/Reservation.java
> +    private Member member;
> `findById`에 대해서도 EAGER 동작을 비교해보세요. 그 후 왜 EAGER를 지양해야한다라는 이야기가 나오는지 학습해보시면 좋을 것 같습니다. (findByMember는 왜 동작이 다른지도 포함해서요.)

아래와 같이 EAGER 와 LAZY가 전달하는 쿼리를 비교했습니다 확실히 `LAZY`를 적용하고나서 쿼리문이 짧게 나가고 있음을 확인했습니다. 

`LAZY`로 관리한다면 reservation안에 설정되어 있는 객체에 접근할 때 쿼리가 나가고 있음을 알게되었고, `EAGER`로 쿼리를 날리게 되면 연관관계로 묶여있는 데이터를 한번에 가져오기 때문에 쿼리의 길이가 길어짐을 알 수 있었습니다. 

DB에 조인 연산이나, 여러번의 select문이 나가기 때문에  `EAGER`를 사용한다면 db에 부담이 갈수도 있겠습니다 😄

#### FetchType.Lazy 적용 후 Query

* **findById**
```sql
select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id 
from reservation r1_0
where r1_0.id=?
```

* **findByMember**
``` sql
select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id 
from reservation r1_0
where r1_0.member_id=?
```

#### FetchType.EAGER 적용 후 Qeury

* **findById**
```sql
select r1_0.id,r1_0.date,m1_0.id,m1_0.email,m1_0.name,m1_0.password,m1_0.salt,m1_0.role,r1_0.status,t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail,t2_0.id,t2_0.start_at from reservation r1_0 left join member m1_0 on m1_0.id=r1_0.member_id left join theme t1_0 on t1_0.id=r1_0.theme_id left join reservation_time t2_0 on t2_0.id=r1_0.time_id where r1_0.id=?
```

* **findByMember**
``` sql
select r1_0.id,r1_0.date,r1_0.member_id,r1_0.status,r1_0.theme_id,r1_0.time_id from reservation r1_0 where r1_0.member_id=?
select m1_0.id,m1_0.email,m1_0.name,m1_0.password,m1_0.salt,m1_0.role from member m1_0 where m1_0.id=?
select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
select rt1_0.id,rt1_0.start_at from reservation_time rt1_0 where rt1_0.id=?
select t1_0.id,t1_0.description,t1_0.name,t1_0.thumbnail from theme t1_0 where t1_0.id=?
```

> 무슨말인지 이해가 가지 않아요. EntityManager는 싱글톤으로 관리되지 않습니다. jpa가 entity를 어떤 단위로 관리하고 있는지 transaction과 함께 학습해보세요.

학습한 결과, EntityManagerFactory를 통해서 스프링의 각 Thread에 EntityManager가 생성되어 db와 상호작용하는 것을 알게되었습니다!

스프링에서 관리하는 JPARepository인 `SimpleJPARepository`클래스에 `@Transactional`어노테이션이 붙여저 있어서 각 메서드가 호출 시작 ~ 종료 할때까지 transaction이 유지됨을 알 수 있었습니다.

2024-05-21 05:08 UTC, fromitive commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional(readOnly = true)
해당 부분에서 시간이 많이 걸렸습니다. 😅 

 `FetchType.LAZY`를 적용한 후 `Service`를 테스트를 하니 stream API를 사용하지 않은 테스트를 제외한 모든 테스트가 `LazyInitializationException`를 발생하게 되면서 실패했습니다.. 🥲
> 
> **이상한 점**이, controller 테스트는 통합 테스트이기에 API 요청시 mock이 아닌 같은 서비스 메서드를 호출하는데 예외가 발생하지 않았고, `Repository`도 마찬가지로 `findAll()`을 수행할 때 예외가 발생하지 않았습니다.
> 
> 오류를 검색한 결과, `FetchType.LAZY`를 하게 되면 연관관계에 있는 객체가 실제 객체가 아닌 **프록시 객체**가 저장되며, 필요할 때마다 쿼리문이 나간다고 합니다.

이부분은 open session in view라는 개념을 알지 않은 상태에서 설명을 드리다 보니 전달이 잘 되지 않았습니다.😭

결론은 Spring Boot는 `spring.jpa.open-in-view=true` 라는 옵션이 기본 적용되어있었고 controller에서 응답이 오기까지 transaction이 죽지 않고(open session이니 session으로 설명드려야 할까요?)유지가 되어 reservationResponses를 생성할 수 있었습니다.

따라서 `controller/admin/AdminReservationTest` 안의 `given_when_GetReservations_then_statusCodeIsOk` 메서드는 통과가 됬던 것이었습니다.

그러나, `ReservationServiceTest`내에 Reservationservice.findEntireReservationList()를 직접 호출하게 되면 open session in view가 적용되지 않아서 아래의 코드 처럼 메서드 내부의 `reservationRepository.findAll()` 까지만, transaction이 유지되었던 것이었고, FetchType.LAZY 이기에 `.map(ReservationResponse::from)`에서 이미 transaction을 다시 사용하려니 예외가 발생한 것으로 분석됩니다. 😄

``` java
    public ReservationResponses findEntireReservationList() {
        // findAll() 호출완료시점에서 transaction 종료
        final List<ReservationResponse> reservationResponses = reservationRepository.findAll()
                .stream()
                 // 종료된 transaction으로 다시 요청하니, LazyInitializationException 예외 발생
                .map(ReservationResponse::from). 
                .toList();
        return new ReservationResponses(reservationResponses);
    }
```

> 이렇게 지정하니, controller나, service에서 나가는 쿼리문이 `FetchType.EAGER`로 지정했을 때와 동일하게 나가는데 원래 이렇게 사용하는 건지 감이 잡히지 않습니다 😞

이 이야기를 했던 것은, 현재 요구사항에서는 전체 예약 목록을 불러오기 위해 데이터를 전부 사용하고 있기때문에 LAZY와 EAGER의 차이가 없어 보였었습니다. 😅
프로젝트 크기가 커지게 되면 연관관계가 당장은 필요없는 객체를 불러올 필요가 없기 때문에 점점 LAZY와 EAGER의 성능차이가 날 것으로 예상됩니다! 😄

2024-05-21 05:16 UTC, fromitive commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    boolean existsByThemeId(Long themeId);
MemberRepository 의 findByEmail도 누락되어있었네요..! 추가하겠습니다!

2024-05-21 06:28 UTC, fromitive commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +@DataJpaTest
테스트에서`@Transactional`을 사용하게 되면 테스트가 끝난 후 실행했던 DB 정보들이 롤백이 되는 것 이외에, **하나의 트렌젝션으로 묶이기 때문에** `FetchType.LAZY`와 같이 연관된 엔티티를 지연로딩할 경우 거짓 양성이 나타날 수 있겠습니다. 😃

2024-05-21 06:36 UTC, fromitive commented
안녕하세요 오리 🐤 포케입니다. 😄

리뷰주신 부분에대해서 코멘트를 남겼으니 확인 부탁드립니다 🙇 

전 리뷰와 달라진 부분은 [링크](https://github.com/woowacourse/spring-roomescape-waiting/pull/67/files/e75cb7d467154b84b409cd022b1a3d400396e48c..bfd81b28475f6ddd094bf6a7986fa43ba3fb1fc5) 와 같습니다.

2024-05-21 07:27 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    private Member member;
쿼리를 실제로 날려보신걸 정리해보면
- findById
    - LAZY : entity 쿼리 후 연관관계에 걸린 entity들 각각 쿼리
    - EAGER : entity 쿼리에서 연관관계 걸린 entity join으로 한번 쿼리
- findByMember
    - LAZY, EAGER : entity 쿼리에서 연관관계 걸린 entity join으로 한번 쿼리

가 되겠네요. jpa 스펙에서 EAGER는 즉시로딩으로 `findById`에서 기대하는 기능과 동일하게 join으로 잘 즉시로딩한 것을 볼 수 있고,`findByMember`는 다시 쿼리를 한번 더 날리게 되는데요.

이전에 코드를 보여드렸지만 `findById`는 jpa의 인터페이스인 `EntityManager`의 find메소드를 사용하고 있기 때문에 EAGER가 목적에 맞게 잘 활용되고 있는 것이에요. 다만 `findByMembr`와 같은 "정의되지 않은" 동적 쿼리의 경우 spring data jpa가 임의로 쿼리를 만들어 날리게 되는데요.

이때 spring data jpa가 만드는 쿼리는 jpql을 만들어서 jpql 쿼리를 실행합니다.

여기까지 정리하면, `EAGER`가 문제되는 것이 아닌 spring data jpa가 jpql 쿼리로 `EAGER`를 날릴때 쿼리가 여러번 날아가는 것이 문제입니다. jpql이 `EAGER`에서 왜 쿼리가 여러번 날아가는지는 다음 단계 진행하면서 함께 학습해보시면 좋을 것 같아요.

2024-05-21 07:29 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional(readOnly = true)
네 필요한 상황에서 LAZY와 EAGER의 성능차이는 쿼리의 갯수에 대한 차이가 나는 것이므로 성능의 차이가 나는것이 맞아요.

다만 EAGER는 위의 코멘트에서 jpql 시 쿼리가 LAZY와 똑같이 나가며 왜 똑같이 나가냐는 학습하고 유의해서 사용하면 좋을 것 같아요.

2024-05-21 07:31 UTC, jinyoungchoi95 commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +@DataJpaTest
네. 실제로 api 요청시에는 하나의 트랜잭션에 묶이지만, 테스트를 진행하면서 테스트에 다른 쿼리메소드들이 나오게 될 경우 테스트를 위한 쿼리 트랜잭션이 테스트 대상이 되는 트랜잭션과 묶인다는 문제가 있어요.

테스트는 실제환경에서 이루어져야 이상적이지만 테스트용 쿼리들이 실제환경처럼 안만들수도 있는 거죠. 이건 다음단계를 진행하시면서 영속성에 대한 부분을 보고 학습하시면 좋을 것 같아요.

2024-05-21 07:34 UTC, jinyoungchoi95 approved these changes
안녕하세요 포케 😄

남겨주신 답변에 대한 코멘트와 추가 코멘트 달아두었으니 확인부탁드려요. 다음 미션 진행을 위해 머지하겠습니다. 현재 코멘트에서 궁금하신 점이 있다면 현재 pr에서는 확인하기 힘드니 다음 pr요청에 포함하여 요청주세요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-21 07:34 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Member.java
> +    @Column(unique = true, nullable = false)
(반영하지 않으셔도 됩니다.) `@Column`옵션에서 db와 비교하면서 볼만한 컬럼 옵션은 `name`, `nullable`, `unique`, `length`인 것 같아요. 그래서 이런 값들을 추가하여 db 스키마를 굳이 보지 않고 entity만 보고도 스키마 정보를 알 수 있도록 넣기도 해요.

2024-05-21 07:35 UTC, merged