[1 - 2단계 방탈출 예약 대기] 알파카(최휘용) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #68
Opened 2024-05-16 07:01 UTC by slimsha2dy

안녕하세요 스티치! 파카파카알파카입니다.

이번 미션은 제 페어인 조이썬의 코드로 진행하였습니다.
코드의 변경사항은 다음과 같습니다. [변경사항](https://github.com/woowacourse/spring-roomescape-waiting/pull/68/files/bdd13864b883b95a4ecf66da3ad338bcd1228052..68c7e5e0b02e846a4f672f50c1ac870a41b06d87)
이번 미션을 통해 JPA를 처음 접하게 되었다 보니 미션 구현 위주로 진행하느라 아직은 크게 질문이 없습니다.
이후 추가적인 학습이나 남겨주신 리뷰에서 궁금한 점이 생기면 질문 남겨보겠습니다.
잘 부탁드립니다!!

## 웹 개발 경험
스프링, JPA 및 웹 개발은 우테코 미션을 통해 처음 접해봤습니다.

## 0단계 기본 코드 준비
페어와 상의하여 누구의 기존 단계 코드를 가져올지 결정해야 했는데, 페어는 자신의 기존 코드를 계속 발전시키는 경험을, 저는 타인의 코드 기반에서 요구사항을 구현하는 경험을 하고자 해 제 페어인 조이썬의 코드를 사용하게 되었습니다.
서로 이전 미션(미션 1, 2)의 요구사항을 본인의 철학에 맞게 구현했다보니, 여러 군데에서 코드의 차이점이 발견되었습니다. 하지만, 이번 미션에서 배워가야 할 것들에만 집중하기 위해, 제 마음에 들지 않는 코드가 있더라도 그것이 이미 이전 미션을 통해 충분히 학습한 내용이면 수정하지 않았습니다.
따라서 이번 단계에서는 **JPA 관련 수정사항 혹은 그 자체의 내용**을 중점적으로 리뷰를 받아 학습하고 싶습니다.

## 테스트용 계정
이름 | 이메일 | 비밀번호 | 권한
-- | -- | -- | --
John Doe | john@example.com | password123 | ADMIN
Jane Smith | jane@example.com | abc12345 | USER
Alice Lee | alice@example.com | qwerty1234 | USER

2024-05-17 07:58 UTC, lxxjn0 requested changes
파카파카알파카 반갑습니다 :) 이번에 리뷰를 맡게 된 스티치입니다.

JPA를 적용하시면 엔티티에 대한 설계를 매우 잘 해결해주신 것 같아요. 단지 JPA를 적용하였지만 전체적으로 여전히 ID 기반의 조회 내용들이 많이 존재합니다. 이 부분을 중점으로 다시 확인해보시면 좋을 것 같아요. 

프로덕션 코드 위주로 피드백 남겨봤으니 한번 참고해주시고 제가 처음에 변경범위를 확인하지 못하고 기존 코드에 대한 피드백을 남긴 것들도 있는데 해당 피드백도 간단하게만 참고해주세요 :)

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/domain/user/Member.java
> +    private Role role;
JPA 엔티티를 작성하다보면 지금처럼 어노테이션이 다양하게 붙는 상황이 주로 생기곤 합니다(DTO도 마찬가지고요). 이런 경우 개행만 적절히 해준다면 코드의 가독성을 좀 더 높일 수 있어요 :)

```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Embedded
    private Name name;
    
    @Embedded
    private Email email;
    
    @Embedded
    private Password password;
    
    @Enumerated(EnumType.STRING)
    private Role role;
```

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/domain/user/Member.java
> +    }
Member 엔티티의 구분자는 Id로 설정되었는데 동등성을 부여할 필요가 있을까요? 도메인 적으로 동등성 부여가 필요없는 경우에는 추가하지 않는게 적절하다고 생각합니다. (해당 코드가 페어의 코드이지만 코멘트가 필요한 부분은 지금처럼 달아두도록 하겠습니다)

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/service/ReservationService.java
> +        final List<Reservation> reservations = reservationRepository.findAllByMemberId(memberId);
이번에 JPA를 사용하게 되었는데 조회 메서드는 id 기반으로 하고 있습니다. Member로 조회하지 않고 Id로 조회하신 이유가 있을까요? JPA를 적용한 만큼 그와 관련된 방향으로 코드를 작성해보면 좋을 것 같아서 질문드립니다.

만약 Resolver나 Interceptor에서 Member 엔티티를 반환하지 않고 사용해서 그렇다면 이 부분도 변경해보는 것은 어떨까요?

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    private ReservationStatus reservationStatus;
`@Enumerated` 활용 👍🏼

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
전체적인 도메인에 대해서 동등성을 부여해야 하는 것인가? 라는 고민을 다시 해보면 좋을 것 같아요. 도메인 요구사항으로 인한 동등성 부여가 아닌 단순히 테스트 편의성 등의 이유로의 동등성 부여라면 적절하지 않은 방향이 아닐지도 같이 고민해보면 좋을 것 같고요 :)

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/domain/reservation/ReservationStatus.java
> +        throw new IllegalArgumentException(String.format("%s 는 역할에 없습니다.", value));
stream을 활용하면 코드를 좀 더 깔끔하게 개선할 수 있을 것 같습니다 :)

2024-05-17 07:58 UTC, lxxjn0 commented on src/main/java/roomescape/repository/ThemeRepository.java
> +    List<Theme> getPopularTheme(final String startDate, final String endDate, int count);
Theme 도메인에서 Reservation을 가지고 있지 않고 지금처럼 쿼리로 해결하신 이유가 무엇인가요?

2024-05-19 04:47 UTC, slimsha2dy commented on src/main/java/roomescape/domain/user/Member.java
> +    private Role role;
멤버변수는 항상 당연히 붙여왔는데 이렇게 어노테이션이 많은 경우엔 개행을 추가하는 편이 훨씬 가독성이 좋네요! 🙇

2024-05-19 05:03 UTC, slimsha2dy commented on src/main/java/roomescape/domain/reservation/ReservationStatus.java
> +        throw new IllegalArgumentException(String.format("%s 는 역할에 없습니다.", value));
해당 부분 반영했습니다!!

2024-05-20 06:05 UTC, slimsha2dy commented on src/main/java/roomescape/domain/user/Member.java
> +    }
원활한 테스트를 위해 만들면서 필요할 수도 있겠다고 지나쳤었는데 도메인적으로 생각해봤을 때 Member의 동등성을 부여할 필요성이 없겠네요. 해당 부분을 삭제했습니다.

2024-05-20 08:49 UTC, slimsha2dy commented on src/main/java/roomescape/repository/ThemeRepository.java
> +    List<Theme> getPopularTheme(final String startDate, final String endDate, int count);
db에서 쿼리를 통해 해결할 수 있는 건 최대한 하기 위해서 해당 방식처럼 하게 되었습니다.
단순하지 않은 통계를 어디서 처리하는지에 대해 고민이 많았는데, 결국 실제 성능과 관련된 부분이고 실제 어플리케이션의 상황에 따라 지금 알기는 힘든 부분이라고 생각했습니다.
다만 장단점에 대해 생각해보자면,
- **쿼리로 해결할 경우**: 한 번의 쿼리가 db에 최적화되어 실행되므로 성능 상 좋을 것 같다. 디스크에 대한 접근이 최소화될 것 같다. 복잡한 SQL 문이 가독성을 해칠 수 있다.
- **그렇지 않을 경우**: Theme 도메인에서 Reservation 을 가지고 객체지향적으로 관련 부분을 구현할 수 있다. 즉 유지보수하기 쉬워진다. 

아직 기준에 대한 명확한 근거는 없지만, 두 장단점을 비교해보았을 때 큰 차이가 없다고 느껴지고 이전에 짜둔 SQL 쿼리를 활용할 수 있다는 점에서 일관되게 쿼리로 처리했습니다.
또한 해당 기능을 자바 코드로 구현하기 위해서는 날짜로 예약을 제한해야 하므로 Theme 도메인이 Reservation을 갖고 있는 형태를 크게 활용하지 못할 것 같습니다.
혹시 제가 놓친 부분이나 스티치의 의견이 있다면 듣고 싶습니다..!
이렇게 한 번에 쿼리로 처리하는 방식이 현업에서는 지양하는 방식일까요?

2024-05-20 12:32 UTC, slimsha2dy commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
현재 `Reservation`, `ReservationTime`, `Theme`에 대해 동등성이 부여되어 있습니다.
사실 이에 대해 모두 `equals`와 `hashcode`가 재정의된 이유는 테스트의 편의성 때문이었는데, `equals`가 굳이 지금 당장 필요하지 않더라도 언젠가 쓸 일이 없을 것이라 단언할 수도 없고, 도메인 로직 상으로 합당한 방식으로 재정의한다면 굳이 피할 필요가 없다고 생각해서 하게 되었습니다.
테스트에서 챙길 수 있는 편의성도 있고, 있다고 해서 부자연스럽게 느껴지지는 않는데 이에 대해 스티치는 어떻게 생각하시나요?

2024-05-21 10:09 UTC, lxxjn0 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
물론 '동등성을 부여하면 안되는가?'라는 질문에는 그렇다고 말할 순 없겠지만 '동등성을 부여하는게 더 적절한가?'에 대해서는 그렇지 않다고 할 수 있을 것 같아요. 물론 이 의견은 제 의견이니 알파카가 다르게 생각한다면 그에 대한 이야기를 나눠보는 것도 좋을 것 같아요 :)

> equals가 굳이 지금 당장 필요하지 않더라도 언젠가 쓸 일이 없을 것이라 단언할 수도 없고

먼저 이 말은 결국 현재는 쓰이는 곳이 없다는 이야기가 될 것 같아요. 그렇다면 우리가 경계해야 하는 오버엔지니어링의 관점이 아닐까 하는 생각을 합니다. 필요하지 않고 언제 쓰일지 모르는 기능을 지금 굳이 구현해두는 것이 옳은가에 대해서는 아니라고 생각합니다.

> 도메인 로직 상으로 합당한 방식으로 재정의한다면

두 번째로 이 부분은 도메인의 설계나 구현에 따라서 판단되는 문제라고 생각합니다. 그래서 알파카가 도메인을 동등성을 기반으로 정의한다면 그럴 수 있다고 생각합니다. 그러나 제가 느끼기엔 지금의 동등성은 도메인적인 의미를 지니는 동등성이 아닌 이미 유일성을 판단하는 구분자인 ID로만 동등성을 부여하기에 적절하지 않다고 생각했던 것이었습니다.

예를 들어서 자동차 게임을 생각해보면 DB가 없고 구분자가 없어서 우리는 다른 정보들을 통해서 동등성을 부여하였습니다. 또는 체스를 단순하게 생각해본다면 rank와 file의 정보가 같다면 동등한 위치라고 판별할 수 있기에 그에 맞는 동등성을 부여했고요.

그러나 지금의 도메인들에서는 구분자라는 동등성을 판별하는 기준이 이미 존재하는데 이 구분자를 도메인적인 동등성으로 사용해버린 상황이라고 생각해서 어색하다고 느끼는 것 같습니다.

정리해서 저는 '도메인에서 이러한 상황에 대한 객체는 동등한 객체라고 판단할 수 있다'라는 비즈니스 로직이 없는데 코드적인 편의를 위해서 동등성을 부여하면 '과연 도메인 객체가 해당 도메인을 표현하고 있는것인가?'라는 생각이 드는 것 같습니다. 혹시 알파카는 이러한 저의 생각에 대해서 혹시 어떤 생각을 가지시고 계실까요?

2024-05-21 10:20 UTC, lxxjn0 approved these changes
피드백 반영하시느라 수고하셨습니다 👍🏼 이번 단계는 생각보다 간단하게 잘 변경해주셔서 크게 피드백 드릴 내용은 없는 것 같습니다. 

추가로 이전 피드백에 대해서 답글 남겨뒀는데 한번 확인하시고 추가적인 의견 남겨주세요! 다음 단계 진행할 때 공유하시고자 하는 코멘트 링크 남겨주시면 함께 확인해보도록 하겠습니다 :)

2024-05-21 10:20 UTC, lxxjn0 commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +    private ThemeRepository themeRepository;
ThemeRepository가 두개가 있는데 코드가 잘못 작성된걸까요?

2024-05-21 10:20 UTC, merged

2024-05-22 07:39 UTC, slimsha2dy commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +    private ThemeRepository themeRepository;
헉 잘못 작성한 부분이네요.. 수정했습니다..!

2024-05-26 06:32 UTC, slimsha2dy commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
제가 처음에 동등성을 부여할 때 거부감이 들지 않았던 이유는, 비록 테스트를 위한 코드이지만 그렇다고 도메인의 성격을 해치지는 않는다고 생각했기 때문이었습니다.

언급해주신 id로 구분할 수 있는 유일성에 대해서는(제가 아직 프로젝트 경험이 없어서 짐작 뿐이지만), 예약 시간이나 테마 등의 도메인은 1 대 N 관계로 다른 여러 도메인이 가질 수 있기 때문에 영속화되기 전에 비교하는 상황이 생길 수 있지 않을까? 라고 생각했기 때문입니다.

만약 그런 상황이라면 id를 갖고 있지 않은 객체와 비교하게 될텐데, 만약 예약 시간 도메인이라면 id가 다르더라도 갖고 있는 시간 필드가 같다면 같다고 재정의하는 것이 굳이 이상하다고 느껴지지 않아 자연스럽게 쓰게 된 것 같습니다.
그래서 삭제한 `Reservation` 객체와 달리 `ReservationTime`과 `Theme`은 id가 아닌 필드의 비교를 통해 동등성을 판단하고 있었습니다.

>먼저 이 말은 결국 현재는 쓰이는 곳이 없다는 이야기가 될 것 같아요. 그렇다면 우리가 경계해야 하는 오버엔지니어링의 관점이 아닐까 하는 생각을 합니다. 필요하지 않고 언제 쓰일지 모르는 기능을 지금 굳이 구현해두는 것이 옳은가에 대해서는 아니라고 생각합니다.

이 부분에 대해서 저는 테스트에서의 용이성과 저울질할 수 있다고 생각했습니다.

만약 현재 도메인 로직에선 쓰이지 않지만 테스트만을 위한 코드가 있다면 다른 동료 개발자가 봤을 때 쉽게 사용성을 파악하기가 쉽지 않고 어쩌면 혼란을 줄 수 있지만, equals의 재정의는 굳이 쓰이지 않더라도 위에서 언급한 이유로 도메인의 성격을 해치지 않기도 하고 어떤 특정한 메서드를 정의한 것이 아닌 단순히 동등성을 부여한 것 뿐이므로 혼란을 줄 여지가 적은 반면, 테스트에서 동등성에서의 엄격함을 간단하게 부여할 수 있는 장점이 더 크다고 생각했습니다.
이에 대해서 스티치는 어떻게 생각하시나요?

2024-05-26 08:38 UTC, lxxjn0 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
알파카의 의견을 잘 작성해주셔서 감사합니다 :) 

 먼저 위에 알파카가 들어준 예시 중 '예약 시간의 경우 시간 필드가 같다면 같다고 재정의하는 것이 굳이 이상하다고 느껴지지 않아 ...'에 대해서는 저도 동의하는 바입니다. 도메인에 대한 정의는 비즈니스 요구사항에서 주어지기도 하지만, 논리적인 맥락에 따라 코드에서도 정의가 가능하다고 생각합니다. 우리는 이번 미션에서 예약 시간은 특정 시간에 하나만 존재하기에 시간이 같다면 동등한 객체라고 판단할 수 있습니다. 이게 결국 '도메인 로직'이라고 볼 수 있겠죠. 그렇기에 이러한 상황은 '시간이 같다면 동일한 예약 시간이다'라는 도메인 로직을 동등성을 부여해서 표현한 것입니다.

 다음으로 테스트를 위한 동등성 부여는 결국 개발자의 자율에 따르긴 합니다. 이전에 이야기한 것처럼 '틀린 코드이냐'라면 그렇진 않다고 생각하지만 '좋은 코드냐'라고 한다면 저는 여기에 동의하지 못한다는 이야기를 드린 것이었습니다. 이 부분은 저의 의견이기에 알파카가 무조건 적으로 제 이야기가 맞다고 생각하실 필요는 전혀 없습니다. 그냥 같이 개발을 하는 한 개발자의 의견 정도로만 생각해주시면 좋을 것 같아요.

 우테코 시작할 때 우리는 테스트 만을 위한 코드를 프로덕션 코드에 넣는 것을 지양하자라는 것을 배웠을 것입니다. 먼저 저는 이 관점에 매우 동의하는 편이기에 지금의 동등성 부여에 부정적인 편일 수 있습니다. 더 나아가 저는 과거에 getter 또한 프로덕션 코드에서 사용되는 getter가 아니면 구현하지 않았습니다. 그리고 테스트에서는 AssertJ가 지원해주는 extract 기능을 통해 필드를 가져와서 테스트를 하기도 했습니다. 그러나 getter는 kotlin 등의 언어에서는 프로퍼티의 정보를 제공해주는 역할로 기본적으로 제공해주기도 하고(이는 언어의 설계 방향이 프로퍼티에 대한 노출에 관대한 방향으로 가고 있다고 느꼈고, 저도 이에 동의하였다는 말이었습니다), 객체가 캡슐화 한 데이터를 변조할 위험이 적다면 노출되어도 괜찮다는 관점에 동의하면서 getter에 대한 생각은 조금 더 열린 관점으로 이해했던 것 같습니다.

 그러나 동등성은 이로 인해 발생할 수 있는 부작용이 명확하기도 하고(Set에서 동등성이 부여되면 삭제될 수 있는 위험), VO 객체와 같이 동등성이 코드 내에서 단순한 편의성 이상으로 표현하는 바가 크기에 이 부분에 있어서 제가 어색함을 느낀 걸 수도 있습니다. 도메인의 성격을 해치지 않는다는 것은 동의하지만 이 말이 곧 도메인의 성격을 표현하는 코드 냐에 대한 대답은 되지 않는다고 생각합니다. 저에겐 도메인의 성격을 해치지 않으면 어떠한 코드도 들어가도 되나? 라는 의문이 드는 이야기로 느껴졌습니다. 그렇기에 좀 더 보수적인 관점에서 도메인을 표현하는 코드가 도메인 객체에 들어가야 한다고 생각하기도 하고요.

 테스트에서 편의성이 중요하냐라고 물으신다면 편의성보다는 안정성과 보수적인 코드가 더 중요하다고 생각합니다. 언제든 명확한 상황에서만 코드가 돌아가는 것을 보장해주는 것이 테스트인데, 여기서 편의성에 대한 장점을 찾는 것이 옳을까? 아니면 테스트의 엄격함을 유지하는 것이 옳을까? 라고 물으신다면 저는 후자가 더 옳다고 생각하고요.

 정리하자면 결국 개발자의 개인적인 선택입니다. 물론 팀으로 운영이 된다면 모두가 동의하는 코드여야 하지만 지금은 알파카의 코드를 작성하는 과정이기에 어떤게 정답이라고 말씀드릴 수는 없습니다. 단지 저와 같은 리뷰어들은 이러한 부분에 대해서 생각해볼 수 있는 거리를 제공해주는 사람이라고 생각해주시면 좋을 것 같아요. 제가 작성한 말에 의도가 잘 전달될 지는 모르겠지만 알파카의 생각을 발전시키는 방향에 있어서 좋은 양분이 되었으면 하는 바람입니다 👍🏼