[1 - 2단계 방탈출 예약 대기] 로키(정해성) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #70
Opened 2024-05-16 07:16 UTC by HaiSeong

호돌🐯 안녕하세요!
또 뵙는군요! 저의 첫번째 미션 (자동차 경주) 리뷰어 셨어요!
이번 미션도 잘 부탁 드립니다.

### 스프링 경험
저는 이전에 스프링 경험이 있긴 하지만 조금의 인터넷 강의와 아주 작은 프로젝트만 경험해봐 처음 하는 사람이라고 생각하시면 될것 같습니다.

### 페어의 코드 사용
페어의 코드를 사용해서 이번단계 진행했습니다. 이전까지는 `controller` 라는 패키지가 있다면 `ReservtionController`, `ThemeController` 등이 모두 들어있는 구조를 사용했었는데, 이번 페어의 패키지 구조는 `reservation`이라는 패키지 안에 `controller`, `service` 등의 패키지가 각각있고 그 안에 `ReservationController`만 있는 구조를 사용하더라고요. 제가 사용하지 않았던 패키지 구조라 이번 미션을 통해 비교해보며 장단점을 느껴보고 싶었습니다.

### 이번 단계 반영 커밋
[링크]()

2024-05-16 10:44 UTC, kimhodol requested changes
안녕하세요 로키 :) 또 만나서 반갑습니다.

요구사항 구현 잘 해주셨네요.

코멘트 확인 부탁드립니다.

---

> 제가 사용하지 않았던 패키지 구조라 이번 미션을 통해 비교해보며 장단점을 느껴보고 싶었습니다.

저도 로키가 어떻게 느꼈는지 궁금하네요 ㅎㅎ 후기 들려주시면 감사하겠습니다!

2024-05-16 10:44 UTC, kimhodol commented on src/main/java/roomescape/member/dto/response/FindReservationResponse.java
> +                "예약");
의견) status도 Reservation 객체가 가지고 있으면 어떨까요?

2024-05-16 10:44 UTC, kimhodol commented on src/main/java/roomescape/reservation/model/Reservation.java
> +    @ManyToOne(fetch = FetchType.LAZY)
질문) FetchType.LAZY를 했을 때의 장점이 무엇인가요? 이렇게 설정해두어서 Repository에서 매번 JPQL Fetch Join을 써야한다는 것이 번거롭게 느껴져서요.

2024-05-16 10:44 UTC, kimhodol commented on src/test/java/roomescape/auth/AuthIntegrationTest.java
> +        // memberRepository.save(new Member("몰리", Role.USER, "login@naver.com", "hihi"));
질문) 이걸 비롯해서 가끔 테스트에서 주석처리 되어있는 코드들은 어떤 이유인가요?

2024-05-16 10:44 UTC, kimhodol commented on src/test/java/roomescape/auth/service/AuthServiceTest.java
>  class AuthServiceTest {
질문) 이것도 사실상 `@IntegrationTest`가 된 것 같은데, 변경한 이유가 있을까요?

2024-05-16 10:44 UTC, kimhodol commented on src/main/java/roomescape/common/GlobalExceptionHandler.java
> +                            jsonMappingException.getPath().get(0).getFieldName() + " 필드의 형식이 잘못되었습니다."));
질문) 0번째 path만을 가져와서 필드명 오류를 나타내는 이유가 있나요? IndexOutOfBound가 날 가능성은 없을까요?

2024-05-17 05:43 UTC, HaiSeong commented on src/main/java/roomescape/member/dto/response/FindReservationResponse.java
> +                "예약");
지금 2단계 까지는 사실 status가 모두 `예약` 이라는 상태 인것 같습니다. 3단계에서 `예약`이라는 상태와 `대기중` 이라는 상태가 생기게 되는것 같은데 `2번째 대기중` 같이 예약 순위를 알려줄지, 아니면 단순히 `예약대기중` 처럼 대기중이라는 상태만 알려줄지 정책이 정해지지 않은 상황 입니다. 또한 정책에 따라 구현방법도 여러가지가 될것 같습니다.

그래서 2단계에서 Reservation 테이블에 status 컬럼을 추가하는것이 아직은 무리라고 생각했습니다. 혹시 다음단계에서 추가해도 될까요?

2024-05-17 05:48 UTC, HaiSeong commented on src/test/java/roomescape/auth/AuthIntegrationTest.java
> +        // memberRepository.save(new Member("몰리", Role.USER, "login@naver.com", "hihi"));
`// memberRepository.save(new Member("몰리", Role.USER, "login@naver.com", "hihi"));`

페어의 이전코드에서 가져온 부분인데 지금 같은 경우는 `몰리`라는  member가 저장되지 않았다는 것을 강조하기 위해서 라고 했습니다. 저도 이 이유를 듣고 납득이 되어 그대로 유지했습니다. 

호돌이 보기에는 별로인가요?!

2024-05-17 06:49 UTC, HaiSeong commented on src/main/java/roomescape/reservation/model/Reservation.java
> +    @ManyToOne(fetch = FetchType.LAZY)
우선 모든 상황에서 Reservation의 Member나 Theme의 정보를 조회할 필요는 없다고 생각했습니다. 물론 지금 API 들은 모두 이 연관정보들을 즉시 가져와야 하지만요.

그러나 ㅍ하면 Member, Theme, ReservationTime을 JOIN을 해서 가져오지 않고 각각 쿼리를 날려 가져오는것을 발견했습니다. 이 n + 1 문제를 해결하기 위해  Fetch Join을 사용해서 한번에 모든 정보를 가져오도록 했습니다.

`매번 JPQL Fetch Join을 써야한다는 것이 번거롭게 느껴진다.`라는 의견은 동의 합니다..! 그러나 성능을 위해 필요하다고 생각했습니다.

아래는 `FetchType.EAGER`로 설정 후 JPQL을 삭제했을때 findAll을 호출한 결과입니다.
```
Hibernate: 
    select
        r1_0.id,
        r1_0.date,
        r1_0.member_id,
        r1_0.reservation_time_id,
        r1_0.theme_id 
    from
        reservation r1_0
Hibernate: 
    select
        m1_0.id,
        m1_0.email,
        m1_0.name,
        m1_0.password,
        m1_0.role 
    from
        member m1_0 
    where
        m1_0.id=?
2024-05-17T15:40:00.000+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
Hibernate: 
    select
        rt1_0.id,
        rt1_0.start_at 
    from
        reservation_time rt1_0 
    where
        rt1_0.id=?
2024-05-17T15:40:00.002+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
Hibernate: 
    select
        t1_0.id,
        t1_0.description,
        t1_0.name,
        t1_0.thumbnail 
    from
        theme t1_0 
    where
        t1_0.id=?
2024-05-17T15:40:00.002+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
Hibernate: 
    select
        m1_0.id,
        m1_0.email,
        m1_0.name,
        m1_0.password,
        m1_0.role 
    from
        member m1_0 
    where
        m1_0.id=?
2024-05-17T15:40:00.003+09:00 TRACE 72523 --- [nio-8080-exec-2] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
Hibernate: 
    select
        m1_0.id,
        m1_0.email,
        m1_0.name,
        m1_0.password,
        m1_0.role 
    from
        member m1_0 
    where
        m1_0.id=?
2024-05-17T15:40:00.004+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
Hibernate: 
    select
        rt1_0.id,
        rt1_0.start_at 
    from
        reservation_time rt1_0 
    where
        rt1_0.id=?
2024-05-17T15:40:00.005+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
Hibernate: 
    select
        m1_0.id,
        m1_0.email,
        m1_0.name,
        m1_0.password,
        m1_0.role 
    from
        member m1_0 
    where
        m1_0.id=?
2024-05-17T15:40:00.006+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [3]
Hibernate: 
    select
        rt1_0.id,
        rt1_0.start_at 
    from
        reservation_time rt1_0 
    where
        rt1_0.id=?
2024-05-17T15:40:00.009+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [3]
Hibernate: 
    select
        rt1_0.id,
        rt1_0.start_at 
    from
        reservation_time rt1_0 
    where
        rt1_0.id=?
2024-05-17T15:40:00.010+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [4]
Hibernate: 
    select
        rt1_0.id,
        rt1_0.start_at 
    from
        reservation_time rt1_0 
    where
        rt1_0.id=?
2024-05-17T15:40:00.010+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [5]
Hibernate: 
    select
        t1_0.id,
        t1_0.description,
        t1_0.name,
        t1_0.thumbnail 
    from
        theme t1_0 
    where
        t1_0.id=?
2024-05-17T15:40:00.011+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
Hibernate: 
    select
        t1_0.id,
        t1_0.description,
        t1_0.name,
        t1_0.thumbnail 
    from
        theme t1_0 
    where
        t1_0.id=?
2024-05-17T15:40:00.011+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [3]
Hibernate: 
    select
        t1_0.id,
        t1_0.description,
        t1_0.name,
        t1_0.thumbnail 
    from
        theme t1_0 
    where
        t1_0.id=?
2024-05-17T15:40:00.012+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [4]
Hibernate: 
    select
        t1_0.id,
        t1_0.description,
        t1_0.name,
        t1_0.thumbnail 
    from
        theme t1_0 
    where
        t1_0.id=?
2024-05-17T15:40:00.013+09:00 TRACE 72523 --- [io-8080-exec-10] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [5]
```

```
Hibernate: 
    select
        r1_0.id,
        r1_0.date,
        r1_0.member_id,
        r1_0.reservation_time_id,
        r1_0.theme_id,
        m1_0.id,
        m1_0.email,
        m1_0.name,
        m1_0.password,
        m1_0.role,
        rt1_0.id,
        rt1_0.start_at,
        t1_0.id,
        t1_0.description,
        t1_0.name,
        t1_0.thumbnail 
    from
        reservation r1_0 
    join
        member m1_0 
            on r1_0.member_id=m1_0.id 
    join
        reservation_time rt1_0 
            on r1_0.reservation_time_id=rt1_0.id 
    join
        theme t1_0 
            on r1_0.theme_id=t1_0.id
2024-05-17T15:48:02.619+09:00 TRACE 72743 --- [nio-8080-exec-2] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
```

2024-05-17 06:55 UTC, HaiSeong commented on src/main/java/roomescape/common/GlobalExceptionHandler.java
> +                            jsonMappingException.getPath().get(0).getFieldName() + " 필드의 형식이 잘못되었습니다."));
```java
if (ex.getCause() instanceof JsonMappingException jsonMappingException) {
            return ResponseEntity
                    .status(HttpStatus.BAD_REQUEST)
                    .body(ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST,
                            jsonMappingException.getPath().get(0).getFieldName() + " 필드의 형식이 잘못되었습니다."));
        }
```

`ex.getCause() instanceof JsonMappingException jsonMappingException` 이 조건을 만족한다면  `jsonMappingException.getPath()`의 길이가 무조건 1 이상이라고 생각되어서 이런식으로 작성했습니다. 

지금보니 인덱스를 통해 접근하는것보다는 다른 방법을 이용하는게 좋을것 같네요. 수정해보겠습니다!

2024-05-17 08:08 UTC, HaiSeong commented on src/test/java/roomescape/auth/service/AuthServiceTest.java
>  class AuthServiceTest {
`@IntegrationTest`는 E2E 테스트에서 사용하기 위해 만들었습니다. 

```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)
```
이 코드들이 중복되긴 하지만 용도가 달라 붙이는게 적합하지 않다고 생각했습니다.

2024-05-17 08:09 UTC, HaiSeong commented
>저도 로키가 어떻게 느꼈는지 궁금하네요 ㅎㅎ 후기 들려주시면 감사하겠습니다!

처음에는 패키지가 너무 많아 적응이 잘 안되었는데 적응되고 나니 찾기 훨신 쉬웠습니다. 특히 dto 패키지에 너무 클래스가 많아 찾기 어렵던것이 잘 보여서 좋은것 같습니다!

2024-05-18 13:47 UTC, kimhodol commented on src/main/java/roomescape/member/dto/response/FindReservationResponse.java
> +                "예약");
넵 이슈 없습니다!

2024-05-18 13:53 UTC, kimhodol commented on src/test/java/roomescape/auth/AuthIntegrationTest.java
> +        // memberRepository.save(new Member("몰리", Role.USER, "login@naver.com", "hihi"));
설명에 대한 주석은 납득이 가능할 것 같은데, 코드 주석은 이것이 지금 정책에 의해서 임시로 주석처리가 된 것인지(물론 그런 경우에도 주석을 잘 사용하진 않지만) 아닌지 의도를 파악하기 어려워서 사전 설명을 듣지 않으면 가독성에 좋지 않다는 생각이예요.

2024-05-18 14:12 UTC, kimhodol requested changes
안녕하세요 로키 :)

피드백 반영 잘 해주셨네요.

코멘트 확인 부탁드릴게요!

2024-05-18 14:12 UTC, kimhodol commented on src/main/java/roomescape/member/domain/Email.java
> +public class Email {
질문) record를 사용하지 않은 이유가 있을까요?

2024-05-18 14:12 UTC, kimhodol commented on src/main/java/roomescape/member/service/AdminService.java
> +    }
사소한 의견) 개인적으로 findXXX는 Optional을 반환하게 하고, getXXX는 non null한 엔티티를 반환하거나 예외를 던지게 하는 식으로 작성하는데, 선택적으로 반영해보시죠!

2024-05-18 14:12 UTC, kimhodol commented on src/main/java/roomescape/reservation/model/Reservation.java
> +    public boolean isSameTime(final ReservationTime reservationTime) {
의견) hasSameTime은 어떨까요?

2024-05-18 14:12 UTC, kimhodol commented on src/main/java/roomescape/reservation/repository/ReservationRepository.java
> +            select r, m, rt, t
질문) select r만 해도 되지 않나요?

2024-05-18 14:12 UTC, kimhodol commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +public class ReservationService {
질문) 서비스 테스트는 왜 없나요?

2024-05-19 04:26 UTC, HaiSeong commented on src/main/java/roomescape/auth/domain/AuthInfo.java
> +        return this.role.isNotAdmin();
앗 그렇네요! 삭제하겠습니다!

2024-05-19 04:29 UTC, HaiSeong commented on src/main/java/roomescape/auth/core/CookieAuthorizationManager.java
> +        }
넵 스트림문법 사용하여 수정하겠습니다!

2024-05-19 04:34 UTC, HaiSeong commented on src/main/java/roomescape/common/DateTimeFormatConfiguration.java
> +    }
페어의 전 코드에서 가져온 부분입니다!
프로젝트 전역적으로 날짜와 시간 형식을 지정해준다고 했습니다.

저는 이전에 DTO에서 지정해서 사용했는데 이전 코드를 가능하면 수정하지 말라는 이번 미션 요구사항과 새로운 방법을 공부해보자 라는 생각으로 그대로 사용하게 되었습니다.

2024-05-19 04:35 UTC, HaiSeong commented on src/main/java/roomescape/common/GlobalExceptionHandler.java
> +        System.out.println(EXCEPTION_PREFIX + ex.getMessage());
넵 logger를 도입하겠습니다!

2024-05-19 04:50 UTC, HaiSeong commented on src/main/java/roomescape/member/domain/Email.java
> +public class Email {
@Embeddable 객체를 record로 쓸수 있는줄 몰랐네요.

record는 기본생성자가 없으니 JPA 엔티티나 임배더블 객체로 쓸 . 수없겠다 생각했는데 다른 크루와 이야기 하다가 알게되었어요. 수정하겠습니다!

2024-05-19 09:44 UTC, HaiSeong commented on src/main/java/roomescape/member/service/AdminService.java
> +    }
말씀해주신대로 getXXX 이라는 네이밍이 더 어울리는것 같아요!! 수정하겠습니다! 👍

2024-05-19 09:45 UTC, HaiSeong commented on src/main/java/roomescape/reservation/model/Reservation.java
> +    public boolean isSameTime(final ReservationTime reservationTime) {
isSameTime 보다 좋은 이름인것 같습니다!

2024-05-19 10:05 UTC, HaiSeong commented on src/main/java/roomescape/reservation/repository/ReservationRepository.java
> +            select r, m, rt, t
jpql 문법을 잘 몰랐네요!! `select r` 만 써도 잘 됩니다!

2024-05-19 10:43 UTC, HaiSeong commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +public class ReservationService {
우선 페어의 기존코드에 Service 테스트가 없어 미션 기간동안 기존 코드들에 Service 테스트를 작성하기는 어렵겠다고 생각했습니다. 또한 아직 제가 스프링에서 단위 테스트를 작성하는 도구들에 대한 학습이 부족해 다음주 평일 시간을 통해 학습해보려 합니다.

혹시 테스트 도구에 대한 학습을 한 후 service 테스트를 작성해도 될까요?

2024-05-20 17:15 UTC, kimhodol commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +public class ReservationService {
네넵 물론입니다! 다음 단계에서 같이 반영해주세요~

2024-05-20 17:23 UTC, kimhodol reviewed
안녕하세요 로키 :) 리뷰가 늦어서 미안해요.

이번 단계는 여기서 마무리해도 될 것 같네요.

다음 단계도 화이팅입니다!

2024-05-20 17:23 UTC, merged