[1 - 2단계 방탈출 예약 대기] 시소(신지송) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #76
Opened 2024-05-16 07:58 UTC by shin-jisong

안녕하세요 호돌! BE 6기 시소입니다. 😊
이번 미션에서는 JPA를 전환하며 다양한 트러블 슈팅을 진행하고 배웠어요!
(대략 OneToOne은 왜 Lazy로 설정해도 Eager인지... 왜 No Arg 생성자가 있어야 하는지... 등 재미있는 경험을 했습니다 👍)
잘 부탁드리며, 좋은 하루 보내시길 바랍니다! 감사합니다. ☘️

### 저의 스프링 웹 경험은 다음과 같습니다
스프링을 다뤄 본 적은 있으나 깊은 사고를 한 경험은 부족합니다.
스프링의 형태 자체가 생소하지는 않지만, 클론 코딩정도의 경험이라 이번 레벨에 들어서 새로 학습하였습니다.

### 이번 미션에서 구현한 사항은 다음과 같습니다
지난 미션에서 완료된 페어의 코드를 가져와 구현하였습니다!
따라서 README.md에서 토글로 접힌 부분은 지난 미션 구현 사항이에요
이번 미션에서 추가한 코드에 대해서는 [여기](https://github.com/woowacourse/spring-roomescape-waiting/pull/76/files/559eca9dde2a7658bf6e7ec9645b521e5022a2c5..ca7accb5aad8c94457883fbcee89ab3174cdf2ad)에서 확인하실 수 있어요. 🙇‍♂️

2024-05-16 11:00 UTC, kimhodol requested changes
안녕하세요 시소 :)

요구사항 잘 구현해주셨네요.

코멘트 확인 부탁드립니다!

2024-05-16 11:00 UTC, kimhodol commented on src/test/java/roomescape/application/member/MemberServiceTest.java
> +    @Transactional
질문) 테스트 메소드에 Transcational을 붙이면 어떤 효과가 있나요?

2024-05-18 05:13 UTC, shin-jisong commented on src/main/java/roomescape/application/member/dto/request/MemberLoginRequest.java
> +        @NotNull(message = "이메일을 입력해주세요.")
NotNull의 경우, 어노테이션명과 동일하게 null만을 허용하지 않습니다

따라서 공백 문자는 허용하게 됩니다 해당 예시는 “” 혹은 “  “가 될 수 있습니다

NotEmpty의 경우, null과 함께 “”까지 허용하지 않습니다.

따라서 “ “의 경우 허용하게 됩니다.

NotBlank는 위 사항을 모두 허용하지 않습니다.

해당 부분에서는 포장 객체에서 validation을 한번 더 진행해 주기 때문에 입력 단계에서는 null만을 처리하도록 변경하였습니다!

2024-05-18 05:13 UTC, shin-jisong commented on src/main/java/roomescape/application/reservation/dto/response/ReservationStatusResponse.java
> +                "예약"
해당 부분을 ENUM으로 만들어 따로 처리하고자 하는 생각도 있었습니다

예를 들어 진행 완료, 예약 완료, 예약 취소 등을 활용하여

날짜가 지나면 진행 완료로 바꾸고 중간에 delete를 호출하면 취소로 변경하는 등을 수행할까 생각도 해 보았습니다 🤔

현재로서는 요구 사항을 착실히 수행하는 게 좋을 것 같아 보류하였었는데

유연하게 변경 사항에 대처할 수 있을 것 같아 다른 로직은 수행하지 않고 예약 진행만을 수행하도록 상태 관련 ENUM을 추가하였습니다

2024-05-18 05:13 UTC, shin-jisong commented on src/main/java/roomescape/domain/member/Email.java
> +    }
JPA를 도입하며  `no-args constructor`를 필수로 넣어 주는 과정에서

public으로 여는 것이 꺼려져 Package private으로 열었었습니다만

protected로 여는 것이 더 적절해 보여 변경해 주었습니다!

2024-05-18 05:13 UTC, shin-jisong commented on src/main/java/roomescape/domain/member/Member.java
> +    private PlayerName name;
해당 부분에 대해 고민해 봤는데 네이밍 통일에 따라 MemberName으로 바꾸는 게 더 적절해 보이네요! 변경해 주었습니다

2024-05-18 05:14 UTC, shin-jisong commented on src/main/java/roomescape/domain/member/Member.java
> +    public Member(String name, String email, String password) {
메인 코드가 테스트에 영향을 받아버렸네요!

수정하였습니다

2024-05-18 05:14 UTC, shin-jisong commented on src/test/java/roomescape/application/member/MemberServiceTest.java
> +    @Transactional
JPA 영속성 컨텍스트의 범위를 테스트 레이어까지 확장을 해 주고, 테스트 이후 롤백을 해 준다는 효과가 있어요.

저의 경우에는 전자의 효과를 위해서 사용해 주었습니다.

해당 코드에 Transactional을 붙여준 이유는 JPA를 도입하고 예기치 못한 save 오류를 발견했어요

선행되어야 하는 객체를 저장하고 이후 다른 객체를 저장하였을 때 null이 뜨며 서로 참조를 하지 못한다는 문제점이 있었어요

```
@Transactional
	@Override
	public <S extends T> S save(S entity) {

		Assert.notNull(entity, "Entity must not be null");

		if (entityInformation.isNew(entity)) {
			entityManager.persist(entity);
			return entity;
		} else {
			return entityManager.merge(entity);
		}
	}
```

구현체 코드를 보니 save를 하는 과정에서 각각의 Transactional을 해주어 객체를 인식 못 하는 오류라 생각했습니다

따라서 하나의 Transactional으로 관리해 주어 인식하도록 설정하였는데 저장을 할 때 한꺼번에 저장을 하니 해당 어노테이션을 활용하지 않아도 되었습니다!

따라서 해당 로직으로 바꿔 작성하는 것으로 수정했습니다 👍

2024-05-18 05:16 UTC, shin-jisong commented
안녕하세요 호돌! 
언급드린 사항을 제외하고는 모두 반영 완료하였습니다 👍
좋은 하루 보내세요 🙇‍♂️

2024-05-18 14:43 UTC, kimhodol commented on src/test/java/roomescape/application/member/MemberServiceTest.java
> +    @Transactional
좋은 글 하나 공유드립니다 :) https://toby.epril.com/8

2024-05-18 14:52 UTC, kimhodol requested changes
안녕하세요 시소 :)

피드백 반영 잘 해주셨네요.

코멘트 확인 부탁드립니다!

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/application/auth/JwtTokenManager.java
> +                           @Value("${jwt.expire-in-millis}") long tokenExpirationMills,
의견) ConfigurationProperties를 사용해보면 어떨까요?

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/application/config/ClockConfig.java
> +    @Bean
질문) 이건 어떤 용도인가요?

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/application/reservation/ThemeService.java
> +                        10)
의견) 7, 1, 10 같은 숫자는 상수화하면 좋을 것 같아요.

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/domain/member/Email.java
> +public class Email {
질문) record를 사용하지 않은 이유가 있을까요?

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/domain/reservation/ThemeRepository.java
> +            limit :limitCount
질문) jpql에서 limit이 작동하나요?

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/domain/role/MemberRole.java
> +    @MapsId
질문) 이건 어떤 용도인가요?

2024-05-18 14:52 UTC, kimhodol commented on src/main/java/roomescape/presentation/auth/CredentialContext.java
> +@RequestScope
질문) RequestScope를 어떻게 사용하고 있는건가요?

2024-05-19 05:06 UTC, shin-jisong commented on src/main/java/roomescape/application/auth/JwtTokenManager.java
> +                           @Value("${jwt.expire-in-millis}") long tokenExpirationMills,
좀 더 유연하게 값을 전달할 수 있고 객체 지향적으로 설계할 수 있네요!

도입하여 구현하였습니다 👍

2024-05-19 05:06 UTC, shin-jisong commented on src/main/java/roomescape/application/config/ClockConfig.java
> +    @Bean
해당 코드를 통해서 시간에 관련된 정보를 한 단계 더 추상화할 수 있습니다!

현재 저희의 서비스 코드는 시간에 대한 정보가 반영되어 있습니다

(현재 날짜보다 전의 날짜는 추가 불가능함 등)

또한 테스트 코드는 초기에 DB로 데이터를 셋업해 두어 사용하게 됩니다

하지만 시간에 대한 정보가 반영되어 있는 서비스 특성상 시간이 흐르면 테스트가 필연적으로 통과하지 못하게 되어 있습니다

따라서 시간 정보를 외부에서 주입해 주고 서비스 코드에서 현재 시간을 세팅해 주도록 설계되어 있습니다

2024-05-19 05:06 UTC, shin-jisong commented on src/main/java/roomescape/application/reservation/ThemeService.java
> +                        10)
가독성과 유지보수성을 위해 상수화하는 게 좋겠네요!

수정하였습니다

2024-05-19 05:06 UTC, shin-jisong commented on src/main/java/roomescape/domain/member/Email.java
> +public class Email {
메인 도메인 로직이라 추후 유지보수 시에 비지니스 로직이 추가될 가능성이 충분히 있다고 판단하였습니다

또한 Record는 entity로 구현할 시에 여러 예외 사항을 만날 수 있어 DTO에서만 사용하고자 하여 class로 구현하였습니다

2024-05-19 05:07 UTC, shin-jisong commented on src/main/java/roomescape/domain/reservation/ThemeRepository.java
> +            limit :limitCount
네 최근 업데이트 된 버전에 따르면 작동할 수 있다고 명시되어 있습니다

관련 공식 문서를 확인하고 코드를 작성하였는데 아무리 찾아도 해당 내용이 나오지 않아

관련 구현 코드 첨부드립니다! 😢

<img width="645" alt="image" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/86762272/46f8ccde-cf79-4cce-8783-b9cfcef45345">

2024-05-19 05:07 UTC, shin-jisong commented on src/main/java/roomescape/domain/role/MemberRole.java
> +    @MapsId
`@MapsId` 의 용도를 여쭤보시는 거라면 OneToOne 관계일 때 연관 관계에 있는 객체의 Id를 나의 Id로 맵핑해 주는 역할입니다! 따로 다른 Id를 사용하지 않고 공통 Id를 사용하고 싶어서 해당 방향으로 작성해 주었습니다

`MemberRole`의 용도를 여쭤보시는 거라면 멤버 Id와 대응되는 role을 저장하는 Entity입니다 Member에 저장하여도 되었겠지만 Member가 가지고 있는 정보를 atomic하게 저장하고 싶어 해당 구조로 설계하였습니다 Role이 나중 요구사항으로 들어온 내용이어서 테이블을 수정하는 것보다는 테이블을 추가하여 실제 유지보수 상황을 체험해 보고자 구현한 내용입니다

2024-05-19 05:07 UTC, shin-jisong commented on src/main/java/roomescape/presentation/auth/CredentialContext.java
> +@RequestScope
RequestScope을 사용하면 요청이 들어올 때마다 빈이 갱신되는 것을 이용하고자 하였습니다

 웹 요청 범위 내에서 사용자의 자격 증명을 관리하고 검증하는 역할을 수행하는데,

각 요청이 영향을 받으면 안 되기 때문에 해당 어노테이션을 사용해 주었습니다

2024-05-19 05:13 UTC, shin-jisong commented
안녕하세요 호돌! 
이것저것 질문해 주신 덕에 많이 공부하고 고심하여 코멘트 남깁니다
페어의 코드를 사용해 미션을 진행했어서 호돌이 주신 질문 중 페어가 작성한 코드에 대해서는
도입 당시에 페어와 대화 나누며 설명을 듣고 제가 납득한 사유를 작성했습니다 🙂
(현재 남아있는 코드는 제가 충분히 동의한 코드이며, 동의에 대한 사유들이 존재했습니다!)
하지만 설명이 불충분하다고 느끼실 수도 있을 듯해요 😖
해당 부분에 대해서는 추가 코멘트를 달아주시면 더 고민해 보고 코멘트를 남기도록 하겠습니다 
감사합니다 :)

2024-05-19 09:07 UTC, kimhodol commented on src/main/java/roomescape/domain/member/Email.java
> +public class Email {
> Record는 entity로 구현할 시에 여러 예외 사항을 만날 수 있어

이거는 어떤걸까용?

2024-05-19 09:08 UTC, kimhodol commented on src/main/java/roomescape/domain/reservation/ThemeRepository.java
> +            limit :limitCount
https://docs.jboss.org/hibernate/orm/6.0/userguide/html_single/Hibernate_User_Guide.html#hql-limit-offset

6.0에서부터 LIMIT이 지원되는군요? 하나 배워갑니다 :)

2024-05-19 09:10 UTC, kimhodol commented on src/main/java/roomescape/domain/role/MemberRole.java
> +    @MapsId
> MapsId 관련

좋습니다! 공통 ID를 사용했을 때 칼럼 개수가 줄어든다는 것 말고 다른 장점도 있을까요?


> MemberRole 관련

"실제 유지보수 상황"이라는 것이 어떤 걸 의미한지 명확하진 않지만, 납득가네요!

2024-05-19 09:13 UTC, kimhodol requested changes
안녕하세요 시소 :)

코멘트 달아주신 것에 대해 몇 가지 코멘트 달았습니다.

다만 피드백 반영사항이 remote push가 안된 것 같은데 확인 한 번 부탁드릴게요!

2024-05-19 13:45 UTC, shin-jisong commented on src/main/java/roomescape/domain/member/Email.java
> +public class Email {
record는 필드에 final 지정이 되고 no arg constructor가 없기 때문에 해당 부분에서 오류가 생길 수도 있다고 보았습니다!
또한 데이터 유효성 검사 등의 여러 비즈니스 로직을 넣을 것이라면 Record보다는 Class로 작성하는 것이 확장성이 좋다고 판단하였습니다 :)

2024-05-19 13:48 UTC, shin-jisong commented on src/main/java/roomescape/domain/role/MemberRole.java
> +    @MapsId
같은 값을 가지고 있어 불필요한 Id를 줄이고 관계를 직접적으로 볼 수 있다는 장점이 있다 생각합니다

실제 유지보수 상황에서는 기존의 데이터들이 있기 때문에 테이블을 직접적으로 수정하기 어렵지 않을까? 판단하였습니다
따라서 테이블을 추가하는 형식으로 진행해 보았습니다

2024-05-19 13:49 UTC, shin-jisong commented
죄송합니다 호돌 :( push하고 코멘트 남깁니다!

2024-05-20 18:30 UTC, kimhodol commented on src/main/java/roomescape/domain/member/Email.java
> +public class Email {
참고로 Hibernate 6.2부터 [embeddable java record](https://in.relation.to/2023/03/30/orm-62-final/)를 지원합니다. 

질문) 비즈니스 로직을 넣는데 있어서 record에는 어떤 문제가 있을까요?

2024-05-20 18:43 UTC, kimhodol approved these changes
안녕하세요 시소 :)

이번 단계는 여기서 마무리할게요.

다음 단계도 화이팅입니다!

2024-05-20 18:43 UTC, kimhodol commented on src/main/java/roomescape/application/auth/dto/JwtProperties.java
> +    private long expireInMillis;
의견) setter말고 생성자 주입을 사용해서 final 필드로 만들어 볼까요?

2024-05-20 18:43 UTC, merged