[1 - 2단계 방탈출 예약 대기] 명오(김형호) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #79
Opened 2024-05-16 08:07 UTC by HyungHoKim00

안녕하세요 범블비! 리뷰이 명오입니다.

저는 이번에 처음으로 스프링을 학습했습니다.

이번 미션 잘 부탁드립니다!

이번 미션 변화만 보기 [링크]()

사용 가능 id
ADMIN: [redddy@gmail.com](mailto:redddy@gmail.com), 0000
USER: '[gkatjraud1@redddybabo.com](mailto:gkatjraud1@redddybabo.com), 1111

2024-05-16 09:52 UTC, ddaaac requested changes
안녕하세요 명오 👋 

미션 구현 잘 해주셨네요.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-05-16 09:52 UTC, ddaaac commented on src/main/java/roomescape/config/CheckMemberInterceptor.java
> +            request.setAttribute(LOGIN_MEMBER, loginMember);
ArgumentResolver에서 할 수도 있을 것 같은 일인데 여러 단계를 거치며 loginMember를 구하는 이유가 있을까요?

2024-05-16 09:52 UTC, ddaaac commented on src/main/java/roomescape/domain/Reservation.java
> +    private Theme theme;
[즉시 로딩과 지연 로딩](https://ict-nroo.tistory.com/132)에 대해서도 학습해보시면 좋을 것 같아요.

2024-05-16 09:52 UTC, ddaaac commented on src/main/java/roomescape/domain/Reservation.java
> +    }
jpa는 왜 특정 접근제어자를 갖는 [기본 생성자](https://hyeonic.tistory.com/191)가 필요할까요?

2024-05-16 09:52 UTC, ddaaac commented on src/main/java/roomescape/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
[Crud Repository](https://blog.naver.com/writer0713/221587319282)에 대한 글을 읽어봐도 좋을 것 같아요.

2024-05-16 09:52 UTC, ddaaac commented on src/main/java/roomescape/repository/MemberRepository.java
> +    }
재미있는 시도네요. 
findByEmailOrThrow 정도로 네이밍을 하면 어떨까 싶어요.

2024-05-16 09:52 UTC, ddaaac commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    List<Theme> findPopularThemes(
Popular의 정의는 어떻게 될까요?
이 정의에 대한 구현이 쿼리에 있는 것과 도메인에 있는 건 어떤 차이일까요?

2024-05-16 09:52 UTC, ddaaac commented on src/main/resources/application.yaml
> +    show-sql: true
프로덕션 환경에서 sql문을 모두 볼 필요가 있을까요?
테스트 환경에서는 꽤 유용할 수 있는데요, 테스트 환경에서만 이 설정을 오버라이드해도 좋을 것 같습니다.

2024-05-16 09:52 UTC, ddaaac commented on src/main/resources/application.yaml
> +      ddl-auto: create-drop
[이 글](https://smpark1020.tistory.com/140)을 읽어봐도 좋을 것 같습니다.

2024-05-16 09:52 UTC, ddaaac commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
- Repository 테스트에 Web 환경 설정이 필요할까요?
- `@SpringBootTest` 외에 레포지토리 테스트에 적당한 다른 테스트 환경은 없을까요?

2024-05-16 09:52 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@Transactional
[@Tx](https://toby.epril.com/8)를 활용한 테스트에는 다양한 의견이 있습니다. 한 번 확인해보셔도 좋을 것 같아요.

2024-05-17 02:45 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/CheckMemberInterceptor.java
> +            request.setAttribute(LOGIN_MEMBER, loginMember);
만약 checkMemberInterceptor에서 구하지 않으면 checkAdminArgumentResolver와 loginMemberArgumentResolver 모두에서 쿠키를 활용하여 member를 가져오는 중복 로직이 발생할거라 생각되어 한 곳에서 처리하도록 했습니다.

하지만, 중복을 제거하기 위해 새로운 interceptor를 구현한 것이 의도대로 사용하지 않고 있다고 느꼈고, 오히려 코드를 증가시킨다고 느껴졌습니다.

별개의 Util 클래스로 정적 메서드를 사용하여 수정했습니다!

2024-05-17 05:25 UTC, HyungHoKim00 commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
기존에 이에 대해 잘 몰랐기에, 학습한 내용이 맞는지 여쭤보고 싶습니다.

1. Repository에는 web 환경 설정이 필요하지 않습니다. entityManager를 통해 db에 접근하고 있고, flush가 발생하기 전 까지는 web에 있는 db에 접근하지 않기 때문입니다. (물론, 현재는 인메모리 db를 사용하고 있기에 이런 문제는 더욱 발생하지 않습니다.)
2. @DataJpaTest를 사용해보았습니다. 눈에 띄는 점은, @Transactional이 붙어있다는 것입니다.
아래에 말씀하셨듯, Transactional 어노테이션은 많은 의견이 있는 것으로 알고 있습니다.
하지만, DataJpaTest에서는 위험하다고 느껴지지 않습니다. 하나의 쓰레드에서 관리하고 있기 때문입니다.
또한, SpringBootTest보다 눈에 띄게 속도가 증가한 것이 보였습니다.

2024-05-17 05:31 UTC, HyungHoKim00 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@Transactional
태그해주신 글과 태그해주신 글 내부의 글 모두 잘 읽어보았습니다!

제가 생각한 Transactional의 제일 큰 위험성은, RestAssured를 사용할 때 다른 쓰레드를 사용하기 때문에 정상적으로 반영이 안된다는 점입니다.

Transactional을 사용한 이유는 Test DB의 데이터가 변하지 않기 위해, 테스트간의 독립성을 보장하기 위해서입니다. 만약 테스트간의 독립을 쉽게 다른 방법으로 보장할 수 있다면, 위 방법을 사용하지 않았을 것 같습니다.

그래서 테스트 데이터 초기화가 필요한 모든 테스트 클래스에 @Sql을 사용하는 방식으로 수정하였습니다!

2024-05-17 05:34 UTC, HyungHoKim00 commented on src/main/resources/application.yaml
> +    show-sql: true
프로덕션 환경에선 sql문을 모두 볼 필요가 없다고 생각합니다!
제가 sql문을 보도록 설정한 이유는 jpa가 어떻게 동작하는 지 확인하기 위해서입니다.
실제로 많은 데이터가 오간다면, 불필요하게 많은 sql문이 보일 것입니다.
test환경에서 확인하면 제가 원하는 동작만 하는 지 확인할 수 있기 때문에 테스트 환경에서만 보이도록 수정했습니다.

2024-05-17 06:03 UTC, HyungHoKim00 commented on src/main/resources/application.yaml
> +      ddl-auto: create-drop
확실히, 프로덕션 코드에서 create-drop을 한다는 것은 말이 안된다고 느껴지긴 합니다. 프로그램을 실행할 때 마다 테이블을 초기화하기 때문입니다.
물론 저희는 inMemoryDb를 사용하고 있지만, 실제 프로덕션으로 가게 되면 none을 사용하는 것이 좋을 것 같아 수정했습니다!
validate로 사용해본 결과, 테이블을 만드는데도 불구하고 테이블을 찾지 못하는 오류가 있었습니다 ㅜㅜ 이에 대한 방안은 추가적으로 찾아볼 예정입니다.

2024-05-17 06:07 UTC, HyungHoKim00 commented on src/main/java/roomescape/repository/MemberRepository.java
> +    }
감사합니다! 예외 처리를 어디에서 던지는 것이 좋을 지에 대한 범블비의 의견이 궁금합니다.
1. 예외 처리를 서비스에서 한다.
repository에서 진행하는 것 보다 service에서 예외를 던지는 것이 자연스럽고, 현재 service에서 대부분의 예외를 처리하기 때문에 일관적으로 느껴집니다.
2, 예외 처리를 repository에서 한다.
repository에서 findOrThrow 정도의 예외 처리를 진행해 주어야, 서비스에서 중복 코드가 발생하지 않을 것 같습니다.

위에 대해 어떻게 생각하시나요?

2024-05-17 06:28 UTC, HyungHoKim00 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    List<Theme> findPopularThemes(
popular라는 메서드명은 어떤 반환값을 가지는 지 모호한 느낌이 드네요.. 수정했습니다!

쿼리에 있는 것과 도메인에 있는 것의 제일 큰 차이는 theme을 바로 객체로 가져올 수 있다는 점이라고 느꼈습니다.
도메인에 존재하는 경우, reservation 테이블에서 바로 theme을 한 쿼리만에 가져오기 어렵지만, 쿼리를 사용하여 쉽게 가져올 수 있었습니다!

2024-05-17 06:31 UTC, HyungHoKim00 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
아래는 주신 글을 바탕으로 학습한 내용입니다.

JPA는 DB 값을 객체 필드에 주입할 때 기본 생성자로 객체를 생성한 후 Reflection을 사용하여 값을 매핑하기 때문입니다.
Reflection 방식이 사용되는 이유는, 지연 로딩의 경우 조회하기 전까지 프록시 객체로 존재하기 때문입니다.

2024-05-17 06:36 UTC, HyungHoKim00 commented on src/main/java/roomescape/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
주신 글 잘 읽어보았습니다!

제가 JPA Repository를 사용하게 된 이유는, CRUD에서는 findAll을 호출 할 때 Iterable꼴로 호출되기 때문이였습니다.
물론 ReservationRepository를 제외한 Repository에서는 CRUD의 기능만으로 충분하지만, Controller에서 ResponseEntity로 모두 반환하지만 `@RestController`를 사용하는 것 처럼 일관성있게 사용하는 것이 좋을 것이라고 생각했습니다.
List꼴로 가져올 필요 없는 경우의 Repository는 JPA로 하는 것이 더 좋은 방법일까요?
어떤 방법을 선호하시는지 궁금합니다.

2024-05-17 06:59 UTC, HyungHoKim00 commented on src/main/java/roomescape/domain/Reservation.java
> +    private Theme theme;
처음 접근해보는 주제여서, 학습에 큰 도움이 되었습니다.

즉시 로딩은, reservation 조회 쿼리가 발생한 시점에서 모든 연관 객체를 로딩하고,
지연 로딩은, reservation 조회 쿼리 발생 후 연관 객체를 조회하려 할 때 그 객체를 로딩합니다.

즉시 로딩을 사용하면 n+1 문제가 발생하는 것을 볼 수 있었는데, 그 원인을 파악할 수 있었습니다.

모든 ManyToOne 연관관계를 Lazy로 변경하였습니다!

2024-05-17 08:22 UTC, HyungHoKim00 commented
안녕하세요 범블비!!

남겨주신 좋은 글 자료들이 학습하는데 큰 도움이 되었습니다.

특히, 대부분이 질문이라 생각해볼 것이 많아 많이 배웠습니다.

이번에도 잘 부탁드립니다!!

2024-05-18 04:34 UTC, ddaaac approved these changes
안녕하세요 명오 👋 

리뷰 반영 잘 해주셨습니다.

다음 단계 진행해주세요!

2024-05-18 04:34 UTC, ddaaac commented on src/main/java/roomescape/domain/Reservation.java
> +    private Theme theme;
eager 방식이 알맞은 방법일 때도 있습니다. 각 방식의 특징을 잘 따져서 선택하시면 좋을 것 같아요.

2024-05-18 04:34 UTC, ddaaac commented on src/main/java/roomescape/repository/MemberRepository.java
> +    }
객체 관점에서 메서드 시그니처와 함께 생각해보시면 좋을 것 같아요.
repository#findByEmailOrThrow 란 시그니처를 보면 어색할까요?

2024-05-18 04:34 UTC, ddaaac commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    List<Theme> findPopularThemes(
요구사항이 쿼리에 있는 경우 도메인 요구사항이 변경될 경우에 쿼리를 분석하고 수정해야될 수도 있겠죠. 프로시저 사용을 피해야 되는 이유에 대해서도 찾아보시면 좋을 것 같네요.
가능하다면 도메인에 로직을 두고 쿼리는 가볍고 직관적이게 사용하면 좋을 것 같아요.
물론 성능 등의 이유로 쿼리에 어느정도 로직이 들어갈 수도 있습니다.

2024-05-18 04:34 UTC, ddaaac commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
웹 환경이 필요없다면 webEnvironment = NONE으로 줄 수 있을 것 같습니다.
`@DataJpaTest` 잘 사용해주셨어요.

2024-05-18 04:34 UTC, merged

2024-05-20 00:43 UTC, HyungHoKim00 commented on src/main/java/roomescape/repository/MemberRepository.java
> +    }
시그니처가 어색하지 않은 것 같습니다!
실제로 jdbcTemplate의 queryForObject를 사용하면, 제가 사용하고 있는 findByEmailOrThrow와 비슷하게 느껴지네요.
findByEmail이라는 메서드도 동시에 존재하기 때문에 상황에 맞게 사용해주면 좋을 것 같습니다!

2024-05-20 02:21 UTC, HyungHoKim00 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    List<Theme> findPopularThemes(
프로시저에 비즈니스 로직을 넣었을 때의 단점이 많다는 것을 알 수 있었습니다.
특히, 유지보수성과 테스트에서 큰 결함을 가진다는 부분에 공감할 수 있었습니다. 당장에 저도 sql 구문을 읽는 데에 어려움을 겪고 있는데, 이를 수정하면서 올바르게 수정되었는지 확신을 가지기도 어려울 것 같습니다.
또한, db의 성능을 향상시키기보다 서버의 성능을 향상시키는게 더 쉽다는 점도 알게 되었습니다.

쿼리를 간단하게 하기 위해 로직을 서비스단에서 수행하도록 변경했는데요, 이때 could not initialize proxy - no session 에러가 발생했습니다. 이를 해결하기 위해 두가지 방법을 알게 되었습니다.
1. `@Transactional`
2. `@EntityGrapth`

1번 방법은 쿼리가 더 많이 나간다는 단점이 있었고(Theme 조회 쿼리만 3회 발생하여 총 4회의 쿼리가 발생했습니다.)
2번 방법은 재사용성이 떨어진다는 단점이 있었습니다.(이 쿼리를 사용하여 Theme 이외의 정보를 조회하고 싶을 시 수정해야함. 모든 객체를 EntityGraph로 연결한다면 Lazy Loading의 장점을 느끼지 못함)

어떤 방법을 더 선호하시나요?

2024-05-20 04:00 UTC, HyungHoKim00 commented on src/main/java/roomescape/infrastructure/TokenExtractor.java
> +    public static String fromRequest(HttpServletRequest request) {
외부로부터 의존된 값을 사용하지 않고, 같은 파라미터에 대해 항상 같은 값을 반환하는 경우 정적 팩토리 메서드를 사용할 수 있습니다. 또한, 이 메서드가 유틸성 메서드임을 나타내줄 수 있습니다.
반면, 빈으로 등록하면 그 객체의 생명을 스프링이 관리해준다는 장점이 있으며, 유연하게 사용할 수 있습니다.

위의 메서드는 유틸성 메서드라고 생각하여 static을 사용했습니다.

2024-05-21 09:05 UTC, ddaaac commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    List<Theme> findPopularThemes(
[OSIV](https://f-lab.kr/insight/understanding-osiv-in-spring-boot?gad_source=1&gclid=Cj0KCQjwjLGyBhCYARIsAPqTz1_qKYW4w2CppGmvg-ucT1t3rou4jTQHNO_o9GS9098KqB-h0HGGAU4aAhMSEALw_wcB)를 알아봐도 좋을 것 같아요.

만약 대부분 로직에서 내부 객체를 사용해야한다면 fetch join을 사용하는 게 더 적당하지 않을까요?
내부 객체를 참조하는 케이스가 적다면 그냥 `@Tx` 써두 될 거 같구요.

2024-05-22 04:17 UTC, HyungHoKim00 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    List<Theme> findPopularThemes(
프로덕션 환경에서만 정상 동작한 이유는 osiv 설정 때문에 트랜잭션이 종료된 후에도 지연 로딩이 가능했었군요!