[1 - 2단계 방탈출 예약 대기] 잉크(이예찬) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #81
Opened 2024-05-16 08:16 UTC by yechop

안녕하세요 잉크입니다.

2024-05-16 15:01 UTC, choijy1705 requested changes
안녕하세요 잉크!
미션 잘 구현해셨어요👍
jpa와 내예약 보여주는 부분 위주로 코멘트 남겼습니다
확인부탁드려요!

2024-05-17 06:38 UTC, yechop commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
방탈출 예약 대기 미션으로 넘어오면서 기존에 만들어놨던 스키마를 지우고 싶지 않아 찾아보다보니  create, update는 주로 개발 초기 단계에 사용하고 운영서버는 validate 혹은 관례상 none을 사용한다는 것을 학습했습니다.

2024-05-17 06:41 UTC, yechop commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    @ManyToOne
시도해보다가 계속 실패해 방법을 못찾았는데 이번 피드백 강의를 통해 영속성 컨텍스트에 대해 학습하여 지연 로딩과 트랜잭셔널을 적용했습니다.

2024-05-17 06:42 UTC, yechop commented on src/main/java/roomescape/member/repository/MemberJpaRepository.java
> +public interface MemberJpaRepository extends CrudRepository<Member, Long> {
JpaRepository를 새롭게 학습해 적용했습니다!

2024-05-17 06:51 UTC, yechop commented on src/main/java/roomescape/theme/repository/ThemeJpaRepository.java
> +            """)
답변 감사합니다

2024-05-17 06:57 UTC, yechop commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    protected Reservation() {
지연 로딩을 적용해보던 도중 private 생성자를 protected로 바꾸는 과정에서 실수로 Reservation까지 바꿨네요 😭

2024-05-17 07:43 UTC, yechop commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
null 검증을 추가했습니다.

2024-05-17 08:22 UTC, yechop commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    protected Reservation() {
엔티티 클래스는 빈 생성자가 필요하고 , public이나 protected가 있어야 한다고 하는데 당장 public으로 필요가 없어서 protected로 설정해 두었습니다.

<img width="961" alt="스크린샷 2024-05-17 오후 5 21 38" src="https://github.com/woowacourse/spring-roomescape-waiting/assets/148426765/7cc67a18-8b21-452c-94f2-a9c27eac80df">

2024-05-17 08:33 UTC, yechop commented on src/main/java/roomescape/member/service/MemberService.java
> +    }
ReservationController.addReservation() 에서 매개변수로 MemberRequest를 받고 있습니다.  컨트롤러가 도메인에 대해 알 수 없게 MemberRequest로 반환했습니다.
argumentResolver 의 반환타입이 중요할까요??

2024-05-20 06:03 UTC, yechop commented on src/main/resources/application.properties
> +spring.jpa.defer-datasource-initialization=true
학습 후 필요한 설정만 test yaml 파일로 옮겼습니다

2024-05-20 06:52 UTC, yechop commented on src/main/java/roomescape/util/TokenExtractor.java
> +        return Arrays.stream(cookies)
상황에 맞게 에러 메시지를 수정했습니다.

2024-05-20 09:10 UTC, yechop commented on src/main/java/roomescape/member/domain/Password.java
> +public record Password(String password) {
PasswordEncoder를 활용하여 암호화했습니다.
회원가입 기능을 구현하지 않은 상태라 "password"를 BCryptPasswordEncode로 인코딩해 data.sql에 초기 데이터로 저장해놓았습니다.

2024-05-20 12:50 UTC, choijy1705 approved these changes
잉크
jpa 관련해서는 잘 반영해주셨습니다👍
로그인과 같은 사용성 측면에서는 아직 챙기지 못한부분들이 있는것 같습니다
다음 단계 진행하면서 다시 한번 챙겨보면 좋을것 같아요!

2024-05-20 12:50 UTC, choijy1705 commented on src/main/java/roomescape/member/service/MemberService.java
> +        if (passwordEncoder.matches(member.getPassword().password(), loginRequest.password())) {
순서 바꿔야 할것 같아요!

2024-05-20 12:50 UTC, choijy1705 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    }
private 은 안되서 protected로 사용한다고 이야기 해주셨는데
얘는 private 으로도 동작하는건가요?

2024-05-20 12:50 UTC, choijy1705 commented on src/main/java/roomescape/member/service/MemberService.java
> +        if (passwordEncoder.matches(member.getPassword().password(), loginRequest.password())) {
signUp은 따로 없는건가요??
로그인 안되어서 그냥 회원가입해서 테스트 해볼려했는데 없는것 같네요!

2024-05-20 12:50 UTC, merged

2024-05-21 01:55 UTC, yechop commented on src/main/java/roomescape/member/service/MemberService.java
> +        if (passwordEncoder.matches(member.getPassword().password(), loginRequest.password())) {
> signUp은 따로 없는건가요?? 로그인 안되어서 그냥 회원가입해서 테스트 해볼려했는데 없는것 같네요!

패스워드 암호화 해보라고 하신 리뷰에 코멘트 달아놨는데 못보신것 같아요! 3-4단계 pr에 코멘트 달아놓겠습니다~

2024-05-21 02:05 UTC, choijy1705 commented on src/main/java/roomescape/member/service/MemberService.java
> +        if (passwordEncoder.matches(member.getPassword().password(), loginRequest.password())) {
@yechop 실행해서 해보시면 로그인이 안됩니다...
확인해보시면 좋을것 같네요