[3 - 4단계 방탈출 예약 대기] 백호(전호건) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #90
Opened 2024-05-20 00:58 UTC by Arachneee

안녕하세요 비밥!
백호입니다!

저번 단계 리뷰에서 새로운 인사이트를 얻을 수 있어서 좋았어요!
이번 단계도 잘부탁드립니다. 😄 

### 리뷰 받았으면 하는 부분
- 각 객체에 적절한 역할이 부여되어 유지보수에 좋은 코드인지 궁금해요.
- 성능적인 부분도 잘 고려되었는지 알고 싶어요.

### 이번 미션에서 얻어가고자 하는 부분
- 객체관점과 데이터관점 2가지 모두 고려하여 중간지점을 찾는 저만의 기준을 세우고 싶어요.

### 웹 개발 경험
- Spring과 JPA 인강을 듣고 로컬에서 게시판을 혼자 만들어본 경험이 있습니다. 배포한 경험은 없습니다.

<b>예약 정책과 ERD는 README에 적어 두었습니다.</b>

질문은 코멘트에 달아두겠습니다.

2024-05-20 01:11 UTC, Arachneee commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
예약 대기 취소는 어드민 또는 예약 대기를 한 자신만 취소를 할 수 있어 권한을 제한했습니다.
기존에는 어드민에서만 가능한 api는 /admin을 붙여 interceptor를 활용했는데요. 
현재의 경우도 interceptor를 추가하는 것이 좋을까요? 
여러 상황마다 권한이 다를 수 있는데 그 때마다 interceptor를 추가하는 것은 좋지 않다고 생각합니다. 
그런데 controller 객체가 권한 설정 역할까지 하는 것은 많은 책임이 있다고 생각합니다.
비밥은 이런 경우 어떻게 처리하시나요?

2024-05-21 00:07 UTC, pci2676 requested changes
리뷰가 조금 늦었습니다.

고민해볼만한 부분에 리뷰를 남겨두었으니 확인해주세요.

2024-05-21 00:07 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Waiting.java
> +    private Reservation reservation;
status로의 복구를 바라는 것은 절대 아니고 단순한 질문입니다.

>어드민의 예약 목록조회와 예약 대기목록조회 api가 나누어져있다.

status 값을 조건절에 넣어 검색하는 것도 고려해보셨을것 같은데 좋지않다고 생각하신 이유가 궁금합니다.

>어드민만 예약을 취소할 수 있고 유저는 예약 대기만 취소할 수 있다.

테이블 자체의 접근권한을 가지고 있는것이 아니라 개발자가 해당 테이블에 접근하는 코드를 작성하면  
유저도 예약을 취소할 수 있을것 같아보입니다. 이에 대한 고민도 해보신것일까요?

2024-05-21 00:07 UTC, pci2676 commented on src/main/java/roomescape/service/ReservationService.java
> +        return ReservationResponse.createByReservation(newReservation);
3명이 같이 예약요청을 한다고 가정해보았을때

2명은 동시에 요청을 진행하였고

그보다 느린 1명이 이후 예약 요청을 진행하였다고 상황을 가정해보았을 때

예약과 대기의 순번이 어떻게 될 수 있을까요?

ex. 고객 A, B, C

A와 B의 요청 시간은 각각 (00:00:01)  
C의 요청 시간 (00:00:02)  
(초 아래 단위는 동일하다고 가정합니다.)

이때 A와 B와 C의 상태가 각각 어떻게 될지   
고객이 예상할 수 있는 자신의 상태 기대값과 비교해보신적 있으실까요?

2024-05-21 01:47 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Waiting.java
> +    private Reservation reservation;
> status 값을 조건절에 넣어 검색하는 것도 고려해보셨을것 같은데 좋지않다고 생각하신 이유가 궁금합니다.

예약목록은 한 타임에 하나만 존재할 수 있는 것과 달리 예약 대기 목록은 매우 많아 질 수 있습니다.
그런데 예약목록만 가져오기 위해 테이블 전체를 스캔하는 비용이 너무 크다고 생각했습니다.

> 테이블 자체의 접근권한을 가지고 있는것이 아니라 개발자가 해당 테이블에 접근하는 코드를 작성하면
유저도 예약을 취소할 수 있을것 같아보입니다.

api를 사용하는 클라이언트만 생각하고 개발자는 생각해보지 못했습니다. 
`어드민만 예약을 취소할 수 있고 유저는 예약 대기만 취소할 수 있다.`는 어드민 또는 유저로 로그인을 할 수 있는 사용자 관점에서의 정책입니다.
개발자는 로그인도 필요없이 코드를 작성하면 모든일을 다 할 수 있고 할 수 있어야하는데 어떤 부분을 말씀하시는 걸까요?

2024-05-21 04:44 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/WaitingRepository.java
> +    List<WaitingWithRank> findWaitingRankByMemberAndDateAfter(Member member, LocalDate date);
Repository가 너무 많은 역할을 하고 있는 것이 문제일까요? 아니면 서브쿼리의 성능이 좋지 않은 것이 문제일까요?

실제 1000건의 예약 대기를 조회하는 성능을 테스트해봤습니다. 
1번 : 서브쿼리를 활용한 한방쿼리를 보내는 방법(현재 방식) [94ms]
2번: 나의 Waiting을 우선 가져온 뒤 각 Waiting에 대해 count쿼리를 날리는 방법 [390ms]
3번: 전체 Waiting을 가져온 뒤 application에서 count하는 방식 [100ms]

2번의 경우 예약 대기1건마다 count쿼리를 호출하는 방식은 db서버를 여러번 호출해야하므로 성능이 더 안좋습니다. 
1번 3번은 성능이 비슷하지만 3번의 경우 순번 계산 역할을 도메인 객체로 위임할 수 있습니다.

application에서 처리하는 것으로 변경하겠습니다.

2024-05-21 06:34 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationService.java
> +            waitingRepository.delete(waiting);
논리적 삭제를 활용하여 나중에 데이터가 삭제되어도 삭제되었다는 것을 알림 혹은 예약 취소 등으로 보여줄 수 있을 것 같습니다.

2024-05-21 11:21 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationService.java
> +        return ReservationResponse.createByReservation(newReservation);
1초 미만의 동시성은 고려하지 못했습니다.
동시성 테스트 `ReservationConcurrencyTest` 를 추가하여 실행해보니 A, B는 예약이 되고 C는 예약내역이 2개라 find에서 예외가 나와 null 상태가 됩니다.

동시성 문제를 해결하기 위해 `@Lock(LockModeType.PESSIMISTIC_WRITE)`와 `@Transactional(isolation = Isolation.SERIALIZABLE)` 까지 추가했는데 해결하지 못했습니다.
`@Transactional(isolation = Isolation.SERIALIZABLE)` 로는 해결될 줄 알았는데 안됩니다. ㅠㅠ

이 문제를 어떻게 해결해야할까요?

2024-05-21 11:42 UTC, Arachneee commented
안녕하세요 비밥! 

리펙토링을 진행하면서 크게 바뀐 부분(커밋내역)입니다.
1. Service에 노출된 도메인 로직을 도메인 내부로 변경했습니다. 
- [중복 예약 검증](https://github.com/woowacourse/spring-roomescape-waiting/pull/90/commits/637df159efc5e300f89f44d8beb9b965b7b4083a)
- [예약 삭제시 예약 대기 자동 승인](https://github.com/woowacourse/spring-roomescape-waiting/pull/90/commits/1778a830e0b89894411f9390f3f539f1a5273a93#diff-0f311d3f43c1f5f57814cec6f7cb2feb4b8cdedeebadc22b97a91a89bfe2e667)
2. Repository에 있는 도메인 로직을 도메인 내부로 변경했습니다.
- [대기 순번 계산](https://github.com/woowacourse/spring-roomescape-waiting/pull/90/commits/e180003625ad4bc77ab5373c552de8525f855608)

양방향매핑과 영속성전이를 활용하여 최대한 도메인으로 도메인로직을 위치시켰습니다.
이제 도메인에게 역할이 부여되었다는 느낌을 받았고 Spring없이 순수 단위테스트를 할 수 있게되었습니다.
이런 방식으로 도메인에게 역할을 부여하는 것이 JPA를 활용하여 객체지향 설계를 하는 방법이라고 생각됩니다.
비밥은 어떻게 생각하시나요?

2024-05-21 11:45 UTC, Arachneee commented on src/main/java/roomescape/domain/member/Member.java
> +        this.id = id;
도메인 테스트에서 id가 없는 객체를 사용하면 equal이 동작하지 않는 문제가 있었습니다.
프로덕트 코드에는 id가 있는 생성자가 필요없지만 테스트를 위해 생성자를 추가했습니다.
테스트만을 위한 코드라 생각되는데 비밥은 어떻게 생각하시나요?

2024-05-21 11:50 UTC, Arachneee commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
권한에 대한 책임이 Service layer까지 넘어 오는 것이 이해가 잘 되지 않습니다.
Controller에서 끊을 수 있음에도 Service에게 위임했을 때 어떤 이점이 있는지 잘 모르겠습니다.

2024-05-21 23:06 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Waiting.java
> +    private Reservation reservation;
> 개발자는 로그인도 필요없이 코드를 작성하면 모든일을 다 할 수 있고 할 수 있어야하는데 어떤 부분을 말씀하시는 걸까요?
> `개발자가 해당 테이블에 접근하는 코드를 작성하면 유저도 예약을 취소할 수 있을것 같아보입니다.` 이 부분이 잘 이해가 되지 않습니다.
> 권한을 제한하는 책임은 presentation layer에 있고 Service layer 부터는 권한 제한을 두지 않았습니다. Service에서도 권한을 제한해야 한다는 말씀일까요?

아래 이유가 테이블을 나눈 이유라는것이 잘 이해가 되지 않아 드린 질문이었습니다 😄 
>어드민만 예약을 취소할 수 있고 유저는 예약 대기만 취소할 수 있다

무언가 개선을 바라고 드린 리뷰는 아니었고 단순 질문이었습니다.

2024-05-22 00:11 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/WaitingRepository.java
> +    List<WaitingWithRank> findWaitingRankByMemberAndDateAfter(Member member, LocalDate date);
1000건으로 성능에 대한 차이를 가늠하기는 힘들것 같아보입니다.  
가능하시다면 10만건 이상의 데이터를 생성하고 비교해보시면 좋을것 같습니다.

3번의 방식의 경우 count해야하는 대상이 너무 많아지면 메모리에 데이터에 대한 정보를 올리다가 문제가 발생할 수 있어서 저는 피하는게 좋을것 같습니다.

제가 오히려 혼란을 가중시킨 느낌인데요. 😓   

저라면 2번의 방식 혹은 1번의 방식에서 쿼리를 조금 수정하여 join의 방식으로 문제를 해결하려 했을것 같습니다. 서브쿼리의 경우 explain을 통한 쿼리 성능의 예측이 힘들어보이기 때문입니다.

2024-05-22 00:17 UTC, pci2676 commented on src/main/java/roomescape/service/ReservationService.java
> +        return ReservationResponse.createByReservation(newReservation);
여러가지 방법이 있을것 같습니다.

시도하신 것처럼 락을 잡는것도 하나의 방법이 될 수 있을 것 같고

트랜잭션을 끊어서 가는것도 하나의 방법이 될 수 있을것 같습니다.

예를들어 요청이 오면 모두 waiting 으로 저장을 하고 이후 트랜잭션에서 waiting에 있는것중 가장 빠른 waiting을 reseravtion으로 격상하는 방식도 있을것 같습니다.

조금 더 자세하게 설명드리면

1. API 호출
- transaction 1
 - waiting 저장 
- transaction 1 end
- transaction 2
 -  waiting 중 가장빠른 waiting을 reservation으로 저장
- transaction 2 end

위와 같은 형태로 수행하면 요청의 누락은 없고 reservation을 하나만 생성할 수 있을것 같아보입니다.  
물론 조금 더 보완하면 좋을 부분이 있겠지만 거기까지 다루기에는 이번 미션의 범위를 조금 벗어나는것 같아 이렇게만 적어보았습니다.

2024-05-22 00:19 UTC, pci2676 commented on src/main/java/roomescape/domain/member/Member.java
> +        this.id = id;
지금은 domain 객체라고 보신 Member가 영속성 컨텍스트를 위한 객체로도 활용이 되어 발생하는 문제인것 같습니다.

테스트만을 위한 코드는 말씀하신 것 처럼 지양하는 것이 좋습니다.

다만 다른 방법으로 도메인 객체에서 별도의 식별자를 가지는 방법을 고려해볼 수 있을것 같습니다.

2024-05-22 00:33 UTC, pci2676 requested changes
질문에 대한 답변과 코멘트를 남겨두었으니 확인해주세요.

2024-05-22 00:33 UTC, pci2676 commented on src/main/java/roomescape/service/MemberService.java
> +                .orElseThrow(() -> new RoomEscapeBusinessException("회원이 존재하지 않습니다."));
애플리케이션을 운영하다보면 exception 메세지에 있는 정보가 큰 도움이 되는 경우가 많습니다.

지금보다 조금 더 많은 정보를 담아주면 도움이 될 것 같습니다.

2024-05-22 00:33 UTC, pci2676 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional(isolation = Isolation.SERIALIZABLE)
`SERIALIZABLE`로 고립레벨을 설정하면 동시성과 관련된 여러가지 문제점이 해결이 될 수 있지만

성능에 대한 문제가 발생하게 됩니다. 가능하면 추가적인 데이터 구조 혹은 데이터 흐름을 변경하여 해결해보도록 노력해보시면 좋을것 같습니다.

2024-05-22 00:33 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +@SQLDelete(sql = "UPDATE reservation SET is_deleted = true where id = ?")
이것도 나쁘지 않은 방법인것 같긴한데요.

jpa repository를 이용하여 엔터티를 불러올때 유의하지 않으면 원하는 데이터를 불러오지 못하는 경우가 발생할 수 있으니 주의하시면 좋을것 같습니다.

사실 그래서 저는 잘 사용하지 않는 기능입니다. (좋지 않다는 것은 아니니 오해하지마세요~)

2024-05-22 00:33 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    private List<Waiting> waitings = new ArrayList<>();
`@OneToMany`로 연관관계를 엮어야 하는 이유가 있었는지 설명해주실 수 있나요?

2024-05-22 01:41 UTC, Arachneee commented on src/main/java/roomescape/domain/member/Member.java
> +        this.id = id;
> 다만 다른 방법으로 도메인 객체에서 별도의 식별자를 가지는 방법을 고려해볼 수 있을것 같습니다.

어떤 방법을 말씀하시는 건가요?
현재 id로 equal이 재정의 되어 있지만 이를 나머지 필드로 equal을 재정의하는 방법을 말씀하시는 건가요?

2024-05-22 04:10 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +@SQLDelete(sql = "UPDATE reservation SET is_deleted = true where id = ?")
혹시 다른 방법이 있나요? Repository에서 찾을 때마다 조건을 걸어서 찾는 방법을 사용하시나요?

2024-05-22 04:19 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    private List<Waiting> waitings = new ArrayList<>();
도메인이 도메인 로직을 가지고 Service는 비지니스 플로우를 가지는 것이 적절한 역할 분배라고 생각합니다.
도메인에 도메인 로직이 있는 것이 테스트에 용이하고 유지보수에 좋다고 생각합니다.
- [중복 예약 검증](https://github.com/woowacourse/spring-roomescape-waiting/pull/90/commits/637df159efc5e300f89f44d8beb9b965b7b4083a) 
- [예약 삭제시 예약 대기 자동 승인](https://github.com/woowacourse/spring-roomescape-waiting/pull/90/commits/1778a830e0b89894411f9390f3f539f1a5273a93#diff-0f311d3f43c1f5f57814cec6f7cb2feb4b8cdedeebadc22b97a91a89bfe2e667)

 그런데 이 2가지 도메인 로직이 Service 객체에 노출되는 문제가 있었습니다.
그래서 이 문제를 해결하기 위해 양방향 연관관계를 사용했습니다.

2024-05-22 10:36 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationService.java
> +        return ReservationResponse.createByReservation(newReservation);
저는 예약없이는 예약 대기가 존재할 수 없다고 생각하여 Waiting이 Reservation 외래키를 가지고 있습니다.
그래서 예약 대기를 먼저 저장할 수 없습니다.
무결성과 동시성의 트레이드 오프인 것 같습니다.
동시성은 자세히 알지못해 다음 레벨에 알아보겠습니다.

2024-05-22 11:59 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/WaitingRepository.java
> +    List<WaitingWithRank> findWaitingRankByMemberAndDateAfter(Member member, LocalDate date);
inner join으로 변경해봤습니다!

2024-05-22 12:31 UTC, Arachneee commented on src/main/java/roomescape/domain/member/Member.java
> +        this.id = id;
테스트만을 위한 생성자지만 이 정도의 생성자는 추가해도 문제가 없다고 판단했습니다.

2024-05-22 12:49 UTC, Arachneee commented
안녕하세요 찰리!
백호입니다.

코멘트 주신 부분 생각해보고 필요한 부분 반영했습니다.

양방향 연관관계를 이용한 객체구조에대해 더 이야기를 나눠보고 싶어요.

크루들의 예약 대기 구조가 다양하지만 저처럼 양방향을 설정한 크루는 보지못했어요.

저의 구조가 단점도 있겠지만 도메인에 비지니스 로직을 위치시킬 수 있다는 장점이 매우 크다고 생각합니다.

비밥의 생각을 듣고 싶어요.

2024-05-22 16:19 UTC, pci2676 commented on src/main/java/roomescape/service/ReservationService.java
> +        return ReservationResponse.createByReservation(newReservation);
좋습니다 😄

2024-05-22 16:53 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +@SQLDelete(sql = "UPDATE reservation SET is_deleted = true where id = ?")
논리적 삭제된 데이터도 조회해야하는 일이 많아서 매번 조회 조건에 추가해주는 편입니다.

2024-05-22 16:53 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    private List<Waiting> waitings = new ArrayList<>();
>양방향 연관관계를 이용한 객체구조에대해 더 이야기를 나눠보고 싶어요.
크루들의 예약 대기 객체의 구조가 다양하지만 저처럼 양방향을 설정한 크루는 보지못했어요.
저의 구조가 단점도 있겠지만 도메인에 비지니스 로직을 위치시킬 수 있다는 장점이 매우 크다고 생각합니다.
비밥의 생각을 듣고 싶어요.

꽤 어려운 이야기가 될 것 같은데요.

저의 생각을 먼저 말씀 드리면 저는 가능한 연관관계를 맺지 않는 것을 좋아합니다.

jpa 라는 특별한 라이브러리에 도메인 기능이 종속적이게 되는 것에 불편한 경험이 많기 때문입니다.  
애플리케이션의 요구사항은 예상치 못한 방향으로 변경되기도 하는데 기존 정책을 뒤집어야 하는 경우도 있습니다. 이러한 경우 jpa의 특정 영속성 컨텍스트를 이용하는 기능을 사용했다가 변경에 어려움을 겪은적이 있습니다.

그렇다면 절대 사용하지 않느냐? 라고 묻는다면 그렇지는 않습니다.

명백히 생명주기가 일치하는 케이스라면 사용하기도 합니다.

조금 더 풀어서 말하면 생성되는 시기와 제거되는 시기가 언제나 동일하다면 연관관계로(OneToMany) 묶어서 사용하곤 합니다.

이러한 경우라면 cascade와 같은 속성을 사용해도 크게 이질감 없이 사용할 수 있기 때문입니다.

위 말씀을 토대로 다시 정리해보자면, 저는 jpa도 하나의 외부 라이브러리로 바라보고 있기 때문에  
도메인이 해당 라이브러리에 의존하는것을 그다지 선호하는 편이 아닙니다.   

도메인은 가능한 POJO하게 작성하는게 좋다고 생각하는 편이라 기회가 있다면 도메인용 객체와 영속성 컨텍스트용 객체 또한 분리하는 편입니다.

2024-05-22 16:53 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/WaitingRepository.java
> +        group by w.reservation
👍

2024-05-22 16:53 UTC, pci2676 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    private List<Waiting> waitings = new ArrayList<>();
위와 같은 맥락에서 JPA의 특정 기능( 쿼리 조회시 조건절을 포함시키는 등)들에 의존하는것을 선호하지 않는 편입니다. 😄

2024-05-22 16:53 UTC, pci2676 commented on src/main/java/roomescape/domain/member/Member.java
> +        this.id = id;
저도 이 정도의 생성자는 허용해도 나쁘지 않다고 생각하는 편입니다.

>어떤 방법을 말씀하시는 건가요?
현재 id로 equal이 재정의 되어 있지만 이를 나머지 필드로 equal을 재정의하는 방법을 말씀하시는 건가요?

id가 아닌 별도의 unique한 식별자를 말씀드린것이었습니다.

언급해주신 것 처럼 나머지 필드들을 조합할 수 도 있고  
별도의 key를 애플리케이션에서 발급하는 방법도 있을것 같습니다. (ex. UUID)
id는 rdb에 종속된 값이니까요.

2024-05-22 16:53 UTC, pci2676 commented on src/main/java/roomescape/service/ReservationService.java
> +        return ReservationResponse.createByReservation(newReservation);
지금은 조금 이른 감이 있을것도 같네요.

그래도 애플리케이션을 설계하는 부분에 있어 정말 중요한 부분이고 장애 요소로 발생하기 좋은 포인트이니 꼭 알아보시기 바랍니다.

2024-05-22 23:16 UTC, pci2676 requested changes
질문에 대한 답변을 남겨두었으니 확인해주세요.  
이번 단계에서 요구한 사항은 만족한것 같고 더 진행해 볼 내용은 없을것 같습니다.  
다시 PR주시면 머지하겠습니다.

2024-05-26 04:30 UTC, Arachneee commented
안녕하세요 비밥!
동시성에대해 조금 더 생각을 해봤는데요.
기존 객체의 구조가 동시성에 분리한 구조임을 인지했습니다. 그렇다면 처음부터 동시성을 고려해서 설계를 해야할까요? 동시성 문제는 서비스가 확장되어 유저가 많아졌을 때 생기는 문제라고 생각해요. 그래서 너무 먼 미래를 처음부터 생각하여 설계를 하는 것이 맞을지 고민입니다.

기존 객체 구조를 변경하지 않고 동시성 문제를 해결할 수 있는 방법을 생각해서 적용해봤습니다.

2024-05-27 02:01 UTC, pci2676 commented
> 그렇다면 처음부터 동시성을 고려해서 설계를 해야할까요? 동시성 문제는 서비스가 확장되어 유저가 많아졌을 때 생기는 문제라고 생각해요. 그래서 너무 먼 미래를 처음부터 생각하여 설계를 하는 것이 맞을지 고민입니다.

보통 현업에서는 처음부터 고려를 하여 설계를 하는 편이긴 합니다. 그러나 지금은 해당 키워드와 해결방법에 대해 알아두기만 해도 좋을것 같습니다. 😄

2024-05-27 02:09 UTC, pci2676 approved these changes
이번 단계에서 나누어볼만한 이야기는 모두 나누어 본 것 같습니다.

그동안 고생하셨습니다. 머지하겠습니다. 🚀

2024-05-27 02:09 UTC, merged