[3 - 4단계 방탈출 예약 대기] 이상(이건상) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #98
Opened 2024-05-21 13:14 UTC by kunsanglee

안녕하세요 피케이! 😇

로직은 구현했지만 그동안 빠져있던 테스트코드 부채에 너무 힘겨워서 우선 pr 제출 드립니다 죄송해요..
저번에 말씀해주신대로 프로덕션과 테스트 환경의 테스트 데이터 격리를 했습니다.

3단계에 추가된 예약 대기 `Waiting`을 예약과 분리하여 엔티티로 만들었습니다.
현재 단계에서는 예약과 예약 대기가 거의 일치하는 속성을 지녔습니다.
그럼에도 분리한 이유는 예약과 예약 대기가 우발적 중복으로 비슷한 속성을 지니고 있되, 
변경이 생긴다면 다른 이유, 다른 속도로 변경이 생길 것 이라고 생각했습니다. 
또 분리하는데 공수가 크게 들지 않는다는 이유로 분리하였습니다.
그에 대한 리턴으로 중복 로직이 좀 생겼지만, 위 생각으로 인해 어느정도 타협을 하였습니다.
이 이유에 대해서 피케이는 어떻게 생각하시나요??🤔

4단계는 예약 삭제시 우선 순위인 예약 대기가 다음 예약으로 자동 등록되도록 구현했습니다.

그리고 이전 미션에서 이어진 제 코드에 대한 질문이 있습니다.
제 코드는 presentation -> application -> domain 패키지로 분리되어 있는데요,
application 패키지에 있는 서비스 클래스에서는 presentation 패키지에서 들어온 요청 객체를 받아서
domain 패키지에 있는 `ReservationFactory`, `WaitingFactory`, `ReservationScheduler`와 같은 도메인 서비스 객체에 메세지를 보내고있습니다.  애플리케이션 서비스에서 도메인 패키지에 속하는 Repository들을 의존하고 있고, 도메인 서비스들도 의존하고 있는데, 
도메인 서비스에서도 repository를 의존하는게 어색하다는 생각이 많이 들었습니다.

application 패키지에 있는 서비스 클래스에서만 repository들을 의존하고, 도메인 서비스에 해당하는 객체에서는 repository에 대한 의존을 제거하는 것이 적절한지 궁금합니다. 예약 추가, 예약 삭제와 같은 행위를 하나의 애플리케이션 서비스 객체로 만들고, 그 행위를 수행하기 위한 객체들을 도메인 서비스의 매개변수로 넘겨 비즈니스 로직을 수행하게 했어야 했는데, 이 부분을 놓쳐서 의존이 난잡하게 된 것 같습니다.🤯

아무래도 이번 미션에서의 중심이되는 학습목표는 아니지만, 이 기회에 아키텍쳐에 대한 부분도 피케이에게 점검받고 싶은 마음에 질문 올립니다.
감사합니다!! 😊

2024-05-24 14:09 UTC, pkeugine requested changes
안녕하세요 이상!
우선 리뷰가 늦어서 죄송해요.
늦은 김에 이상이 말해주신 것처럼 프로젝트 구조까지 싹 다 봤어요.
보니까 구조와 테스트에 꽤나 신경쓰고 계신 것 같았어요.
관련하여 고민이 있다면, 코멘트 남겨주시면 같이 대화해볼 수 있을 것 같네요!

워낙 꼼꼼하게 잘 만들어주셔서 그냥 간단한 리뷰와 질문 몇 개 남겨봤습니다.
한 번 확인해주시고, 질문 있다면 언제든지 DM 도 환영입니다 😄

2024-05-24 14:09 UTC, pkeugine commented on src/test/java/roomescape/domain/ReservationSchedulerTest.java
> +    }
꽤 처리할게 많은 테스트인데도 잘 검증해주셨고, 테스트도 잘 읽히네요.
테스트 자체를 꽤 잘 다루시는군요?

2024-05-24 14:09 UTC, pkeugine commented on src/test/java/roomescape/domain/ReservationTest.java
> +    }
정말 구체적으로 테스트를 만들어주셨네요 👍
확실히 꼼꼼하게 테스트를 하려면 시간이 오래걸리죠? 😂

2024-05-25 03:19 UTC, kunsanglee commented on src/main/java/roomescape/config/DataInitializer.java
> +public class DataInitializer implements CommandLineRunner {
이번 반영에서 프로덕션에 데이터 삽입을 위한 DataInitializer를 삭제하겠습니다. 감사합니다 😊

2024-05-25 03:22 UTC, kunsanglee commented on README.md
> +  token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.vcK93ONRQYPFCxT5KleSM6b7cl1FE-neSLKaFyslsZM
미션에서 기본 예시로 사용된 `/reservations-mine` 같은 경우 계층적으로 표현된 자원이라고 인식되지 않았습니다.
그래서 기존에 `/reservations` 자원에 속하는 접근으로 `/reservation/my` 또는 `/reservation/mine`으로 변경을 생각했습니다. 😇

2024-05-25 03:36 UTC, kunsanglee commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +@DomainService
클린 아키텍쳐에 대해서 조금 찾아보고 학습한 내용에 대해서 미션에 적용하다보니, 미션에서 추구하는 학습 목표와는 별개인 것들이 생겨났네요 🥲 

지난 미션에서 예약을 생성할 때 지난 날짜에 대한 검증을 서비스 레이어에서 수행하게 했었습니다. 
하지만 비즈니스 로직이 서비스 레이어에 노출되었다고 생각해서 도메인에게 책임을 부여해야 했는데요,
예약 도메인 자체의 생성시 검증하게 되면, DB에서 조회하여 예약 객체를 생성시 저장되었던 과거 날짜를 가진 예약을 생성해야 하기 때문에 예외가 발생하는 문제가 있었습니다.

그래서 도메인이 가져야할 책임이지만, 예약 도메인 객체가 가져야할 책임은 아니라고 생각이 들었습니다. 또 비즈니스 로직을 서비스 계층이 아닌 도메인 계층에서 처리해야 했으므로, 신규 예약 생성의 책임을 갖는 도메인 객체를 만들었습니다. 여기에 더해 단순 도메인 객체 보다는 도메인 계층에 존재하는 도메인 객체들을 사용해서 비즈니스 로직을 수행하는 도메인 서비스라는 생각을 전달하기 위해 `@DomainService`라는 의미를 명시적으로 나타내는 애너테이션까지 만들게 되었습니다. 🥲

2024-05-25 03:51 UTC, kunsanglee commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +    private final WaitingQueryRepository waitingQueryRepository;
```java
if (reservation.isPast(clock)) {
    throw new RoomescapeException(RoomescapeErrorCode.DATE_EXPIRED);
}
```
말씀해주신 내용을 듣고나니 제가 보기에도 `ReservationScheduler#cancel` 메서드 내에서 굳이 비즈니스 로직이라 할 수 있는 부분은 위 코드에서 `예약이 현재보다 과거인가?`를 확인하는 부분밖에 없는데, `ReservationService#cancel`에서 수행해도 되는 부분을 굳이 도메인 서비스로 분리한 것 같은데 잘 이해한게 맞을까요?? 😅

2024-05-25 03:55 UTC, kunsanglee commented on build.gradle
> +    implementation("com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.1")
지난 pr에서 jpa를 사용하면서 만들어지는 쿼리에 바인드되는 변수를 볼 수 있도록 하라고 말씀하셔서 적용했습니다.
```
logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
```
이런 옵션을 적용하는 선택지도 있었지만, 적용해보니 외부 라이브러리를 적용한 포맷이 바인드 변수를 확인하는데 아주 조금 더 좋아보였습니다. 😅 그냥 하이버네이트의 옵션으로 변경하는게 좋을까요??

2024-05-25 04:01 UTC, kunsanglee commented on src/main/java/roomescape/application/ReservationService.java
> +    }
저도 이 코드 작성할 때 메서드로 분리 할까 말까 고민이 되었는데, 피케이가 보시기에 전자가 더 가독성이 좋군요!
흐름을 따라갈 수 있도록 분리하지 않는 것으로 변경하겠습니다! 😇

2024-05-25 04:09 UTC, kunsanglee commented on src/main/java/roomescape/domain/repository/WaitingQueryRepository.java
> +                and w2.id < w.id)
현재 제 코드에는 `create_at`과 같은 시스템 컬럼이 없기 때문에 
기본키 생성 전략이 `GenerationType.IDENTITY`로 유일성이 보장되는 식별자인 `id`로 비교해도 문제가 없다고 생각했습니다.😇

2024-05-25 05:03 UTC, pkeugine commented on README.md
> +  token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.vcK93ONRQYPFCxT5KleSM6b7cl1FE-neSLKaFyslsZM
그렇군요! 👍 
이왕 restful 하게 해보는거, `mine` 이라는 명사로 만들어줘보죠 ㅋㅋㅋ

2024-05-25 05:13 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +@DomainService
일단 해당 어노테이션은 정말 잘 만들어주셨다고 생각해요.
사실상 마킹하기 위한 어노테이션인데, 그것만으로도 구조를 이해하는데 큰 도움이 되거든요.

> 예약 도메인 자체의 생성시 검증하게 되면, DB에서 조회하여 예약 객체를 생성시 저장되었던 과거 날짜를 가진 예약을 생성해야 하기 때문에 예외가 발생하는 문제가 있었습니다.

이 말이 정확히 이해가 되지는 않아요. 🥲 
예약이 생성된 시간과, 예약시간은 다르지 않나요?

2024-05-25 05:23 UTC, pkeugine commented on build.gradle
> +    implementation("com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.1")
아뇨! 괜찮다고 생각해요.
질문을 남길 때 잘못되었기 때문에 남기지만은 않아요 ㅋㅋㅋㅋ
그런데 제가 저걸 안 써봐서 그러는데, `spy.log` 는 필수로 git 에 올려야하는건가요?

2024-05-25 05:25 UTC, pkeugine commented on src/main/java/roomescape/application/ReservationService.java
> +    }
ㅋㅋㅋㅋ 작성 스타일은 사람마다 느끼는게 다 다르겠지만, 저도 메서드 분리를 할지말지 고민을 했을 것 같아요.
변경 👍

2024-05-25 05:25 UTC, pkeugine commented on src/main/java/roomescape/domain/repository/WaitingQueryRepository.java
> +                and w2.id < w.id)
좋은 답변입니다!!

2024-05-25 11:04 UTC, kunsanglee commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +@DomainService
JDBC를 이용해서 저장된 예약을 조회시, 생성자에 검증 로직이 있는 경우 과거 날짜로 저장된 데이터가 검증에서 과거 날짜 예외를 터뜨렸습니다. JPA의 경우 기본 생성자로 객체 생성 후 reflection으로 객체에 값을 할당하기 때문에 생성시 검증 로직으로 인한 예외는 없을 것 같습니다.

사실 JDBC 때 지난 날짜에 대한 검증은 정확히 따지면 `Reservation`이 가지는게 아니라, `새로운 객체 생성` 이라는 책임을 지니는 객체가 가지는게 맞다고 생각하여 `ReservationFactory` 객체가 가지게 하였던 것인데, 
JPA를 사용하는 지금 시점에는 그냥 `Reservation` 객체가 해당 검증을 가지게 하는게 더 적절할까요? 🤯

2024-05-25 11:05 UTC, kunsanglee commented on build.gradle
> +    implementation("com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.1")
저도 처음봐서 일단 올려볼까..? 하는 마음으로 올렸는데 역시 git ignore하는것이 더 좋았겠네요 😢 죄송합니다.

2024-05-25 11:10 UTC, kunsanglee commented on src/main/java/roomescape/domain/repository/WaitingQueryRepository.java
> +    Optional<Waiting> findCandidateWaiting(LocalDate date, Time time, Theme theme);
아 First가 더 명쾌한 네이밍이네요 반영하겠습니다 😇

2024-05-25 11:21 UTC, kunsanglee commented on src/main/java/roomescape/exception/RoomescapeErrorCode.java
> +    DATE_EXPIRED(HttpStatus.CONFLICT, "이미 지난 과거의 요청은 처리할 수 없습니다."),
커스텀 예외와 에러코드를 만들어서 사용하는데 있어서 궁금한 점이 있는데요,
지금은 `roomescape`라는 하나의 모듈만 있어서 에러코드도 한 개가 있는 상태입니다.
그래서 다른 모듈이 추가되면 그에 대응하는 커스텀 예외와 에러코드도 추가한다는 개념으로 생각하고 있습니다.

그런데 커스텀 에러코드가 지금은 몇개 없다고 하지만 서비스가 점점 커져서 예외 상황이 늘어나 에러 코드가 100개가 되면 오히려 관리하기 어려울 수 있다 라는 의견을 본 적이 있습니다. 하지만 제 생각에는 하나의 모듈이 성장하더라도 예외가 기하급수적으로 늘 것 같지는 않은데 이런 경우에 대해서 피케이는 어떻게 생각하시나요? 🤔

그리고 `RoomescapeErrorCode`에서 값으로 `HttpStatus`를 정의해두고 도메인을 포함한 모든 계층에서 예외를 발생시킬 때 사용하고 있는데, HttpStatus는 presentation 응답의 성격을 가져서 부적절하지 않냐는 의견을 본 적 있는 것 같아요. 그렇다고 status 대신 임의로 정의한 숫자를 사용한다고 하더라도 사실상 HttpStatus code와 다를바가 없다고 생각하여 status로 사용하고 있었는데요, 이 부분에 대해서도 어떻게 생각하시는지 궁금합니다. 🤯

2024-05-25 12:14 UTC, kunsanglee commented on src/main/java/roomescape/application/WaitingService.java
> +    public List<WaitingWithRankResponse> reserveWaiting(LoginMember loginMember, WaitingRequest request) {
네 현재 제가 머리속에 가지고 있는 개념은 이렇습니다.(솔직히 제대로 학습한 개념이 아니라 자신이 없습니다..😢)

예를들어`새로운 예약 생성` 이라는 요청을 `application` 서비스 객체로 만들어서 클라이언트에게 받은 요청에 대한 검증, 권한 검사, 트랜잭션을 관리하는 책임을 가집니다.

`domain` 서비스는 application 서비스 객체에게서 위임받은 요청을 해결하기 위해 여러 도메인과 상호작용하며 비즈니스 로직을 구현하고 처리하는데 집중합니다.

2024-05-25 12:21 UTC, kunsanglee commented on src/main/java/roomescape/application/ReservationService.java
> +        return reservationQueryRepository.findByCriteria(memberId, dateFrom, dateTo, themeId).stream()
헉 놓쳤네요! 순서가 엇나가는 것을 좋아하지 않아서 변경하는 편입니다.
별거 아닌 것 또한 좋게 봐주셔서 감사드립니다 피케이 😇

2024-05-25 12:25 UTC, kunsanglee commented on README.md
> +
아.. `예약 대기 관리 기능 구현`, `예약 대기 거절 기능 구현` 이렇게 커밋 메세지를 남겨서 보시기에 헷갈릴 수 있겠군요.. 🥲
커밋 메세지도 좀 더 가독성 좋게 남기도록 노력하겠습니다! 😄

2024-05-25 12:34 UTC, kunsanglee commented on src/main/java/roomescape/domain/Waiting.java
> +public class Waiting {
말씀해주신 얘기를 들으니 예약에 다양한 상태가 추가된다면 하나의 도메인에서 관리하기 수월하겠군요 🫨
레벨 1에서 객체지향을 집중하여 공부할 때에는 최대한 분리하는 것을 지향하여 연습했었는데, 
DB에 데이터를 저장하고 조회해야하는 숙명을 지닌 후로는 객체지향과 DB IO와의 트레이드 오프를 생각해야 해서 정말 어렵네요..
어떻게 해야 이런 부분에 잘 적응할 수 있을까요? 😣

2024-05-25 12:40 UTC, kunsanglee commented on src/main/java/roomescape/application/dto/AvailableTimeResponse.java
> +) {
아 dto의 의존 방향이 거꾸로 되었네요 🤯
짚어주셔서 감사합니다!! 😊

2024-05-25 12:55 UTC, kunsanglee commented on src/main/java/roomescape/domain/ClockConfig.java
> +
`ClockConfig`와 같은 설정 클래스는 스프링 프레임워크에 대한 의존성을 가지므로 도메인 계층에 있으면 안되겠네요! 🤯
infrastructure 패키지로 이동하겠습니다! 😢

2024-05-25 13:02 UTC, kunsanglee commented on src/test/java/roomescape/domain/ReservationSchedulerTest.java
> +    }
아이고 아닙니다.. 😅
좋게 봐주셔서 감사합니다. 
칭찬해주시니 테스트를 더 열심히 작성하고 싶어지네요!! 😇

2024-05-25 13:03 UTC, kunsanglee commented on src/test/java/roomescape/domain/ReservationTest.java
> +    }
당연히 작성해 두었어야 할 테스트들이 밀려있어서 그 부담감이 좀 컸습니다 😭
세세히 봐주셔서 감사합니다! 😊

2024-05-26 06:14 UTC, kunsanglee commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +    public void cancel(Long reservationId) {
`@Transactional`의 propagation 옵션

- `REQUIRED`
디폴트 값으로 사용됩니다. 다른 메서드와 트랜잭션을 공유할 수 있는 가장 일반적인 시나리오에 적합합니다. 예를 들어, 여러 데이터베이스 업데이트를 하나의 트랜잭션으로 묶고 싶을 때 사용합니다.

- `REQUIRES_NEW`
독립적인 트랜잭션이 필요한 경우에 사용됩니다. 예를 들어, 현재 진행 중인 트랜잭션과 관계없이 항상 새로운 트랜잭션을 시작해야 할 때 사용합니다. 이는 로깅, 메시지 전송 등의 작업에 유용할 수 있습니다.

이 밖에도 여러 옵션이 있지만, 아직 위의 두 옵션 이외에는 어떤 상황에 사용해야 할지 모르겠네요. 🤯

2024-05-26 06:33 UTC, kunsanglee commented on src/main/java/roomescape/domain/ReservationFactory.java
> +    public Reservation create(Long memberId, LocalDate date, Long timeId, Long themeId) {
아 `ReservationService`의 create 메서드에서 `@Transactional` 애너테이션을 붙여서 이미 트랜잭션을 시작하고, `ReservationFactory`의 create 메서드를 호출하기 때문에 먼저 만들어진 트랜잭션에 포함되어 사실 따로 트랜잭션 애너테이션을 왜 붙여야 하지 생각했었습니다. 

프로덕션 코드에서는 트랜잭션 범위에 잘 포함되어있지만 `ReservationFactory` 만 독립적으로 테스트할 때는 트랜잭션이 적용되지 않는군요! 🫨

혹시 이거 말고도 현재 상황에서 붙여야할 이유가 있을까요? 제가 놓친 점이 있다면 알려주세요 피케이 🥲

2024-05-26 14:18 UTC, pkeugine commented on src/test/java/roomescape/domain/ReservationSchedulerTest.java
> +    }
(assertThat 을 `assertAll` 이나 `assertSoftly` 와 같은 것으로 묶어주면 더 완벽할 것 같아요!)

2024-05-26 14:24 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +@DomainService
🤔 이상의 목표에 맞게 구현하는게 맞을 것 같아요.
어느 시점에 예외가 터졌으면 하는지에 대한 목표가 있다면,
딱히 구조에 대한 고민보단 그에 맞는 위치에 두는게 맞다고 생각합니다.

2024-05-26 14:24 UTC, pkeugine commented on build.gradle
> +    implementation("com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.1")
죄송할 이유 없습니다 ㅋㅋㅋ

2024-05-26 14:26 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationScheduler.java
> +    public void cancel(Long reservationId) {
아 propagation 말고도 isolation 이라던지, 좀 더 넓은 범위의 옵션을 말한거였습니다!

2024-05-26 14:29 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationFactory.java
> +    public Reservation create(Long memberId, LocalDate date, Long timeId, Long themeId) {
맞아요 의무는 아니에요.
이상이 말해주신 것 외에도
`ReservationFactory` 는 단독적으로도 쓰일 수 있으니까, 예방차원에서 붙이는 의미가 커요.
너무나도 급한 상황이라면... 누군가는 controller 에서 쓸 수도 있거든요.
... 안 그럴거같죠? 👻 😂

2024-05-26 14:37 UTC, pkeugine commented on src/main/java/roomescape/exception/RoomescapeErrorCode.java
> +    DATE_EXPIRED(HttpStatus.CONFLICT, "이미 지난 과거의 요청은 처리할 수 없습니다."),
저는 관리하기 어려울 것 같다는 편에 있긴해요.
메시지를 한 곳에 모으면서 관리 포인트를 하나 추가하는거라서요.
그리고 예외코드를 한 곳에 몰아서 관리하는 것처럼, 여러 곳에서 사용하는 코드를 한 곳에 모아두면
여러 개발자가 동시다발적으로 개발하고 있을 때 충돌이 발생하기 정말 쉽습니다.
그래서 그 충돌이 일어나지 않게 조심해야할 것 같아요.

어떤 경우에는 여러 팀이 하나의 프로젝트 또는 repository 에서 공동으로 작업하는 경우도 있어요.
그럴 땐 정말 많은 예외코드가 생길 것 같긴하네요 🤔 

`http status` 관련해서는, 사실 저희 팀에서도 며칠 전에 관련된 얘기를 하긴 했었습니다 ㅋㅋㅋ
저는 뭐든 상관없다 느낌이긴 한데, 그러다보니 오히려 http status 관련 정보가 여러 곳에 들어가도 괜찮다는 생각을 가지고 있어요.
아직까지는 그게 응답에 직접적으로 들어가있다고 해서 딱히 유지보수의 어려움을 겪진 못했던 것 같네요.
오히려 예외 터지는 위치에서 바로 알 수 있어서 편했기 때문에...
이론과 실제로 느껴보는건 다를 수도 있구나라는 생각을 했던 것들 중 하나입니다.

물론 반대 의견도 이해가 가긴해요.
그래서 저는 팀원이 하지말자고 하면 존중해줄 수 있습니다.

2024-05-26 14:38 UTC, pkeugine commented on README.md
> +
헐 다른 메시지였군요... 🤯
왜 같은 걸로 보였을까요... 이거야말로 제가 죄송합니다... ㅋㅋㅋ

2024-05-26 14:43 UTC, pkeugine commented on src/main/java/roomescape/domain/Waiting.java
> +public class Waiting {
다양한 시도를 해보면서 그냥 그 경험을 토대로 본인 생각을 가져가는게 좋은 것 같아요.
아무래도 저를 포함한 꽤 많은 사람들이 데드라인, 꽤 많은 양의 레거시 코드, 퇴근 후 본인 시간 확보, 팀원들과의 의견 취합과 같은 요소를 객체지향보다 우위에 두고 있는 것일수도 있어요 ㅋㅋㅋㅋㅋㅋ
물론 이상이 말해주신 기술적인 것들도 당연히 고려되구요.

최대한 많이 경험해보세요!
그 경험이 별로였다면 오히려 좋은겁니다.
유지보수하기 힘든 레거시를 만드는 방법을 찾은거니까, 그걸 피하면 되는거니까요 :)

2024-05-26 14:51 UTC, pkeugine commented on src/main/java/roomescape/application/dto/AvailableTimeResponse.java
> +) {
아 네, `application 에서 응답 dto 를 반환하는 것을 지양해보자` 라고 하는게 더 알맞은 말이었던 것 같긴하네요 🙇 

이미 이에 대해 고민하셨다면 패스해도 괜찮습니다!

2024-05-26 14:54 UTC, pkeugine requested changes
안녕하세요 이상!
리뷰 잘 반영해주셨고, 정말 많은 것들에 대해 얘기 나눠봤네요.
머지해도 될 정도이지만, 아직 남은 시간이 있으니 마지막 request change 를 할게요.
더 바꾸고 싶은게 남아있다면 해주시면 됩니다.
얼마 남지 않은 미션 조금만 더 파이팅입니다! 🔥 🔥 🔥

2024-05-26 15:47 UTC, pkeugine approved these changes
고생하셨어요 이상!
이번 미션을 통해 많이 배워갔으면 하는 마음입니다.
앞으로 남은 미션도 파이팅이에요!!!
이만 머지하도록 하겠습니다 :)

2024-05-26 15:47 UTC, merged