[3 - 4단계 방탈출 예약 대기] 커비(이현지) 미션 제출합니다.
woowacourse/spring-roomescape-waiting pull request #99
Opened 2024-05-21 13:43 UTC by skylar1220

안녕하세요 러너덕 커비에요!

3-4단계는 빠르게 기능 구현 후, 리뷰를 통해 이야기를 나눠보며 개선해보고자했어요!

예약과 예약 대기가 비슷하면서 다른 속성을 갖고있어서 엔티티부터, 서비스, 컨트롤러를 각각 가져야하나, 통합해야하나 고민을 가장 많이 했어요. 

Waiting 테이블을 추가하는 방식으로 엔티티 구조를 짠 이유는,

> 장점 

1. 예약 대기 데이터만 갖고 로직을 처리할 일(예: 예약 대기 순번)이 많기에 조회에 유용할 것이라고 생각했어요.
2. 예약 테이블에서 대기까지 관리한다면 하나의 예약 당 다수의 예약 대기를 갖고있을텐데, 예약을 조회할 때 나머지 대기까지 전체 탐색을 해야하기에 분리를 선택했어요.
3. 예약 엔티티에는 수정사항이 없기때문에 기존의 테스트 코드들을 수정하지 않아도 된다는 이점도 있었어요.

> 단점

Reservation 엔티티와 동일한 필드를 갖고 있어서 중복이라는 찝찝함이 들었지만, 필드만 동일할 뿐 사용되는 목적이 다르기에 감수할 수 있는 점이라고 생각합니다!

`내가 쓴 코드 한줄한줄에 이유와 장단점을 설명할 수 있기`를 레벨2 학습 목표로 잡은 만큼, 
코드에 대한 근거를 늘려가는 리뷰 과정이 되도록 노력해보겠습니다!
감사합니다☺️

2024-05-23 13:47 UTC, Deocksoo requested changes
안녕하세요 커비, 리뷰 기다려주셔서 감사해요 🙇 
Waiting 객체를 따로 분리해서 구성하신 것이 좋네요 👍 
중복되는 부분이 있지만, 역할이 더 잘 구분되어 보이는것같아요.
테스트도 꼼꼼하게 잘 작성해주셨네요.

고민해보시면 좋을 만한 부분에 코멘트 남겨두었으니, 확인 한 번 부탁드려요.

2024-05-23 13:47 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +                    Long rank = waitingRepository.countAllByDateAndTimeAndThemeAndIdLessThanEqual(
rank 계산을 DB에서 하게 되는군요.
지금은 이 계산을 application으로 올리려면 약간 복잡하겠어요.
저장할 때 rank도 함께 계산해서 저장하는 방식도 고려해보셨을 것 같은데, 이 방식과 비교하면 어떤가요?

2024-05-23 13:47 UTC, Deocksoo commented on src/main/java/roomescape/domain/ReservationWithWaiting.java
> +    public static List<ReservationWithWaiting> of(final List<Reservation> reservations,
이 부분은 이번 구현 요구사항에서 상당히 중요한 역할을 하는 기능일 것 같은데요.
단위테스트를 추가해보는 것은 어떤가요?

2024-05-23 13:47 UTC, Deocksoo commented on src/main/java/roomescape/domain/ReservationWithWaiting.java
> +public class ReservationWithWaiting {
필요에 따라 이렇게 도메인 객체를 새로 구성하신 부분이 좋네요 👍 
다양한 로직이 추가될수록 점점 응집도 높은 객체가 되겠네요.

다만 객체의 이름이 적절한지 조금 더 고민해보시면 좋겠어요. 지금은 with waiting이 객체가 무슨 역할을 하는지 약간 헷갈리게 만드는거같아요.
그리고 중요한 객체일수록 그 객체의 이름으로 소통하게 될 일이 많아지는데요. 약간 과하다고 생각할 수 있지만, 객체의 발음도 중요해요.
로버트 C 마틴의 저서 <클린코드>에는 '발음하기 쉬운 이름을 사용하라. 발음하기 어려운 이름은 토론하기도 어렵다. 바보처럼 들리기 십상이다.' 라는 구절이 있어요.

객체의 이름을 들었을 때 직관적으로 의미를 파악할 수 있는 더 좋은 이름은 없을까요?
혹은 다른 Entity들의 이름을 따로 구분해주고, 이 객체의 이름을 Reservation 으로 가져가는 것도 방법이겠네요.

2024-05-23 13:47 UTC, Deocksoo commented on src/main/java/roomescape/domain/WaitingWithRank.java
> +public class WaitingWithRank {
👍

2024-05-23 15:27 UTC, skylar1220 commented on src/main/java/roomescape/config/MemberLoginInterceptor.java
> +            response.setStatus(401);
더 가독성이 좋겠네요. 반영하겠습니다!

2024-05-23 15:30 UTC, skylar1220 commented on src/main/java/roomescape/config/WebMvcConfig.java
> +                .addPathPatterns("/reservation-mine");
chaining 하는 것이 각 인터셉터에 해당되는 pattern들을 잘 보여줄 수 있을 것 같습니다!

2024-05-23 15:32 UTC, skylar1220 commented on src/main/java/roomescape/domain/Waiting.java
> +    public Waiting() {
프록시 객체 생성을 위해 최소한의 접근제어자인 protected로 변경하겠습니다!

2024-05-23 15:35 UTC, skylar1220 commented on src/test/java/roomescape/service/WaitingServiceTest.java
> +        Member otherMember = memberRepository.save(new Member("runnerDuck", "runnerDuck@email.com", "runnerDuck", Role.USER));
아하 프로필을 보고 오리로 생각했나봅니다😂

2024-05-23 15:38 UTC, skylar1220 commented on src/main/java/roomescape/domain/Waiting.java
> +    public Waiting(final Long id, final Member member, final LocalDate date, final ReservationTime time,
id를 넣어주는 상황이 있지 않을까? 하는 생각으로 생성해두었었는데, 
id 생성 전략이 db에서 auto generated 된 id를 가져오는 것이기도하고, DB와의 정합성을 생각했을 때 
id를 지정하게 하는 해당 생성자는 제거하는 것이 적절하겠네요!

2024-05-24 08:18 UTC, skylar1220 commented on src/main/java/roomescape/service/WaitingService.java
> +                    Long rank = waitingRepository.countAllByDateAndTimeAndThemeAndIdLessThanEqual(
> 저장할 때 rank도 함께 계산해서 저장하는 방식

이 rank를 테이블의 column으로 관리하는 방식을 이야기 하는 것이 맞을까요?
다음 이유들로 해당 방식의 리소스가 더 크다고 생각합니다.

1. 1번째 예약 대기를 취소했을 때, 관련된 모든 예약 대기 row에 업데이트 쿼리를 날려야하는 점.

횟수도 내가 이김.

업데이트는 다 날라가는데

셀릭트는 내가 원하는 그 해당 경우에만 카운트 셀렉트 쿼리 한 번 나감

수정이 많이 생기는 데이터에 대해서느 컬럼으로 두면 안된다.

데이터 정합성 때문에? → 의도와 다르게 잘못된 값을 업데이트 하는 상황?

만약 어떤 로직이 누락된다면, 내부 로직적으로, 업데이트 →내가 그 계산 서비로직

카운트, 카운트 db를 믿고 누락이나 신뢰의 문제가 덜 일어날듯

2024-05-24 09:31 UTC, skylar1220 commented on src/main/java/roomescape/domain/ReservationWithWaiting.java
> +    public static List<ReservationWithWaiting> of(final List<Reservation> reservations,
네 추가해보았습니다!

2024-05-24 10:04 UTC, skylar1220 commented on src/main/java/roomescape/domain/ReservationWithWaiting.java
> +public class ReservationWithWaiting {
현재는 예약, 예약대기 상태뿐이지만 만약, 결제전예약 등의 상태가 더 추가된다면 현재 이름이 문제가 되겠다는 생각도 추가적으로 드네요.
따라서, 예약과 예약 대기 등을 모두 포함하는 '예약 항목'들이라는 의미의 ReservationEntry로 변경했습니다!

2024-05-25 15:22 UTC, Deocksoo approved these changes
미션 종료하려다가, 한 가지만 더 이야기 나눠보면 좋을것같아서 다시 팬딩해요. 리뷰 추가로 남겨둘게요.

2024-05-25 15:22 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +        if (waitingRepository.existsByDateAndTimeAndTheme(reservation.getDate(), reservation.getTime(), reservation.getTheme())) {
이 if문은 꼭 필요한가요?

2024-05-25 15:24 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +        if (waitingRepository.existsByDateAndTimeAndTheme(reservation.getDate(), reservation.getTime(), reservation.getTheme())) {
이 if문은 꼭 필요한가요?

2024-05-25 15:31 UTC, Deocksoo commented on src/main/java/roomescape/domain/ReservationEntry.java
> +public class ReservationEntry {
이제 도메인 객체와 엔티티가 조금 구분되기 시작했네요.
패키지를 나누어 관리해봐도 좋겠어요.

2024-05-25 15:54 UTC, Deocksoo requested changes
안녕하세요 커비,
머지하기 전에 조금 더 고민해보시면 좋을 만한 부분이 있을것같아 코멘트 남겨두었어요 :)
확인 한 번 부탁드려요.

2024-05-25 15:54 UTC, Deocksoo commented on src/main/java/roomescape/domain/Waiting.java
> +public class Waiting {
현재 Waiting에서는 Reservation에서 가지고 있는 정보들을 그대로 비정규화해서 다시 들고 있는 형태죠.
그래서 예약 대기를 생성하는 과정에서 검증할 때에도 비정규화된 정보들을 모두 일일이 고려해야 해요. 이 과정이 꽤나 복잡하죠.

반면 Waiting에서 Reservation을 알고있도록 하고, 비정규화된 데이터들을 모두 없애는 것도 한가지 방법일 것 같아요.
두 가지를 비교하면 어떤 방법이 더 나은가요?

2024-05-25 15:54 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +        if (waitingRepository.existsByDateAndTimeAndTheme(reservation.getDate(), reservation.getTime(), reservation.getTheme())) {
이 if문은 왜 필요한가요?

2024-05-26 04:57 UTC, skylar1220 commented on src/main/java/roomescape/domain/ReservationEntry.java
> +public class ReservationEntry {
정말 패키지 분리 시점이 보이네요. 반영하겠습니다!

2024-05-26 05:02 UTC, skylar1220 commented on src/main/java/roomescape/service/WaitingService.java
> +        if (waitingRepository.existsByDateAndTimeAndTheme(reservation.getDate(), reservation.getTime(), reservation.getTheme())) {
예약과 동일한 날짜,시간,테마인 예약 대기가 있는 경우에만 
아래의 '해당 예약 대기를 예약으로 전환하는 로직'을 실행하기 위해 넣어주었습니다!

2024-05-26 09:48 UTC, skylar1220 commented on src/main/java/roomescape/domain/Waiting.java
> +public class Waiting {
### 💡 기존 방식: 비정규화, 중복 필드

> 장점

- 조회 등을 할 때 join을 하지 않아 성능 유리

> 단점

- 데이터를 중복저장하므로 더 많은 저장 공간이 필요
- 어느쪽 데이터가 믿을만한가?의 문제 발생, 데이터 간의 일관성이 깨질 수 있음.


### 💡 Waiting에서 Reservation을 알고 있게 하는 방식, 정규화

> 장점

- 중복 데이터 제거로 저장 공간 최소화
- '예약'으로 데이터를 비교함으로써 기존에 날짜, 시간, 테마를 갖고 비교하던 로직에 비해 간단해지고 오류 가능성이 적어짐
- 예약 없이는 예약 대기가 있을 수 없다는 정책과 부합
- 요구사항을 최소한의 변경으로 반영 가능

> 단점

- 조회 시 join이 사용되며 성능 문제 발생
- 동시성 문제: 만약 두개의 예약이 동시에 들어오면 예약 생성 전에 2개의 예약 대기를 만들어야할 수도 있는데 그게 안됨
- waiting이 reservatoin 객체를 갖고있으면서 그 안의 member를 알 수 있게됨.
   - 예약 대기가 기존 예약자의 이름을 알 수 있게되는 것이 맞는가? 하는 문제.

### 💡 기타: Schedule 엔티티

- 날짜, 시간, 테마를 포함하는 schedule 엔티티를 Reservation, Waiting이 각각 갖는 방식
- 단점: reservation, waiting 모두 해당 schedule 엔티티를 join해서 사용하므로 join이 자주 발생하게됨.

위와 같은 방식별 장단점들이 있다고 생각합니다.
현재는 중복 필드 제거를 통한 데이터의 일관성과 복잡한 로직의 개선에 장점이 크다고 생각하여 
Waiting에서 Reservation을 알고 있게 하는 방식(정규화)을 적용해보겠습니다!

2024-05-26 17:24 UTC, Deocksoo requested changes
안녕하세요 커비, 
구조를 잘 변경해주셨네요 👍 관련 로직들도 조금 더 단순해진 것 같군요.
궁금한 부분이 있어 코멘트 남겨두었으니 확인 한 번 부탁드려요.

2024-05-26 17:24 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +    public void convertWaitingToReservation(final Reservation reservation) {
이런 로직은 트렌젝션 처리가 꼭 필요하겠네요.
member를 set 하고 waiting을 delete 하는 과정이 하나의 트렌젝션으로 잡혀야 할테고, setMember에서 JPA 더티체킹도 되어야할테니까요.
지금 더티체킹은 잘 되고있는것같은데, 트렌젝션이 어디에 잡혀있는지 찾기가 어렵네요. 어떻게 동작하는건가요?

2024-05-26 17:25 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +        if (waitingRepository.existsByDateAndTimeAndTheme(reservation.getDate(), reservation.getTime(), reservation.getTheme())) {
아하 분기가 꼭 필요하겠군요.

2024-05-27 08:41 UTC, skylar1220 commented on src/main/java/roomescape/service/WaitingService.java
> +    public void convertWaitingToReservation(final Reservation reservation) {
그동안 `필요성이 정말 느껴지면 도입하자!` + 아래와 같은 이유로 트랜잭션을 도입하지 않았었는데요.

### 트랜잭션 처리를 하지 않았던 이유
1. 더티체킹 ok
어차피 repository의 메서드를 호출하면 commit이 되고, 그 때 더티체킹이 되지 않나?
2. 영속성 컨텍스트 ok
osiv가 true로 되어있으니 영속성 컨텍스트를 걱정할 필요도 없지 않나?

<br>

하지만 다시 생각해보면서 아래의 이유들로 트랜잭션을 도입해야겠다고 생각했습니다.
### 트랜잭션 처리를 해야하는 이유 

1. 영속성 컨텍스트의 생명주기
- osiv가 true인 걸 믿고 영속성 컨텍스트를 사용하기에는 너무 외부 설정에 의존하는 것이라는 생각
- 따라서 트랜잭션 처리를 통해 작업단위별로 영속성 컨텍스트 사용하는 것이 더 적절해보임.
2. DB의 정합성
- 만약 save - delete까지가 이뤄져야 정상적인 처리인 작업일 때, save까지만 db에 반영되고 오류가 나는 상황
- 즉, 의도하지 않은 데이터 반영을 막기 위해 트랜잭션에 의한 롤백 필요.
- 
### 그럼 필요한 서비스 메서드에만 트랜잭션을 걸면 되지 않을까?

위와 같이 생각도 했지만, 아래를 고려해보니 서비스 전체에 걸어주는 것이 낫겠다는 결론을 내렸습니다.

1. 더티체킹이 필요한 부분을 일일히 고려하면서 트랜잭션을 걸어주는 리소스 발생
2. 개발자의 실수로 필요한 부분의 트랜잭션을 빼먹을 위험 발생

추가로 아래 부분에 대한 고민이 생겨서 다음에는 OSIV를 false로 적용하는 방법도 적용해보고 싶습니다!

### 추가: OSIV를 false로 하는 게 좋을까?
- OSIV가 true이면 영속성 컨텍스트가 request ~ response의 생명주기를 가짐.
- 그 과정동안 connection을 갖고있게 됨. connection이 필요하지 않은 부분에서도 불필요하게 connection을 갖고있는 문제.

2024-05-27 08:44 UTC, skylar1220 commented on src/main/java/roomescape/service/WaitingService.java
> +    public void convertWaitingToReservation(final Reservation reservation) {
### 추가1. 필요한 서비스 메서드에만 트랜잭션을 걸면 되지 않을까? NO!

아래를 고려해보니 서비스 전체에 걸어주는 것이 낫겠다는 결론을 내렸습니다.

1. 더티체킹이 필요한 부분을 일일히 고려하면서 트랜잭션을 걸어주는 리소스 발생
2. 개발자의 실수로 필요한 부분의 트랜잭션을 빼먹을 위험 발생

<br>

추가로 아래 부분에 대한 고민이 생겨서 다음에는 OSIV를 false로 적용하는 방법도 적용해보고 싶습니다!

### 추가2. OSIV를 false로 하는 게 좋을까?
- OSIV가 true이면 영속성 컨텍스트가 request ~ response의 생명주기를 가짐.
- 그 과정동안 connection을 갖고있게 됨. connection이 필요하지 않은 부분에서도 불필요하게 connection을 갖고있는 문제.

2024-05-27 08:59 UTC, Deocksoo commented on src/main/java/roomescape/service/WaitingService.java
> +    public void convertWaitingToReservation(final Reservation reservation) {
> 추가1. 필요한 서비스 메서드에만 트랜잭션을 걸면 되지 않을까? NO!

이번 미션에서는 크게 와닿지 않을수도 있지만, 오히려 트랜젝션은 메서드단위로 명시하는 것이 낫다는 의견을 드려요. 
보통 트렌젝션 여부를 판단할 때 클래스 상단까지 올라가는 것보다는, 메서드만 보았을 때에도 트렌젝션의 상태가 어떠한지 알 수 있게 하는 것이 보기 편할 뿐더러
트렌젝션이 의도치 않게 미적용되는 것보다 의도치 않게 적용되는 경우가 시스템 장애 가능성이 더 크다고 봐요.

> 추가2. OSIV를 false로 하는 게 좋을까?

언급해주신 것처럼 문제가 될 여지가 있는데다가, 만에 하나라도 의도치 않은 더티체킹을 유발할 수 있다는 문제가 있어요.
그래서 OSIV는 특별한 이유가 없는 한 꺼두고 모두 트렌젝션으로 처리하는 것이 대개는 더 안전해요.

2024-05-28 09:40 UTC, Deocksoo approved these changes
안녕하세요 커비,
리뷰 끝까지 잘 반영해주셨네요 👍 
단순히 리뷰 내용을 반영하는 것에서 더 나아가 다양한 관점으로 코드에 대해 고민해보신 부분이 인상깊어요.
`내가 쓴 코드 한줄한줄에 이유와 장단점을 설명할 수 있기` 를 목표로 미션 진행하셨는데,
스스로 세우신 미션 목표에 맞게 리뷰 잘 마무리해주신 것 같아요 💯 
처음 의도하신 방향대로 많이 배워가셨기를 바라요.

미션 진행하시느라 고생 많으셨어요.

2024-05-28 09:41 UTC, merged